### ISSUE TITLE
Found an issue with PREG_JIT_STACKLIMIT_ERROR

### ISSUE THREAD

**Issue by PirxDanford** [doctrine/dbal#2941] opened 2017-12-18 15:22 UTC
We are using the version 2.5.13, but the issue is also true for all the following versions of the file
https://github.com/doctrine/dbal/blob/729340d8d1eec8f01bff708e12e449a3415af873/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php#L123

More informations about this can be found here
https://stackoverflow.com/questions/39685883/php-preg-jit-stacklimit-error-inefficient-regex

It would be great that if a solution is found it would be backported.

Script to test, which helped us pinpoint the issue
```
<?php

$version = '5.5.58-0ubuntu0.14.04.1';
echo '<pre>';

var_dump(preg_match('/^(?P<major>\d+)(?:\.(?P<minor>\d+)(?:\.(?P<patch>\d+))?)?/', $version, $versionParts));
if (!preg_match('/^(?P<major>\d+)(?:\.(?P<minor>\d+)(?:\.(?P<patch>\d+))?)?/', $version, $versionParts)) {
    echo "RegEx failed on " . $version . PHP_EOL;

} else {
    echo "RegEx extracted version parts" . PHP_EOL;
    var_dump($versionParts);
}

$pregErrors = [
    PREG_NO_ERROR => 'PREG_NO_ERROR',
    PREG_INTERNAL_ERROR=> 'PREG_INTERNAL_ERROR',
    PREG_BACKTRACK_LIMIT_ERROR => 'PREG_BACKTRACK_LIMIT_ERROR',
    PREG_RECURSION_LIMIT_ERROR => 'PREG_RECURSION_LIMIT_ERROR',
    PREG_BAD_UTF8_ERROR => 'PREG_BAD_UTF8_ERROR',
    PREG_BAD_UTF8_OFFSET_ERROR => 'PREG_BAD_UTF8_OFFSET_ERROR',
    PREG_JIT_STACKLIMIT_ERROR => 'PREG_JIT_STACKLIMIT_ERROR',
];
echo $pregErrors[preg_last_error()] . PHP_EOL;
echo '</pre>';

phpinfo(INFO_GENERAL);

?>
```

**Comment by lcobucci** [comment] 2017-12-19 12:08
@PirxDanford sorry but can you provide more information about that, maybe even a test that confirms the issue?

I've applied a small change on your script and everything seems to work in all supported PHP versions: https://3v4l.org/EbQ7Y

**Comment by Majkl578** [comment] 2017-12-19 12:55
Can't reproduce locally with JIT enabled. Can you please provide information about your PCRE library - version and configuration? Thanks.

**Comment by mikeSimonson** [comment] 2018-01-05 10:25
and php version

**Comment by PirxDanford** [comment] 2018-01-05 10:40
Hi - I am just back from vacation. This error happened on the setup of a colleague. I'll provide more details next week.

**Comment by PirxDanford** [comment] 2018-01-08 13:33
Hi again. So this is pretty tricky to reproduce.

Failing conditions:
- DBAL 2.5.13
- PHP 7.0.26 (with jit enabled)
- Apache 2.4.7
- PCRE 8.38

To prove it really is happening I provide you with this result snippet, from where it should be possible to find all other configuration details:
https://pastebin.com/5bsbM3yC

It will only fail within Apache and not in the CLI, but there could be other setup combinations in which it possibly might fail. Also that we are using a phpbrew version of PHP 7 might be important.

**Comment by mikeSimonson** [comment] 2018-01-08 13:54
Can you check the size that is define on the line ```define PCRE_JIT_STACK_MAX_SIZE``` in the file named ext/pcre/php_pcre.c that phpbrew compile ?

**Comment by PirxDanford** [comment] 2018-01-08 15:03
Yes that line is:
#define PCRE_JIT_STACK_MAX_SIZE (64 * 1024)

Also I set up a VM in the same way now and can reproduce the failure as well, so I can provide details directly now.

**Comment by morozov** [comment] 2021-10-30 21:20
This could be likely resolved by simplifying the regex (https://github.com/doctrine/dbal/pull/4867#issuecomment-945196830). Closing as non-reproducible.

**Closed by morozov** 2021-10-30 21:20 UTC
