### ISSUE TITLE
Support PHP 8.1 Backed Enum's (casting to string or int)

### ISSUE THREAD

**Issue by ThomasLandauer** [doctrine/dbal#5054] opened 2021-11-30 16:07 UTC
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes https://www.php.net/manual/language.enumerations.php
| BC Break    | no

#### Summary

Symfony 5.4 supports an `EnumType` Field in its forms: https://symfony.com/doc/5.4/reference/forms/types/enum.html It would be nice to be able to map this to an entity as-is. Right now, you need to manually transform the `Enum` object to its backed `string` (or `int`). So far, I see three ways to achieve this:

1. Creating a Symfony Data Transformer: https://symfony.com/doc/5.4/form/data_transformers.html#creating-the-transformer
2. Convert it in the entity's setter/getter:
    ```php
    public function setMimetype(?MimetypeEnum $mimetype): self
    {
        $this->mimetype = $mimetype->value;
        return $this;
    }
    public function getMimetype(): ?MimetypeEnum
    {
        return Mimetype::from($this->mimetype);
    }
    ```
3. Setting up a Custom Mapping Type in Doctrine: https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#custom-mapping-types

So instead of having each user figure this out themselves, I'm suggesting to add two new types: `enum_string` and `enum_int`.

**Comment by derrabus** [comment] 2021-11-30 16:21
Duplicate of doctrine/orm#9021

**Closed as completed by derrabus** 2021-11-30 16:22 UTC

**Comment by greg0ire** [comment] 2021-11-30 22:26
Relates to #5036
