### ISSUE TITLE
Unique index does not imply unique column in Oracle

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5508] opened 2022-07-15 21:59 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.7

#### Summary

please see https://dba.stackexchange.com/questions/314472/ora-02270-can-fk-in-oracle-be-defined-on-varchar2-column/314474#314474

#### Current behaviour

https://dbfiddle.uk/?rdbms=oracle_18&fiddle=7de31287a57c063b3304987b06f76137

#### How to reproduce

add unique index and then FK to existing tables using DBAL schema manager

#### Expected behaviour

https://dbfiddle.uk/?rdbms=oracle_18&fiddle=b9e9cf8e0d58247e86dae439ebde578c

with create unique index SQL additional `alter table ... add unique(...) using index ...;` SQL query must be generated

**Comment by morozov** [comment] 2022-07-16 01:09
Please provide a complete scenario that reproduces the issue and the expected behavior in terms of result, not a way to fix the issue.

**Comment by morozov** [comment] 2022-07-16 01:13
@mvorisek please make sure you provide sufficient steps to reproduce the issues you create. Ideally, expressed in code. See #4761 for example. At the moment, there are over 5 issues or pull requests you opened that lack context and are marked as "Requires Feedback".

You've been already asked for a better issue description on multiple occasions but keep posing single-sentence descriptions. This is disrespectful to the maintainers who have to spend their time guessing what exactly the issue is.

If you keep filing issues the way you do, I'll close them as non-reproducible.

**Comment by mvorisek** [comment] 2022-07-16 09:51
Please do not take it as disrespectful. I belive the descriptions are sufficient, well analysed as I was able to fix the issues on my side based on them. Once I analysed them and fixed, for documentation purposes in atk4/data code, I posted the issues officially, so they can be fixed in the DBAL directly.

But I understand you want a short repro code in each issue ticket to allow to reproduce faster. Please allow it to sit here fow a while. Maybe someone else will post the repro code here or even fix the issues itself. If not, please given me a time I will add the repro code to each of my outstanding issue.

**Comment by morozov** [comment] 2022-08-18 15:58
Closing due to the lack of feedback.

**Closed as not planned by morozov** 2022-08-18 15:58 UTC
Labels: Cannot Reproduce

**Comment by mvorisek** [comment] 2022-08-18 16:13
This problem is obvious, as the generated SQL cannot work as prooven in dbfiddle
