### ISSUE TITLE
DateTimeImmutable error with default value CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by tok-amsiq** [doctrine/dbal#2859] opened 2017-09-12 13:06 UTC
I have just changed all my DateTime to DateTimeImmutable and I experienced an issue with the ones where I had a CURRENT_TIMESTAMP default value:

     @ORM\Column(type="datetime_immutable", options={"default"="CURRENT_TIMESTAMP"})
The issue occurs when I use the schema-tool to update my database and I get the following error:

    'ALTER TABLE accounts CHANGE created_on created_on DATETIME DEFAULT 'CURRENT_TIMESTAMP' NOT NULL'

So I learned that the schema-tool tries to execute a query with a string as default value, which is the reason for the error. If I use the DateTime type instead, it will execute it as expected. 
I went digging and I found the method 'getDefaultValueDeclarationSQL' in the AbstractPlatform class, where I found a solution for the issue.

    public function getDefaultValueDeclarationSQL($field)
    {
        $default = empty($field['notnull']) ? ' DEFAULT NULL' : '';

        if (isset($field['default'])) {
            $default = " DEFAULT '".$field['default']."'";
            if (isset($field['type'])) {
                if (in_array((string) $field['type'], array("Integer", "BigInt", "SmallInt"))) {
                    $default = " DEFAULT ".$field['default'];
                } elseif (in_array((string) $field['type'], array('DateTime', 'DateTimeTz')) && $field['default'] == $this->getCurrentTimestampSQL()) {
                    $default = " DEFAULT ".$this->getCurrentTimestampSQL();
                } elseif ((string) $field['type'] == 'Time' && $field['default'] == $this->getCurrentTimeSQL()) {
                    $default = " DEFAULT ".$this->getCurrentTimeSQL();
                } elseif ((string) $field['type'] == 'Date' && $field['default'] == $this->getCurrentDateSQL()) {
                    $default = " DEFAULT ".$this->getCurrentDateSQL();
                } elseif ((string) $field['type'] == 'Boolean') {
                    $default = " DEFAULT '" . $this->convertBooleans($field['default']) . "'";
                }
            }
        }
        return $default;
    }

And if I add 'DateTimeImmutable' to the following line:

    } elseif (in_array((string) $field['type'], array('DateTime', 'DateTimeTz', 'DateTimeImmutable')) && $field['default'] == $this->getCurrentTimestampSQL()) {
        $default = " DEFAULT ".$this->getCurrentTimestampSQL();
    }

It works as intended. Any chance this can be implemented? I haven't seen any documentation about this being intentional, so I figured it wasn't.

**Comment by Ocramius** [comment] 2017-09-12 13:18
Duplicate of https://github.com/doctrine/doctrine2/issues/6698 ?

**Comment by tok-amsiq** [comment] 2017-09-12 13:27
I don't believe so no. This is only an issue with the 'newly' released DateTimeImmutable and works fine with DateTime.

**Comment by Majkl578** [comment] 2017-09-13 00:03
This should be fixed by https://github.com/doctrine/dbal/pull/2835, but we should consider a separate fix for 2.6 since that PR can't go to 2.6,...

**Comment by tok-amsiq** [comment] 2017-09-13 06:42
It has been fixed by #2835, but since I have no timeline for when that PR will be released, a fix for 2.6 would be welcomed with open arms from my part.

**Comment by Ocramius** [comment] 2017-09-13 08:23
The fact that #2835 fixes this as a side-effect is not OK for this patch to go through: needs a dedicated test and an ad-hoc fix for 2.6 if you need it there.

**Comment by Ocramius** [comment] 2017-09-13 08:23
And yep, still using `(string)` casts ;-)

**Comment by tok-amsiq** [comment] 2017-09-13 09:42
I gave it a go at #2861 with (string) casts ;-) 
I also added DateImmutable, but since there was no test case for Date, I didn't figure DateImmutable needed one.

**Closed** 2017-11-18 23:29 UTC

**Comment by spacetraveller** [comment] 2018-05-12 00:34
Thanks for breaking the ability to have the option of having a CURRENT_TIMESTAMP set to default. We use Symfony to handle migrations and have other technologies which user the DB, and now due to this "fix" (or downgrade), I'm unable to set a default timestamp into the schema. Not happy about this "fix" at all, why was it removed ? Makes no sense and is a BAD decision, giving LESS flexibility to use developers.

**Comment by Majkl578** [comment] 2018-05-12 00:48
@spacetraveller Please open new issue for your problem referencing this one. If possible, also provide a test case for the broken use case. Thanks.

**Comment by spacetraveller** [comment] 2018-05-16 23:07
Hey Majk578, please see https://github.com/doctrine/dbal/issues/3142 for the detaiils of the issue.

**Comment by Ocramius** [comment] 2018-05-16 23:35
Reminder to not use `default` with mapped fields, as it breaks the symmetry between written and read data.
