### ISSUE TITLE
Invalid mysql is produced in MySQLSchemaManager::selectTableColumns

### ISSUE THREAD

**Issue by dsentker** [doctrine/dbal#6274] opened 2024-01-25 08:43 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.7.3

#### Summary
The method `MySQLSchemaManager::selectTableColumns` ([source](https://github.com/doctrine/dbal/blob/3.7.3/src/Schema/MySQLSchemaManager.php#L438)) produces SQL which is not valid. In my case, here is (simplified) the query which was created:

```sql
SELECT c.COLUMN_NAME        AS field,
       IF(
                       c.COLUMN_TYPE = 'longtext'
                   AND EXISTS(SELECT *
                              from information_schema.CHECK_CONSTRAINTS
                              WHERE CONSTRAINT_SCHEMA = 'app'
                                AND TABLE_NAME = c.TABLE_NAME -- THE ERROR IS HERE
                                AND CHECK_CLAUSE = CONCAT(
                                      'json_valid(`',
                                      c.COLUMN_NAME,
                                      '`)'
                                  )),
                       'json',
                       c.COLUMN_TYPE
           )                AS type

FROM information_schema.COLUMNS c
         INNER JOIN information_schema.TABLES t
                    ON t.TABLE_NAME = c.TABLE_NAME
WHERE c.TABLE_SCHEMA = "app"
  AND t.TABLE_SCHEMA = "app"
  AND t.TABLE_TYPE = 'BASE TABLE'
  AND t.TABLE_NAME = "doctrine_migration_versions"
ORDER BY ORDINAL_POSITION
```

#### Current behaviour
The query leads to the message "**_[1052] Column 'TABLE_NAME' in where clause is ambiguous_**" which is produced in the AND EXISTS() subquery.

This errors leads to [unusable doctrine/migrations](https://github.com/doctrine/migrations/issues/1395) command calls as this method is invoked.

#### How to reproduce

Run the query i pasted here.

#### Expected behaviour

The sql is valid.

**Comment by nroehling** [comment] 2024-01-25 08:52
I have the same issue

**Comment by derrabus** [comment] 2024-01-25 20:05
Closing as this is not a bug, see https://github.com/doctrine/dbal/pull/6275#issuecomment-1910705178

**Closed as not planned by derrabus** 2024-01-25 20:05 UTC
