### ISSUE TITLE
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'add_new_column' on table 'user'. with sqLite

### ISSUE THREAD

**Issue by Vittalks** [doctrine/dbal#2615] opened 2017-01-25 07:29 UTC
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'add_new_column' on table 'user'. with sqLite

every time unit test cases run after adding new column to migration file failed

but when run php artisan migrate with mysql run successfully

please help out

**Comment by Ocramius** [comment] 2017-01-25 07:57
Closing: this is insufficient information to file a bug report, and you need to first flesh out whether the problem is on your side, or whether it's an actual bug in the DBAL.

**Closed by Ocramius** 2017-01-25 07:57 UTC
