### ISSUE TITLE
OraclePlatform newly escapes backslahes and this leads to a problem

### ISSUE THREAD

**Issue by vavra** [doctrine/dbal#3328] opened 2018-10-23 11:25 UTC
### Bug Report

This statement should return exactly one row and returns nothing

```php
$sql = "SELECT 1  FROM DUAL WHERE '_123' LIKE "
   . $this->xgCon->getDatabasePlatform()->quoteStringLiteral('\\_%') . " ESCAPE '\\'";
```

Executed at version
"name": "doctrine/dbal",
"version": "v2.8.0",

At version 
 "name": "doctrine/dbal",
  "version": "v2.5.1",
there is missing function quoteStringLiteral in OraclePlatform

The error is that newer version has in OraclePlatform function quoteStringLiteral  with row 
$str = str_replace('\\', '\\\\', $str); // Oracle requires backslashes to be escaped aswell.

Please remove the function quoteStringLiteral from OraclePlatform.
The only thing that must be esacaped is a quote char and this is done at AbstractPlatform.

Note. This query 
```sql
SELECT '\' FROM Dual;
```
executed at Sql Developer is valid, no backslash chars must be escaped and exactly one backshlash is returned.

**Comment by Ocramius** [comment] 2018-10-23 11:51
Please upgrade your DBAL version before reporting an issue

**Comment by vavra** [comment] 2018-10-23 12:03
Well, it is obvious that in the latest source the bad line still remains:
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/OraclePlatform.php

**Comment by morozov** [comment] 2018-10-23 13:33
The proposed approach seems legit:
```php
$platform = $conn->getDatabasePlatform();
$query = $platform->getDummySelectSQL("'\\'");
var_dump($query);
var_dump($conn->fetchColumn($query));

string(20) "SELECT '\' FROM DUAL"
string(1) "\"
```
The additional escaping is not needed by default, and https://github.com/doctrine/dbal/commit/1222e946f005e43d8f3aa628b6415a86fe281e91 doesn't contain any functional tests explaining when exactly it's needed.

**Comment by ostrolucky** [comment] 2018-11-22 14:52
Dupe of https://github.com/doctrine/dbal/issues/2926
Fixed by https://github.com/doctrine/dbal/pull/3330

**Closed by ostrolucky** 2018-11-22 14:52 UTC
Labels: Bug, Oracle, Quoting
