### ISSUE TITLE
Error: Undefined constant 'OCI_NO_AUTO_COMMIT'

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5168] opened 2022-01-07 17:19 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.2.x

#### Current behaviour

Currently, when OCI8 ext is not available, the following php notice is shown:

```
Error: Undefined constant 'OCI_NO_AUTO_COMMIT'
```

trace:

```
/__w/data/data/vendor/doctrine/dbal/src/Driver/OCI8/Driver.php:28
/__w/data/data/vendor/doctrine/dbal/src/Connection.php:325
/__w/data/data/vendor/doctrine/dbal/src/Connection.php:1506
```

#### How to reproduce

run OCI8 tests without OCI8 ext installed

#### Expected behaviour

When OCI8 is unavailable, better error message/exception should be thrown.

Other drivers behaviour should be checked as well and the exception should be normalized to one common class.

**Comment by morozov** [comment] 2022-01-07 19:18
> Error: Undefined constant 'OCI_NO_AUTO_COMMIT'

From the above error message, it is pretty much obvious that the extension is not loaded. There is no point in running OCI8 tests without the extension.

> /__w/data/data/vendor/doctrine/dbal/src/Driver/OCI8/Driver.php:28
> /__w/data/data/vendor/doctrine/dbal/src/Connection.php:325
> /__w/data/data/vendor/doctrine/dbal/src/Connection.php:1506

From the stack trace, it looks like the driver is trying to connect, so the usage of the constant is justified.

Not being to even declare a class without the extension loaded (I cannot find the corresponding patch) would be a more realistic issue.

**Comment by morozov** [comment] 2022-01-12 21:42
Closing as the current behavior is by design.

**Closed as completed by morozov** 2022-01-12 21:42 UTC
Labels: Won't Fix, oci8
