### ISSUE TITLE
  Can not change column nullable after upgrade to 2.10.3 

### ISSUE THREAD

**Issue by dyaskur** [doctrine/dbal#4254] opened 2020-09-04 22:58 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.10.3

#### Summary
this migration code is work perfectly at 2.10.2 version

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AlterNullableOutletsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table(
            'outlets',
            function (Blueprint $table) {
                $table->unsignedBigInteger('province_id')->nullable()->change();
            }
        );
        Schema::table(
            'outlets',
            function (Blueprint $table) {
                $table->unsignedBigInteger('city_id')->nullable()->change();
            }
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table(
            'outlets',
            function (Blueprint $table) {
                $table->unsignedBigInteger('province_id')->nullable(false)->change();
            }
        );
        Schema::table(
            'outlets',
            function (Blueprint $table) {
                $table->unsignedBigInteger('city_id')->nullable(false)->change();
            }
        );
    }
}
```
#### Current behaviour

But after I upgrade to 2.10.3 return error below:

```
In Connection.php line 671:

  SQLSTATE[HY000]: General error: 1 no such index: IDX_A9CE40BE946114A (SQL:
  DROP INDEX IDX_A9CE40BE946114A)


In PDOConnection.php line 72:

  SQLSTATE[HY000]: General error: 1 no such index: IDX_A9CE40BE946114A


In PDOConnection.php line 67:

  SQLSTATE[HY000]: General error: 1 no such index: IDX_A9CE40BE946114A
```
#### How to reproduce

My command to run the migration is
`php artisan migrate:fresh --env=testing --database=sqlite_testing --force
`
#### Expected behaviour

How to solve it?

**Comment by greg0ire** [comment] 2020-09-05 06:17
Duplicate of #4243

**Closed by greg0ire** 2020-09-05 06:17 UTC
