### ISSUE TITLE
setMiddlewares in Doctrine\DBAL\Configuration called after createConnection

### ISSUE THREAD

**Issue by mrAndersen** [doctrine/dbal#5408] opened 2022-05-22 07:23 UTC
Reported already here [#1515](https://github.com/doctrine/DoctrineBundle/issues/1515)
Lads from [DoctrineBundle](https://github.com/doctrine/DoctrineBundle) redirected me here

doctrine/doctrine-bundle is 2.6.2
doctrine/orm is 2.12.0
symfony/runtime is 6.0.7
Reproducer https://github.com/mrAndersen/doctrine-bundle-middleware-bug

In short, middlewares are not working in doctrine as prior to 2.6.2 doctrine bundle, because setMiddleware is called after actual DBAL Connection is created and thus won't allow wrapping functional to work

**Comment by dmaicher** [comment] 2022-05-22 08:04
~~I actually think this is not a DBAL issue. See https://github.com/doctrine/DoctrineBundle/issues/1515#issuecomment-1133840375~~

**Comment by greg0ire** [comment] 2022-05-22 11:32
This reminds me of https://github.com/doctrine/dbal/issues/5366 … it's not 100% clear why this should be a DBAL issue though.
After reading #1515, it seems that the issue would be that the DBAL does not allow to have a circular dependency between a middleware and a connection. Why do you need that circular dependency in the first place? I'm not sure we should encourage circular dependencies.

**Comment by morozov** [comment] 2022-05-22 17:24
@mrAndersen what code in the DBAL calls `setMiddlewares()` after `createConnection()`?

**Comment by mrAndersen** [comment] 2022-05-22 17:37
@morozov I am not directly calling those, you can check repoducer repo here https://github.com/mrAndersen/doctrine-bundle-middleware-bug, DoctrineBundle is calling those in compiled symfony container, but seems like i was incorrectly creating middleware trying to wrap actual Connection class instead of using decorator as @dmaicher pointed in  [#1515](https://github.com/doctrine/DoctrineBundle/issues/1515) This new middleware logic is a bit confusing...

**Comment by morozov** [comment] 2022-05-22 17:47
@mrAndersen what is the issue in the DBAL you'd like to get addressed? Please make sure the issue is described in full so that it's not necessary to hop over multiple repositories to get the context.

If you believe the issue you're experiencing should be addressed in the DBAL, please provide a reproducer that doesn't use any additional dependencies.

**Comment by mrAndersen** [comment] 2022-05-22 17:51
@morozov I am not the one who was addressing any issues with DBAL, as i said in starting comment of this, I was redirected here from [#1515](https://github.com/doctrine/DoctrineBundle/issues/1515), so unless guys from DoctrineBundle don't have any comments, this can be closed.

**Closed as not planned** 2022-05-22 18:07 UTC
Labels: Configuration
