### ISSUE TITLE
Comparator incorrectly diffs default values with boolean type

### ISSUE THREAD

**Issue by MouLingtao** [doctrine/dbal#3411] opened 2018-12-14 23:15 UTC
in commit [4389a25](https://github.com/doctrine/dbal/commit/4389a258c0b6a6c47099e65a54db98904d7235b2) we modified the comparison method for the default values of the columns.
However, after the revision, new problems have arisen.
We usually set the column's default value of the 'Boolean' type to false or true, but in MySQL, the Boolean is stored as tinyint, which has a value of 0 or 1, so in this new comparison method, the default value compare result is always false.

**Comment by MouLingtao** [comment] 2018-12-14 23:19
Sorry. I have translated it with Google, and I may not have stated it clearly. Please understand.
I posted the original Chinese words for reference.

在提交4389a25中，我们修改了列的默认值的比较方法。
但是，修改之后，出现了新的问题。
我们通常设置Boolean类型的列的默认值为true或false，而且在MySQL中，Boolean以tinyint存储的，它的默认值会被转化成1或0，所以在这个新的比较方法中，由于比较更加严格了，导致了默认值的比较结果恒定为假。

**Comment by morozov** [comment] 2018-12-15 17:50
This must be a duplicate of #3377. Please try upgrading to `v2.9.1`.

**Closed** 2018-12-16 17:48 UTC
Labels: Bug, Duplicate, Schema Comparison
