### ISSUE TITLE
Mysql Schema Diff always see difference when there is a ManyToOne nullable

### ISSUE THREAD

**Issue by DavidGarciaCat** [doctrine/dbal#2822] opened 2017-08-25 12:43 UTC
Hello,

I've been told here https://github.com/doctrine/DoctrineMigrationsBundle/issues/201#issuecomment-324897373 that Doctrine Migrations is using this repo to build the migration queries, so adding the issue here:

For an unknown reason, every time I am running the `app/console doctrine:migrations:diff` command I get a new migration file, even if I don't have new database updates.

The `up` and `down` methods are including queries to update my tables, but just those columns that are mapping other entities or those columns that allow `null` values.

This is an example for one of the entities (mapped entity), all of them are doing the same:

```php
class Version20170808093252 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE Purpose CHANGE campaign_id campaign_id INT DEFAULT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE Purpose CHANGE campaign_id campaign_id INT DEFAULT NULL');
    }
```

These are the ORM details on my entity:

```php
/**
 * @ORM\Table()
 * @ORM\Entity()
 */
class Purpose
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Campaign", inversedBy="purposes")
     **/
    private $campaign;

    // Other properties on this Entity, not involved on this issue
}
```

And this is for an entity that allows `null` values:

```php
class Version20170808093252 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE address CHANGE line1 line1 VARCHAR(100) DEFAULT NULL, CHANGE line2 line2 VARCHAR(100) DEFAULT NULL, CHANGE line3 line3 VARCHAR(100) DEFAULT NULL, CHANGE town town VARCHAR(100) DEFAULT NULL, CHANGE county county VARCHAR(100) DEFAULT NULL, CHANGE postcode postcode VARCHAR(10) DEFAULT NULL, CHANGE line4 line4 VARCHAR(100) DEFAULT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE address CHANGE line1 line1 VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE line2 line2 VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE line3 line3 VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE line4 line4 VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE town town VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE county county VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE postcode postcode VARCHAR(10) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
    }
```

And the ORM details of this entity:

```php
/**
 * @ORM\Table(name="address")
 * @ORM\Entity()
 */
class Address
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="line1", type="string", length=100, nullable=true)
     */
    private $line1;

    /**
     * @ORM\Column(name="line2", type="string", length=100, nullable=true)
     */
    private $line2;

    /**
     * @ORM\Column(name="line3", type="string", length=100, nullable=true)
     */
    private $line3;

    /**
     * @ORM\Column(name="line4", type="string", length=100, nullable=true)
     */
    private $line4;

    /**
     * @ORM\Column(name="town", type="string", length=100, nullable=true)
     */
    private $town;

    /**
     * @ORM\Column(name="county", type="string", length=100, nullable=true)
     */
    private $county;

    /**
     * @ORM\Column(name="postcode", type="string", length=10, nullable=true)
     */
    private $postcode;
}
```

Also, all `Doctrine/*` vendors / versions I am using, in case there's a know issue. I have tried to update all of them just to be sure these versions don't have a known issue, but I am getting the same behaviour after run `composer update doctrne/* --with-dependencies`

```
$ composer show doctrine/*
doctrine/annotations                v1.4.0  Docblock Annotations Parser
doctrine/cache                      v1.6.1  Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.4.0  Collections Abstraction library
doctrine/common                     v2.7.2  Common Library for Doctrine projects
doctrine/data-fixtures              v1.2.2  Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.5.12 Database Abstraction Layer
doctrine/doctrine-bundle            1.6.8   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.0   Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle   2.3.0   Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle v1.2.1  Symfony DoctrineMigrationsBundle
doctrine/inflector                  v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 v1.5.0  Database Schema migrations using Doctrine DBAL
doctrine/orm                        v2.5.6  Object-Relational-Mapper for PHP
```

I have thought my `charset` settings may affect, but when I check the tables and columns I can see they're already fine:

```sql
SELECT DISTINCT TABLE_COLLATION, COLLATION_NAME, CHARACTER_SET_NAME
FROM   information_schema.`TABLES` T,
       information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA
WHERE  CCSA.collation_name = T.table_collation
AND    T.table_schema = "database_name";
```

<img width="369" alt="screen shot 2017-08-08 at 11 09 17" src="https://user-images.githubusercontent.com/7809429/29067318-1556753a-7c2a-11e7-841f-8342dd636ada.png">

```sql
SELECT DISTINCT CHARACTER_SET_NAME, COLLATION_NAME
FROM   information_schema.`COLUMNS`
WHERE  table_schema = "database_name";
```

<img width="255" alt="screen shot 2017-08-08 at 11 13 42" src="https://user-images.githubusercontent.com/7809429/29067486-afb178fa-7c2a-11e7-8db4-cccae04bfc45.png">

Finally, just in case it may help, some extra data of my local environment:

```
$ uname -v
Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64

$ composer show symfony/symfony*
symfony/symfony v2.8.25 The Symfony PHP framework

$ php -v
PHP 7.0.21 (cli) (built: Jul 29 2017 09:17:51) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.21, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
    with blackfire v1.17.3~mac-x64-non_zts70, https://blackfire.io, by SensioLabs

$ mysql -V
mysql  Ver 15.1 Distrib 10.2.7-MariaDB, for osx10.12 (x86_64) using readline 5.1
```

Any help and/or suggestions will be really appreciated.

Many thanks,

**Comment by mikeSimonson** [comment] 2017-08-25 13:17
duplicate of #2817

**Closed** 2017-08-25 13:21 UTC
Labels: Duplicate

**Comment by DavidGarciaCat** [comment] 2017-08-25 13:51
@mikeSimonson @Ocramius please note the issue #2817 is talking about `NULL` values, however mine references too mapped entities.
