### ISSUE TITLE
Type::convertToPHPValue is not working for Type String

### ISSUE THREAD

**Issue by ziegi** [doctrine/dbal#5681] opened 2022-09-20 07:14 UTC
### Bug Report

DBAL Version 3.4   (at least since 3.1)

#### Summary

I think this is related to Issue #5228
In PHP8 PDO returned always string, so no conversion has been necessary.
As in PHP8.1 we get integers back there has to be a way to cast them.
While this is working for other types that implement their own Type::convertToPHPValue function
the class StringType relies on its parent class Type and return the unchanged value.
I assume this is an old Bug that never got detected due to the older PDO returning strings anyway.

#### Current behaviour

StringType:::convertToPHPValue does no type casting

#### How to reproduce

see Code calling parents::convertToPHPValue

#### Expected behaviour

StringType:::convertToPHPValue should return a string

**Comment by derrabus** [comment] 2022-09-20 07:50
Please provide steps to reproduce your issue.

**Comment by ziegi** [comment] 2022-09-20 08:32
It is easy visible from the code:
https://github.com/doctrine/dbal/blob/3.4.x/src/Types/StringType.php
There is no function convertToPHPValue implemented, so it falls back to 
https://github.com/doctrine/dbal/blob/3.4.x/src/Types/Type.php
with the implementation:
```
    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return $value;
    }
```
To reproduce use something along:
```
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\DriverManager;

$params = [
    'host' => ...,
    'port' => ...,
    'user' => ....,
    'password' => ...,
    'dbname' => ....,
    'driver' => 'pdo_mysql',
    'charset' => 'utf8mb4'
];
$connection = DriverManager::getConnection($params, new Configuration());
$connection->connect();
$result = $connection->fetchOne('SELECT 1');
$stringResult = $connection->convertToPHPValue($result, 'string');
$floatResult = $connection->convertToPHPValue($result, 'float');

var_dump($result);
var_dump($stringResult);
var_dump($floatResult);

```
This will output
```
int(1)
int(1)
double(1)
```
Note the second value should be string

**Comment by derrabus** [comment] 2022-09-20 13:28
Well, this is not how DBAL's type system works. The DBAL types are meant to convert database types to corresponding (!) PHP types and vice versa. The `StringType` for instance is not meant to cast arbitrary database values to string, it is meant to be used on values that the database itself considers to be a string (e.g. a `VARCHAR`). In your case, the value you're selecting is clearly an `INT`.

Closing, as this is not a bug.

**Closed as not planned by derrabus** 2022-09-20 13:28 UTC
Labels: Invalid, Types, Type Conversion

**Comment by ziegi** [comment] 2022-09-20 14:32
Well, 
i won't argue over the DBAL's type system, as do not know enough of the design background.

But as this is the DBAL Part and not the ORM part, the system can not have any clue on 
what the database thinks the type of the value is.
For example the boolean type gets also reported as integers from the database and is 
converted by the BooleanType::convertToPHPValue.
As there is no knowledge about the database without examining the tabel types, which is 
not done on this layer, it is left to the user to call the conversion functions with the desired
target type. 
So there is the function named "convertToPHPValue" which accepts arbitary type names,
and it works for all types, but the string type. If this is by design, than thats  peculiar to me.

For example if the query returns a string, I am allowed to cast it tho other types with the exact function:
```
$result = $connection->fetchOne('SELECT "1"');
$stringResult = $connection->convertToPHPValue($result, 'string');
$intResult = $connection->convertToPHPValue($result, 'integer');


var_dump($result);
var_dump($intResult);
var_dump($floatResult);

string(1) "1"
int(1)
double(1)

```

**Comment by ziegi** [comment] 2022-09-20 14:37
```
$result = $connection->fetchOne('SELECT TRUE');
$stringResult = $connection->convertToPHPValue($result, 'string');
$intResult = $connection->convertToPHPValue($result, 'integer');
$boolResult = $connection->convertToPHPValue($result, 'boolean');
$floatResult = $connection->convertToPHPValue($result, 'float');

var_dump($result);
var_dump($intResult);
var_dump($stringResult);
var_dump($boolResult);
var_dump($floatResult);

int(1)
int(1)
int(1)
bool(true)
double(1)
```

**Comment by derrabus** [comment] 2022-09-20 20:52
I'm sorry that the type system does not work as you expected it to. But it does work as intended and documented, so there's no bug to fix.
