### ISSUE TITLE
`fetchOne()` & `fetchFirstColumn()` ambiguity

### ISSUE THREAD

**Issue by hvt** [doctrine/dbal#4336] opened 2020-10-12 08:19 UTC
### Bug Report

Hey there, we started using Doctrine 3 DBAL for a new project and were bitten by the (in our opinion) ambiguity in naming of both `fetchOne()` and `fetchFirstColumn()` (and their `iterate*()` counterpart).

With `fetchOne()` we would expect retrieving the entire first row, while in fact you get the first row's first column. The method's documentation does indeed explains what the method does. Although, a better name - in our opinion - would be `fetchFirstColumn()`.

However, we then find out this method already exists, so we used that. Finding out that method returns an array. Looking at the method documentation, it returns all the row's first columns. Without any `all` or plural wording in the name, this confused us.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.x

#### Summary

Knowing this is a hard BC break for Doctrine 3, we are wondering what the exact rationale behind the wording of these two methods was. We would also like to suggest alternative names, although assuming it is probably too late for this. Nevertheless eager to know what you all think.

| old name | suggested new name | rationale |
|---|---|---|
| `fetchOne` | `fetchFirstColumn` | One could hint at the first row or the first column. In the new naming, is explicitly states what will be returned. |
| `fetchFirstColumn` | `fetchAllFirstColumn` (or `fetchAllFirstColumns`) | Specifically mentioning that one can expect multiple results (`..All..`), and explicitly say it returns the first column of a row only. This is more in line with the three other `fetchAll*()` methods. Exactly in line would be the first option (singular column), that reads a bit weird so plural columns could be an option too. |
| `iterateColumn` | `iterateFirstColumn` | Specifically mention what column will be iterated over. |

**Comment by morozov** [comment] 2022-02-11 23:41
> we are wondering what the exact rationale behind the wording of these two methods was.

Please see the discussion starting https://github.com/doctrine/dbal/pull/4019#issuecomment-635174952.

The existing naming is not a bug or a BC break as it's reported and there are no plans to change the API for the sake of changing the API, so I will close this issue.

**Closed by morozov** 2022-02-11 23:41 UTC
