### ISSUE TITLE
DBAL Docs Display Master Rather than 2.5

### ISSUE THREAD

**Issue by chrisguitarguy** [doctrine/dbal#2751] opened 2017-06-27 13:53 UTC
For instance, [this documentation page](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#pdo-pgsql) states that the various `ssl*` options are supported beyond `sslmode`, but the [driver itself](https://github.com/doctrine/dbal/blob/v2.5.12/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php) doesn't actually support them in 2.5.

Is there a reason why `master` is being used for the public docs? Seems like an extremely bad idea.

**Comment by Ocramius** [comment] 2017-06-28 04:26
Duplicate of https://github.com/doctrine/doctrine-website-sphinx/issues/149

**Closed by Ocramius** 2017-06-28 04:26 UTC
