### ISSUE TITLE
`doctrine:migrations:diff` generates code to create sequence on a filtered table

### ISSUE THREAD

**Issue by Gwalchmei** [doctrine/dbal#3986] opened 2020-05-04 12:30 UTC
With the code 

```
/**
 * @ORM\Table(name="EXISTING_TABLE")
 */
class ExistingEntity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\SequenceGenerator(sequenceName="EXISTING_SEQUENCE")
     * @ORM\Column(type="integer")
     */
    private $id;
 ...
}
```

and the config

```
doctrine:
    dbal:
        schema_filter: /^SHOULD_MIGRATE_TABLE_/
        ...
```

I expect the command `doctrine:migrations:diff` to generate nothing **but** it generates the following :

```
$this->addSql('CREATE SEQUENCE EXISTING_SEQUENCE START WITH 1 MINVALUE 1 INCREMENT BY 1');
```

The `schema_filter` is used to filter the table names but I did not find an equivalent to filter the sequences.

I guess I could create a `@ORM\CustomIdGenerator` but i'm not sure it is a good solution.

**Comment by stof** [comment] 2020-05-04 13:16
And actually, I was able to transfer the issue...

**Comment by stof** [comment] 2020-05-04 15:06
What happens if you actually remove the schema filter ? I think that this might be caused by your schema filter excluding the existing sequence when loading the existing schema.

**Comment by Gwalchmei** [comment] 2020-05-07 16:31
If I remove the schema_filter, it does not generate migration code to create the existing sequence.

If I edit the schema_filter like this :

```
schema_filter: /^SHOULD_MIGRATE_TABLE_|EXISTING_SEQUENCE/
```

It does not generate migration code to create the sequence.

Updating the [documentation](https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#manual-tables) and the [configuration reference](https://symfony.com/doc/current/bundles/DoctrineBundle/configuration.html) to inform that it filters tables **and** other objects may be enough

**Comment by stof** [comment] 2020-05-07 17:06
This indeed looks like a documentation issue. This option is about filtering the schema, not just tables (otherwise, it would be called `table_filter`).
I suggest you to open PRs to the relevant documentations then.

**Comment by goetas** [comment] 2020-05-08 06:20
https://github.com/doctrine/DoctrineMigrationsBundle/pull/322 has been merged

**Closed** 2020-05-25 13:14 UTC
