### ISSUE TITLE
Out of memory when connection unavailable

### ISSUE THREAD

**Issue by tostiheld** [doctrine/dbal#3023] opened 2018-02-16 09:13 UTC
Whenever I forget to start a mariadb/mysql server instance on my dev machine, I get an out of memory error.

```
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 20480 bytes) in /home/<irrelevant>/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 47
```

If I remember correctly there was a message saying the connection was unavailable previously.

I have both PHP 7.0.27 and 7.1.14 on my machine, the error occurs with both versions.

**Comment by Ocramius** [comment] 2018-02-16 09:48
Sounds like PDO is producing a ridiculous exception message? https://github.com/doctrine/dbal/blob/63efa539343a8e6d296b259ca322de981b213498/lib/Doctrine/DBAL/Driver/PDOConnection.php#L47

**Comment by morozov** [comment] 2018-02-16 16:32
@tostiheld could you try reproducing the issue in isolation like:
```php
$conn = \Doctrine\DBAL\DriverManager::getConnection([
    'driver' => 'pdo_mysql',
    'host' => 'non-existin-host',
    'user' => 'root',
    'password' => '',
    'dbname' => 'mysql',
]);

try {
    $conn->connect();
} catch (Exception $e) {
    echo $e->getMessage(), PHP_EOL;
    var_dump(memory_get_peak_usage());
}
```
It works as expected for me:
```
An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

int(1111312)
```

**Comment by tostiheld** [comment] 2018-02-16 17:59
I get:

```
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
int(806600)
```

Also this is my mariadb version:
```
mysql  Ver 15.1 Distrib 10.2.12-MariaDB, for Linux (x86_64) using readline 5.1
```

Seems like the bug is somewhere else, although it's weird to me that it surfaces here.

**Comment by morozov** [comment] 2018-02-16 18:12
```
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
```
Is this what you would expect to get in your case? It usually means that the MySQL socket path is incorrectly configured in PHP or there's no socket (which will be the case when the server is not running).

You can try capturing the result of `memory_get_usage()` in your code or in DBAL somewhere close to where the OOM happens and see if it's potentially used somewhere else, not in DBAL or PDO.

**Comment by tostiheld** [comment] 2018-02-16 18:15
I would think that this is the desired behaviour, yes, because an oom error kills the php script. It's different than the error you got, so I don't know if that is an issue.

I will try to troubleshoot more tomorrow when I have time

**Comment by magnetik** [comment] 2018-03-09 10:02
I think I'm facing this with PHP 7.2.3 (from deb sury)

**Comment by morozov** [comment] 2018-07-22 15:17
@jeulun please see the code snippets above. Can you reproduce the error using them? If not, what is missing?

No, there are no updates.

**Comment by jeulun** [comment] 2018-07-22 15:32
My exact error is this: PHP Fatal error:  Out of memory (allocated 3527409664) (tried to allocate 20480 bytes) in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 50

I got this when I am trying to deploy my Laravel project to the google cloud platform. Sorry if its not related to the error mentioned above, I will delete my comments.

**Comment by tostiheld** [comment] 2018-07-22 16:06
Sounds like the same error to me though

**Comment by jeulun** [comment] 2018-07-22 16:09
How do I apply the above snippet to reproduce this issue? just copy the code into PDOConnection.php and redeploy?

**Comment by jeulun** [comment] 2018-07-22 16:53
Yeah I am referring to the comment by @morozov.
I have no issue if I am hosting locally using the `php artisan serve` command, only get the error when I deploy the application, anyway I still do not know how to use the snippet @.@

**Comment by jeulun** [comment] 2018-07-22 17:00
Well I followed this solution just now: https://stackoverflow.com/questions/49136944/laravel-fatal-error-memory-bytes-exhausted-with-remote-database
Then when I tried to host locally using `php artisan serve` and I get the same error as I mentioned above but with 262144 bytes instead of 20480 bytes. (Undoing the solution then I can host locally with no issue). I tried to deploy my application both before and after applying the solution, but both way also end up the same error with 20480 bytes. Maybe its a problem on handling exception?

**Comment by tostiheld** [comment] 2018-07-22 17:11
Yes, the problem is probably with handling the exception. The different sizes have to do with the memory configuration in your php.ini (memory limit of a script to be precise).

**Comment by jeulun** [comment] 2018-07-22 17:18
According to google cloud compute, I can change the php.ini settings if I just include one php.ini file at the same level as my app.yaml before deploy, I did change the memory limit in my php.ini file a few times to 1024M and -1. But still getting the same error after deployment.  

Why is that I can host locally with no use but encounter this error during deployment? Anyway to remove the exception handling process?

**Comment by yucolabjames** [comment] 2019-01-15 03:46
I am running into the same problem regardless of whether it's in Windows 10 XAMPP or Ubuntu 16.04 Vagrant under apache, tested with php7.1, php 7.2 and php 7.3.

My php is configured to `memory_limit = -1`

**Comment by Ocramius** [comment] 2019-01-15 10:36
The issue here isn't PDO: the error handler attempts to recover from a DB connection failure, re-creating a new one. Whoever is allocating memory (may be a method call, internal function, variable declaration, etc) that is overflowing PHP's memory limit will lead to a crash.

This happens to be (statistically) PDO because of the memory footprint of it, but that's not the root cause.

Closing as `invalid`, since this is an issue with how the error handling was written in your framework of choice.

**Closed by Ocramius** 2019-01-15 10:36 UTC
Labels: Bug, MariaDB, MySQL, PDO, pdo_mysql
