### ISSUE TITLE
Doctrine:Schema:Validate leeds to ORA-01427(single-row subquery returns more than one row)

### ISSUE THREAD

**Issue by Deamon** [doctrine/dbal#2584] opened 2016-12-22 16:44 UTC
Hi,
I have a problem on Oracle platform with the command doctrine:schema:validate with doctrine/dbal 2.5.5.

When I lauch the command I get the following error : 

```
  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: oci_fetch_all(): ORA-01427: single-row subquery returns more than
  one row
```

I recently upgraded from doctrine/dbal 2.5.4 to doctrine/dbal 2.5.5 and I finally managed to found where the regretion(?) comes from.

It apparently comes from the change of (new) line 668 of the file OraclePlatform.php on this commit : https://github.com/doctrine/dbal/commit/a23a47115f0fa35cf349735dfe342e2715f97f30

It not only change style of the query but transform an innerJoin to a subquery.
The innerJoin allowed several line as subquery doesn't.

This would work perfectly fine if no column have more than on comment.
In my Database, I have several users and each user have a comment on my column. 
And the subquery fail.

This can be corrected By adding an other condition on the subquery to get current user comments only.

I'm working on a PR to show the fix and iterate.

**Comment by deeky666** [comment] 2017-01-14 19:40
Duplicate of #2517

**Closed by deeky666** 2017-01-14 19:40 UTC
Labels: Bug, Columns, Duplicate, Oracle, Platforms, PR Created, Schema Introspection
