### ISSUE TITLE
Problem changing table when run tests using in memory sqlite after upgrade on v2.10.3.

### ISSUE THREAD

**Issue by DarkPrinceWW** [doctrine/dbal#4244] opened 2020-09-02 15:15 UTC
### Bug Report

Laravel migration broken after upgrade.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10.3

#### Summary

Laravel migration on sqlite

```
Schema::table('table_two', function (Blueprint $table) {
    $table->string('name')->change();
});
```

SQLSTATE[HY000]: General error: 1 no such index: IDX_E234CAE293411876 (SQL: DROP INDEX IDX_E234CAE293411876)

#### How to reproduce

```
Schema::create('table_one', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('name');
});

Schema::create('table_two', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('name');
    $table->unsignedInteger('reference_id');

    $table->foreign('reference_id')
        ->references('id')
        ->on('table_one')
        ->onDelete('cascade');
});

Schema::table('table_two', function (Blueprint $table) {
    $table->string('name')->change();
});
```

#### Source of the problem
https://github.com/doctrine/dbal/pull/3762
https://github.com/doctrine/dbal/pull/3762/commits/85a983c3f8d6447c4441832477def1c28d57bee9#diff-3fa09ba089913d40a1fbeb10b8cb8536R773

**Comment by mfn** [comment] 2020-09-02 18:09
Seems to be a duplicate of https://github.com/doctrine/dbal/issues/4243 , can you check?

**Comment by MyIgel** [comment] 2020-09-02 18:15
Its the same problem, yes

**Comment by greg0ire** [comment] 2020-09-02 18:17
Duplicates #4243

**Closed** 2020-09-02 18:18 UTC
