### ISSUE TITLE
Version 3.4 break listTableColumns for Views in MariaDB

### ISSUE THREAD

**Issue by wi-wissen** [doctrine/dbal#5690] opened 2022-09-24 11:54 UTC
### Bug Report

Version 3.4 break function [listTableColumns](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/schema-manager.html#listtablecolumns) for Views in MariaDB.

|    Q        |   A
|------------ | ------
| Version dbal     | 3.4.4
| Version MariaDB     | 10.4.24

#### Summary

If you query columns for a View (not a Table) in mariaDB you get an empty array.

#### Current behaviour

If you query columns for a View (not a Table) in mariaDB you get an empty array.

#### How to reproduce

Just create a View of a Table and run listTableColumns(). Is use dbal in a Laravel project.

#### Expected behaviour

Show colums like in version 3.3.8. A Downgrade fixed this Issue for me.

**Comment by morozov** [comment] 2022-09-24 14:34
This looks like a duplicate of https://github.com/doctrine/dbal/issues/5671.

**Comment by morozov** [comment] 2022-09-29 18:21
Closing similar to https://github.com/doctrine/dbal/issues/5671.

**Closed as not planned by morozov** 2022-09-29 18:21 UTC
Labels: Won't Fix, MySQL, Schema Introspection

**Comment by wi-wissen** [comment] 2022-09-29 19:43
Maybe it could at least be noted in the documentation that it doesn't work for views? For me this was very confusing. Especially because the function was removed in a minor release.

**Comment by morozov** [comment] 2022-09-29 19:52
Nothing in the `listTableColumns()` method name implies that it works with views. I don't believe this change warrants a documentation update.
