### ISSUE TITLE
ALTER TABLE adds COLLATION to changes on numeric columns

### ISSUE THREAD

**Issue by spaceemotion** [doctrine/dbal#3715] opened 2019-11-04 12:09 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10.0

#### Summary

The latest change in https://github.com/doctrine/dbal/pull/3668 by @staudenmeir seem to have broken my migrations in MySQL that don't update text columns.

#### Previous behaviour

```sql
ALTER TABLE user_details 
CHANGE vat_amount vat_amount NUMERIC(8, 2) DEFAULT '0' NOT NULL, 
CHANGE vat_included vat_included TINYINT (1) DEFAULT '0' NOT NULL
```

#### Current behavior

```sql
ALTER TABLE user_details 
CHANGE vat_amount vat_amount NUMERIC(8, 2) DEFAULT '0' NOT NULL, 
CHANGE vat_included vat_included TINYINT (1) CHARACTER SET utf8mb4 DEFAULT '0' NOT NULL COLLATE `utf8mb4_unicode_ci`
```

#### How to reproduce

In a Laravel 6 project:

```php
Schema::table('user_details', static function (Blueprint $table) {
    $table->decimal('vat_amount', 8, 2)->default(0)->change();
    $table->boolean('vat_included')->nullable(false)->default(false)->change();
});
```

**Comment by Ocramius** [comment] 2019-11-04 12:18
duplicate of #3714

**Comment by spaceemotion** [comment] 2019-11-04 12:19
Dang, I had this open half an hour ago, went to lunch and submitted when I came back haha.

**Comment by williamdes** [comment] 2019-11-04 12:22
Haha submitted before lunch :p

**Comment by Ocramius** [comment] 2019-11-04 12:45
s'alright - closing here meanwhile.

**Closed by Ocramius** 2019-11-04 12:45 UTC
Labels: Bug, Columns, Duplicate, MySQL, Schema, Schema Definition, Schema Introspection, Schema Managers
