### ISSUE TITLE
Unknown column type "jsonArray" requested

### ISSUE THREAD

**Issue by irvatoDev** [doctrine/dbal#3272] opened 2018-08-28 07:51 UTC
### Bug Report

i added entity with several fields
when run a build table in apps, show error

```json
    "doctrine/dbal": "2.*",
```

``` shell
Fault to rebuild database schema. Details: Unknown column type "jsonArray" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information. [] []
````

**Comment by Ocramius** [comment] 2018-08-28 11:41
Closing: not a bug, please read the error message again.

**Closed by Ocramius** 2018-08-28 11:41 UTC
