### ISSUE TITLE
ensureForwardCompatibilityStatement expects ResultStatement, given PDOStatement

### ISSUE THREAD

**Issue by mwoods-familiaris** [doctrine/dbal#4603] opened 2021-04-14 13:25 UTC
### Bug Report

TypeError: Argument 1 passed to Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement() must be an instance of Doctrine\DBAL\Driver\ResultStatement, instance of PDOStatement given, called in ./vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1313

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.13.0

#### Summary

executeQuery in Connection.php obtains the statement via:
```
$stmt = $connection->prepare($sql);
```
[link](https://github.com/doctrine/dbal/blob/67d56d3203b33db29834e6b2fcdbfdc50535d796/lib/Doctrine/DBAL/Connection.php#L1288)

which is used in a forward compatibility check, added in this release:
```
return $this->ensureForwardCompatibilityStatement($stmt);
```
[link](https://github.com/doctrine/dbal/blob/67d56d3203b33db29834e6b2fcdbfdc50535d796/lib/Doctrine/DBAL/Connection.php#L1313)

However, ensureForwardCompatibilityStatement expects $stmt to be an instance of ResultStatement, however in the case of a PDO connection, a PDOStatement is returned instead, hence the type error.
```
    /**
     * @param string          $sql
     * @param array<int, int> $driverOptions
     *
     * @return PDOStatement
     */
    public function prepare($sql, $driverOptions = [])
    {
        try {
            $statement = parent::prepare($sql, $driverOptions);
            assert($statement instanceof PDOStatement);

            return $statement;
        } catch (PDOException $exception) {
            throw Exception::new($exception);
        }
    }
```
[link](https://github.com/doctrine/dbal/blob/67d56d3203b33db29834e6b2fcdbfdc50535d796/lib/Doctrine/DBAL/Driver/PDOConnection.php#L76)

#### How to reproduce

Execute a parameterized query using a PDO connection.

#### Expected behaviour

ensureForwardCompatibilityStatement parameter type should cater to all possible statement types.

**Comment by glensc** [comment] 2021-04-14 14:35
I have a similar error when using [debugbar](https://github.com/maximebf/php-debugbar):

```
Argument 1 passed to Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement() must implement interface Doctrine\DBAL\Driver\ResultStatement, instance of DebugBar\DataCollector\PDO\TraceablePDOStatement given, called in /Users/glen/scm/eventum/eventum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1315
```

```
#0 /Users/glen/scm/eventum/eventum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1315): Doctrine\DBAL\Connection->ensureForwardCompatibilityStatement(Object(DebugBar\DataCollector\PDO\TraceablePDOStatement))
#1 /Users/glen/scm/eventum/eventum/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(726): Doctrine\DBAL\Connection->executeQuery('SELECT t0.upr_u...', Array, Array)
#2 /Users/glen/scm/eventum/eventum/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(744): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL)
#3 /Users/glen/scm/eventum/eventum/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(472): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadById(Array)
#4 /Users/glen/scm/eventum/eventum/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(151): Doctrine\ORM\EntityManager->find('Eventum\\Model\\E...', Array, NULL, NULL)
#5 /Users/glen/scm/eventum/eventum/src/Model/Repository/UserPreferenceRepository.php(29): Doctrine\ORM\EntityRepository->find(2)
```

Integrated in two places:
- https://github.com/eventum/eventum/blob/6c2db74117b60be8b2daf6a5a921ab232a36f1e0/src/DebugBarManager.php#L113-L128
- https://github.com/eventum/eventum/blob/6c2db74117b60be8b2daf6a5a921ab232a36f1e0/src/DebugBarManager.php#L73-L96

**Comment by gezilixu** [comment] 2021-04-16 14:14
I have the same error when i run php artisan migrate:generate  error info:  Argument 1 passed to Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement() must be an instance of Doctrin
  e\DBAL\Driver\ResultStatement, instance of PDOStatement given, called in myproject\ven
  dor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php on line 1313, anyone konw How to solve it?

**Comment by glensc** [comment] 2021-04-16 14:38
@gezilixu: 2.13.x is broken in certain setups (to be identified yet which), until then a workaround is to downgrade:

```
composer require doctrine/dbal:2.12.x
```

**Comment by gezilixu** [comment] 2021-04-16 14:49
> @gezilixu: 2.13.x is broken in certain setups (to be identified yet which), until then a workaround is to downgrade:
> 
> ```
> composer require doctrine/dbal:2.12.x
> ```

Wow, it worked out @glensc Thank you very much.

**Comment by mdumoulin** [comment] 2021-04-16 16:16
@mwoods-familiaris If I'm right, you are talking of this issue : #4564. If I'm wrong, can you provide a code sample to reproduce please.

**Comment by glensc** [comment] 2021-04-16 17:05
Yeah, and fix seems to be in https://github.com/doctrine/dbal/pull/4590

**Comment by mwoods-familiaris** [comment] 2021-04-16 17:09
> @mwoods-familiaris If I'm right, you are talking of this issue : #4564. If I'm wrong, can you provide a code sample to reproduce please.

Agreed - not sure how I didn't spot that when I searched, but does appear to be the same bug.

**Comment by mdumoulin** [comment] 2021-04-16 17:36
@glensc I'm affraid that the fix here will not fully answer your expectations. If the user has already wrapped the \PDOStatement, it will be overidden in the DriverManager.
In your case, methods of class https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/DataCollector/PDO/TraceablePDOStatement.php will never be called.

```php
<?php
require_once('vendor/autoload.php');

class MyPDOStatement extends \PDOStatement
{
    public function execute($input_parameters = null)
    {
        var_dump('Hello there');

        return parent::execute($input_parameters);
    }
}

$pdo = new PDO('sqlite::memory:');
$pdo->setAttribute(\PDO::ATTR_STATEMENT_CLASS, [MyPDOStatement::class, []]);

$conn = Doctrine\DBAL\DriverManager::getConnection(['pdo' => $pdo, 'driver' => 'pdo_sqlite']);
$result = $conn->executeQuery('SELECT 1;');
var_dump($result->fetchFirstColumn());
```

**Comment by beberlei** [comment] 2021-04-17 16:31
@mdumoulin outside of this edge case with a custom statement class, the original issue reported here was fixed by your PR #4591 or not?

**Comment by mdumoulin** [comment] 2021-04-18 08:41
@beberlei Yes it is fixed by #4590

**Closed as completed** 2021-04-19 16:30 UTC

**Comment by oojacoboo** [comment] 2021-07-21 05:18
@mdumoulin I'm still a bit confused on all of this.  2.13 has broken our implementation and is a bit of a circular dependency for us as well.  I'm getting the following error:

>Argument 1 passed to Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement() must be an instance of Doctrine\DBAL\Driver\ResultStatement, instance of PDOStatement given

Does `Doctrine\DBAL\Connection` support `\PDO` directly?  The constructor doesn't do any validation.  We have to share a PDO connection with 2 different ORMs.  What's the proper way of handling this now?  I can't seem to find any documentation on it.  We currently have something along these lines:

```php
$pdoConnection = PDOConnection::getInstance(); // Instance of \PDO

$dbalParams = [
    'pdo' => $pdoConnection,
];

$dbalConfig = new Configuration();

// We don't want to add any overhead on production and won't be doing any query debugging
if (!$env->isProduction()) {
    $dbalConfig->setSQLLogger(new DebugStack());
}

$connection = new DoctrineConnection($dbalParams, new MySQLDriver(), $dbalConfig); // Extended instance of Doctrine\DBAL\Connection
```

**Comment by mdumoulin** [comment] 2021-07-21 10:09
@oojacoboo You can use a PDOConnection, but the result of query execution must return a DBAL\Driver\Statement object instead of a \PDOStatement object to be compatible with DBAL.

This comment give a way of doing it : https://github.com/doctrine/dbal/issues/4619#issuecomment-827900550

**Comment by oojacoboo** [comment] 2021-07-22 02:06
@mdumoulin I'm not using `\Doctrine\DBAL\Driver\PDOConnection` though.  I tried to make that clear with the comments.  `$pdoConnection instanceof \PDO`.  I think you're saying you must pass a `\Doctrine\DBAL\Driver\PDOConnection` object to the `Doctrine\DBAL\Connection` constructor?

**Comment by mdumoulin** [comment] 2021-07-22 08:14
@oojacoboo Yes, I think, I understood. You have to make your PDO connection return a Dbal statement instead of PDOStatement when executing a query.

I haven't the full context here, but this may work for you :
```php
<?php

use \Doctrine\DBAL\Driver\PDO\Statement as PDODriverStatement;

$pdoConnection = PDOConnection::getInstance(); // Instance of \PDO
$pdoConnection->setAttribute(PDO::ATTR_STATEMENT_CLASS, [PDODriverStatement::class, []]);

$dbalParams = [
    'pdo' => $pdoConnection,
];

$dbalConfig = new Configuration();

// We don't want to add any overhead on production and won't be doing any query debugging
if (!$env->isProduction()) {
    $dbalConfig->setSQLLogger(new DebugStack());
}

$connection = new DoctrineConnection($dbalParams, new MySQLDriver(), $dbalConfig); // Extended instance of Doctrine\DBAL\Connection
```

**Comment by oojacoboo** [comment] 2021-07-27 04:18
@mdumoulin this results in the following error:

> SQLSTATE[HY000]: General error: user-supplied statement class must be derived from PDOStatement

It might be helpful to have some boilerplate code or docs on how to use a `\PDO` connection with DBAL.  Or maybe I missed that somewhere?

**Comment by mdumoulin** [comment] 2021-07-27 08:21
@oojacoboo 

> @mdumoulin this results in the following error:
> 
> > SQLSTATE[HY000]: General error: user-supplied statement class must be derived from PDOStatement

The PDODriverStatement in my example is derived of \PDOStatement : https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/Driver/PDO/Statement.php#L7

> It might be helpful to have some boilerplate code or docs on how to use a `\PDO` connection with DBAL. Or maybe I missed that somewhere?

I can't find it either, but this feature has been removed from version 3.0. You may find some useful informations here : https://github.com/doctrine/dbal/issues/3545

**Comment by jephdev** [comment] 2021-09-06 11:06
> @gezilixu: 2.13.x is broken in certain setups (to be identified yet which), until then a workaround is to downgrade:
> 
> ```
> composer require doctrine/dbal:2.12.x
> ```

I am using doctrine/dbal:2.10.2 but having the same issue when trying to run migration. How can I fix this please?
