### ISSUE TITLE
Unable to execute orm:generate-proxies

### ISSUE THREAD

**Issue by Alvaro948** [doctrine/dbal#6512] opened 2024-08-29 11:28 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 4.1.0

#### Summary

Since the update to version 4.1.0 the command for generating proxies fails

#### Current behaviour

By executing:

```sh
./bin/doctrine orm:generate-proxies ./var/doctrine/proxies
```

Produces:

```
#41 [prod 18/19] RUN ./bin/doctrine orm:generate-proxies ./var/doctrine/proxies
#41 0.161 PHP Fatal error:  Uncaught TypeError: PDO::__construct(): Argument #2 ($username) must be of type ?string, false given in /www/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:33
#41 0.161 Stack trace:
#41 0.161 #0 /www/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php(33): PDO->__construct()
#41 0.161 #1 /www/vendor/doctrine/dbal/src/Connection.php(217): Doctrine\DBAL\Driver\PDO\PgSQL\Driver->connect()
#41 0.161 #2 /www/vendor/doctrine/dbal/src/Connection.php(236): Doctrine\DBAL\Connection->connect()
#41 0.161 #3 /www/vendor/doctrine/dbal/src/Driver/AbstractPostgreSQLDriver.php(26): Doctrine\DBAL\Connection->getServerVersion()
#41 0.161 #4 /www/vendor/doctrine/dbal/src/Connection.php(191): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->getDatabasePlatform()
#41 0.161 #5 /www/vendor/doctrine/orm/src/Mapping/ClassMetadataFactory.php(724): Doctrine\DBAL\Connection->getDatabasePlatform()
#41 0.161 #6 /www/vendor/doctrine/orm/src/Mapping/ClassMetadataFactory.php(546): Doctrine\ORM\Mapping\ClassMetadataFactory->getTargetPlatform()
#41 0.161 #7 /www/vendor/doctrine/orm/src/Mapping/ClassMetadataFactory.php(174): Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping()
#41 0.161 #8 /www/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(343): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata()
#41 0.161 #9 /www/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(207): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata()
#41 0.161 #10 /www/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(96): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor()
#41 0.161 #11 /www/vendor/doctrine/orm/src/Tools/Console/Command/GenerateProxiesCommand.php(46): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata()
#41 0.161 #12 /www/vendor/symfony/console/Command/Command.php(279): Doctrine\ORM\Tools\Console\Command\GenerateProxiesCommand->execute()
#41 0.161 #13 /www/vendor/symfony/console/Application.php(1029): Symfony\Component\Console\Command\Command->run()
#41 0.161 #14 /www/vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#41 0.161 #15 /www/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#41 0.161 #16 /www/vendor/doctrine/orm/src/Tools/Console/ConsoleRunner.php(30): Symfony\Component\Console\Application->run()
#41 0.161 #17 /www/bin/doctrine(62): Doctrine\ORM\Tools\Console\ConsoleRunner::run()
#41 0.161 #18 {main}
#41 0.161   thrown in /www/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php on line 33
#41 ERROR: process "/bin/sh -c ./bin/doctrine orm:generate-proxies ./var/doctrine/proxies" did not complete successfully: exit code: 255
```

#### How to reproduce

Execute the provided command with `doctrine/dbal@4.1.0`

#### Expected behaviour

The same as before, by setting the version back to `4.0.4` the issue is gone:

```
#41 [prod 18/19] RUN ./bin/doctrine orm:generate-proxies ./var/doctrine/proxies
#41 0.242  Processing entity "App\Domain\Entity\File\FileEntity"
...
#41 0.302 
#41 0.303  Proxy classes generated to "/www/var/doctrine/proxies"
#41 DONE 0.3s
```

**Comment by derrabus** [comment] 2024-08-29 22:12
Please provide steps to reproduce the issue.

**Comment by Alvaro948** [comment] 2024-08-30 05:39
Hi @derrabus, sure, I have created a repo in order to reproduce the error https://github.com/Alvaro948/doctrine-starter, on main branch will find `doctrine/dbal@4.0.4`, simply install do `composer install` and if you execute:

```sh
./bin/doctrine orm:generate-proxies ./var/doctrine/proxies
```

It will work, however, if you switch to branch "updated", re-execute `composer install` (now you have `doctrine/dbal@4.1.0`) the command fails.

**Comment by derrabus** [comment] 2024-08-30 08:33
You're reading the credentials with `getenv()`.

https://github.com/Alvaro948/doctrine-starter/blob/d9efbbd6a0333fe7fc6b30be2ffd7ada28357293/bin/doctrine#L35-L43

If all environment variables are set, the command works fine.

<img width="694" alt="Bildschirmfoto 2024-08-30 um 10 28 14" src="https://github.com/user-attachments/assets/f8e7c605-079c-49e6-b5a1-31c5ae5509c3">

However, if they're not, `getenv()` returns `false` which is not a valid value for the `user` setting as per our documentation. Either omit the user or set it to `null`.

We can change the PDO driver and make it throw if the provided `user` or `password` are neither a string nor `null`. This will give you a nicer error message, but in the end it remains a configuration issue on your side.

**Comment by derrabus** [comment] 2024-08-30 09:51
I've created #6513 to make the configuration error more explicit.

**Comment by Alvaro948** [comment] 2024-08-30 09:58
Hi @derrabus thanks for your answer,

Yes, by setting the env variables it "fixes" the issue, but note that version 4.0.4 did not have this requirement, and most importantly why it this needed in the first place?, I mean, the command is about generating doctrine proxies using the source code, a database connection should not be needed (In my particular use case I execute this command on a CI).

However, I have tried what you suggest without luck, for example, by setting the user & password to `null`:

```php
$connection = DriverManager::getConnection([
    'driver' => 'pdo_pgsql',
    'user' => null,
    'password' => null,
    'host' => null,
    'port' => null,
    'dbname' => null,
    'charset' => 'UTF8',
], $config);
```

This, and other combiantions, still fails on version `4.1.0` but works fine on `4.0.4`

![image](https://github.com/user-attachments/assets/847443de-d16c-498d-b1ee-880a701cd866)

Maybe I have missundertood your answer, as far as I can tell the problem here seems to be that version `4.1.0` is trying to establish a connection with the database even though is not needed, resulting in the type errors your are refeering or in the connection error of the screenshot

**Comment by derrabus** [comment] 2024-08-30 10:21
> why it this needed in the first place?, I mean, the command is about generating doctrine proxies using the source code, a database connection should not be needed (In my particular use case I execute this command on a CI).

This is something we cannot fix it in the DBAL. Long story short: Connections are lazy in DBAL. You can create a connection with invalid parameters and it's fine until you perform any operation that requires an _active_ connection. When loading the class metadata, which the ORM needs to build the proxies, the ORM fetches the database platform object. In order to create that object, we need to know what DBMS we connect to and usually also to which version of that DBMS. So the DBAL establishes a connection in order to detect the server version.

Of course, we could question why fetching the class metadata depends on the database platform, but again: That's an ORM issue and out of scope for this repository.

> note that version 4.0.4 did not have this requirement

Yeah, funny story. Well, in DBAL 4.0, we dropped support for Postgres versions before 10. Because of that, we were in the unique situation that we only had a single platform class for all Postgres versions. Since the server version was irrelevant, we could pick the platform class soley based on the driver, so no connection was established.

In 4.1, a new platform class for Postgres 12 and above was added, so we again need to know the server version when detecting the platform.

However, there is a way to short-circuit the platform detection. If you add `'serverVersion' => '16.4',` to your config array, the error is gone. Of course, you should replace `16.4` with the actual version of your postgres server.

**Comment by derrabus** [comment] 2024-08-30 10:32
See doctrine/DoctrineBundle#351 for a similar discussion.

**Comment by derrabus** [comment] 2024-08-30 10:32
I'm closing the issue now because there's nothing we can do in DBAL to solve it.

**Closed as not planned by derrabus** 2024-08-30 10:32 UTC
Labels: Invalid, pdo_pgsql, Question, Connecting, PDO

**Comment by Alvaro948** [comment] 2024-08-30 10:57
Hi @derrabus,

Yes, I have tried by simply adding `serverVersion` and it indeed worked (good enought for me):

```diff
$connection = DriverManager::getConnection([
    'driver' => 'pdo_pgsql',
    'user' => getenv('DATABASE_USERNAME'),
    'password' => getenv('DATABASE_PASSWORD'),
    'host' => getenv('DATABASE_HOST'),
    'port' => getenv('DATABASE_PORT'),
    'dbname' => getenv('DATABASE_DATABASE'),
    'charset' => 'UTF8',
+   'serverVersion' => '16.4',
], $config);
```

Also, by simply setting other driver than `pdo_pgsql` to `pdo_sqlite` it fixes the issue as well, and all the generated files _seem_ to be exactly the same, but maybe in the future it will change.

Again, thank you so much for your help!
