### ISSUE TITLE
Malformed SQL generated for MySQL when changing column type.

### ISSUE THREAD

**Issue by acelaya** [doctrine/dbal#3813] opened 2020-01-05 20:31 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.2.0

#### Summary

I have a table called `visit_locations` on a MySQL 5.7 database, with a `latitude` column I want to change from `STRING` to `FLOAT`.

When the migration is run, I always get this error:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET utf8 DEFAULT NULL COLLATE utf8_unicode_ci` at line 1
```

#### Current behavior

The error is thrown.

#### How to reproduce

I have reproduced it on MySQL 5.7, with a migration like this one:

```php
<?php

declare(strict_types=1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Types\Type;
use Doctrine\DBAL\Types\Types;
use Doctrine\Migrations\AbstractMigration;

final class Version20200105165647 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $visitLocations = $schema->getTable('visit_locations');
        $visitLocations->getColumn('latitude')->setType(Type::getType(Types::FLOAT));
    }

    public function down(Schema $schema): void
    {
        $visitLocations = $schema->getTable('visit_locations');
        $visitLocations->getColumn('latitude')->setType(Type::getType(Types::STRING));
    }
}
```

I have also seen that the SQL generated is this:

```SQL
ALTER TABLE visit_locations CHANGE latitude latitude DOUBLE PRECISION CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`
```

If instead I remove the `CHARACTER SET utf8` part, then the instruction works, changing the column type as expected.

Maybe this part is not getting placed in the proper position?

#### Expected behavior

The migration is executed without throwing an error.

**Comment by acelaya** [comment] 2020-01-05 23:09
Before running the migration, it was `utf8`

**Comment by TomHAnderson** [comment] 2020-01-06 00:31
`CHARACTER SET utf8 DEFAULT NULL COLLATE utf8_unicode_ci`

I think you should not include default null after the character set.

**Comment by acelaya** [comment] 2020-01-06 07:08
Yes, that's also my guess, but I'm not the one including it. Doctrine is generating that query based on the migration I provided in the issue.

**Comment by gms8994** [comment] 2020-02-03 19:36
I'm experiencing this issue as well in 2.10.1 - 2.9.3 did not experience this issue.

**Comment by taira-terashima-realpit** [comment] 2020-02-04 05:44
Hi, I'm experiencing too this issue.
My environment are

doctrine/dbal:2.10.0
MySQL: 5.6

but not occured this problem in doctrine 2.9.3

Print source here.

```class UpdateColumnCharTypeHogeTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('hoge', function (Blueprint $table) {
            $table->smallInteger('char_type')->unsigned()->nullable()->change();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('hoge', function (Blueprint $table) {
            $table->string('char_type', 5)->nullable()->change();
        });
    }
}

```

**Comment by gms8994** [comment] 2020-02-04 19:48
It looks like the issue came from https://github.com/doctrine/dbal/commit/73f38e722421fed5f00ff3fba76c80cf1a7545b4#diff-f8e1d5c54371540dc546d17c426c36e6 - commenting out the `$column->setPlatformOption('charset', $tableColumn['characterset']);` seems to work correctly.

**Comment by taira-terashima-realpit** [comment] 2020-02-05 00:53
Thx, it's exactly correct.
I update it.

**Comment by roy-bongers** [comment] 2020-02-28 11:28
We experience the same problem using MySQL 5.7 and doctrine/dbal v2.10.1

```php
Schema::table('some_table_name', function (Blueprint $table) {
    $table->unsignedSmallInteger('some_column_name')->change()->default(100);
});
```

```
Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET utf8
DEFAULT 100 COLLATE `utf8_unicode_ci`' at line 1 (SQL: ALTER TABLE some_table_name CHANGE
some_column_name some_column_name SMALLINT UNSIGNED CHARACTER SET utf8 DEFAULT 100
COLLATE `utf8_unicode_ci`)
```

**Comment by morozov** [comment] 2021-12-12 22:49
Closing as a duplicate of https://github.com/doctrine/dbal/issues/3714.

**Closed by morozov** 2021-12-12 22:49 UTC
Labels: Won't Fix, Schema Management
