### ISSUE TITLE
Unicode problem

### ISSUE THREAD

**Issue by logbie** [doctrine/dbal#2828] opened 2017-08-31 23:55 UTC
Doctrine does not seem to detect (\xc2\xbd)(½).

This is the data: _1212½ W. Alameda Ave._

This is what doctrine spits out: _\x31\x32\x31\x32\xbd\x20\x57\x2e\x20\x41\x6c\x61\x6d\x65\x64\x61\x20\x41\x76\x65\x2e_

Which looks like : 1212ݠW. Alameda Ave.

This is what it should spit out.
_\x31\x32\x31\x32\xc2\xbd\x20\x57\x2e\x20\x41\x6c\x61\x6d\x65\x64\x61\x20\x41\x76\x65\x2e_

I'm not sure how to fix this.

some notes on the setup i'm running
OS: Ubuntu 16.04.3
Mysql: 5.7.19-0ubuntu0.16.04.1-log - (Ubuntu)
php: 7.1.8

Doctrine info:
doctrine/dbal: "v2.5.3",
doctrine/common: "v2.5.3"
doctrine/cache: "1.6",

**Comment by morozov** [comment] 2017-09-01 01:55
@logbie could you provide a code example to reproduce this?

**Comment by logbie** [comment] 2017-09-01 02:34
sure.

```
$connectionParams = [
			'dbname' 	=> $cfg["DBase"],
			'user' 		=> $cfg["User"],
			'password' 	=> $cfg["Pass"],
			'host' 		=> $cfg["server"],
			'driver' 	=> $cfg["Driver"],
            'charset'   => $cfg["charset"],
            'driverOptions'   => array('1002'=> "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_bin'")
	];
	


	$config = new \Doctrine\DBAL\Configuration ();
	$conn = \Doctrine\DBAL\DriverManager::getConnection ( $connectionParams, $config );

	$queryBuilder = $conn->createQueryBuilder ();
	$queryBuilder->insert ( 'EN' )
		->values ( array (
			"HMPLX_ID" 					=> "?",
			"RECORD_TYPE" 				=> "?",
			"UNIQUE_SYSTEM_IDENTIFIER" 	=> "?",
			"ULS_FILE_NUMBERS" 			=> "?",
			"EBF_NUMBER" 				=> "?",
			"CALL_SIGN" 				=> "?",
			"ENTITY_TYPE" 				=> "?",
			"LICENSEE_ID" 				=> "?",
			"ENTITY_NAME" 				=> "?",
			"FIRST_NAME" 				=> "?",
			"MI" 						=> "?",
			"LAST_NAME" 				=> "?",
			"SUFFIX" 					=> "?",
			"PHONE" 					=> "?",
			"FAX" 						=> "?",
			"EMAIL" 					=> "?",
			"STREET_ADDRESS" 			=> "?",
			"CITY" 						=> "?",
			"STATE" 					=> "?",
			"ZIP_CODE" 					=> "?",
			"PO_BOX" 					=> "?",
			"ATTENTION_LINE" 			=> "?",
			"SGIN" 						=> "?",
			"FCC_REGISTRATION_NUMBER"   => "?",
			"APPLICANT_TYPE_CODE" 		=> "?",
			"APPLICANT_TYPE_CODE_OTHER" => "?",
			"STATUS_CODE" 				=> "?",
			"STATUS_DATE" 				=> "?"
		) )

	;
	
	$sql = $queryBuilder->getSQL ();
	


	#echo "<br><br>";

	#echo "<b>Unprepared: </b>" . $sql;

	#echo "<br><br>";


	
	// $queryBuilder = $conn->query($sql);

	$stmt = $conn->prepare($sql);

	$stmt->bindValue(1, "0");
	$stmt->bindValue(2, $csia["1"]);
	$stmt->bindValue(3, $csia["2"]);
	$stmt->bindValue(4, $csia["3"]);
	$stmt->bindValue(5, $csia["4"]);
	$stmt->bindValue(6, $csia["5"]);
	$stmt->bindValue(7, $csia["6"]);
	$stmt->bindValue(8, $csia["7"]);
	$stmt->bindValue(9, $csia["8"]);
	$stmt->bindValue(10, $csia["9"]);
	$stmt->bindValue(11, $csia["10"]);
	$stmt->bindValue(12, $csia["11"]);
	$stmt->bindValue(13, $csia["12"]);
	$stmt->bindValue(14, $csia["13"]);
	$stmt->bindValue(15, $csia["14"]);
	$stmt->bindValue(16, $csia["15"]);
	$stmt->bindValue(17, $csia["16"]);
	$stmt->bindValue(18, $csia["17"]);
	$stmt->bindValue(19, $csia["18"]);
	$stmt->bindValue(20, $csia["19"]);
	$stmt->bindValue(21, $csia["20"]);
	$stmt->bindValue(22, $csia["21"]);
	$stmt->bindValue(23, $csia["22"]);
	$stmt->bindValue(24, $csia["23"]);
	$stmt->bindValue(25, $csia["24"]);
	$stmt->bindValue(26, $csia["25"]);
	$stmt->bindValue(27, $csia["26"]);
	$stmt->bindValue(28, $csia["27"]);



	#echo "<br> Prepared: " . $stmt;

	$stmt->execute();
	$conn->close();
```

and the cfg array reads 
```
$cfg["DOCUMENT_ROOT"] = $_SERVER["DOCUMENT_ROOT"];
$cfg["server"]    	  = "localhost";
$cfg["User"]      	  = [Redacted]
$cfg["Pass"]      	  = [Redacted]
$cfg["DBase"]     	  = [Redacted]
$cfg["Driver"]    	  = "pdo_mysql";
$cfg["Directory"]     = "./data";
$cfg["REQUEST_URI"]   = $_SERVER["REQUEST_URI"];
$cfg["charset"]       = "utf8mb4";
```

The field in question is "street address" 

the sql field

``STREET_ADDRESS`` `varchar(200) COLLATE utf8mb4_bin NOT NULL,`

**Comment by morozov** [comment] 2017-09-02 03:42
@logbie here's the script I used to test your case:
```php
$conn = \Doctrine\DBAL\DriverManager::getConnection([
    'dbname' => 'doctrine',
    'user' => 'doctrine',
    'password' => 'Passw0rd',
    'host' => 'localhost',
    'driver' => 'pdo_mysql',
    'charset' => 'utf8mb4',
    'driverOptions' => [
        PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_bin'",
    ],
]);

$conn->executeQuery('DROP TABLE IF EXISTS test');
$conn->executeQuery('CREATE TABLE test (STREET_ADDRESS varchar(200) COLLATE utf8mb4_bin NOT NULL)');

$builder = $conn->createQueryBuilder ();
$builder->insert('test')
    ->values([
        'STREET_ADDRESS' => '?',
    ]);

$sql = $builder->getSQL();
$stmt = $conn->prepare($sql);
$stmt->bindValue(1, '1212½ W. Alameda Ave.');
$stmt->execute();

$address = $conn->executeQuery('SELECT * FROM test')
    ->fetchColumn();

var_dump($address);

// string(22) "1212½ W. Alameda Ave."
```
It worked fine for me, and the value in the DB also looked correctly:
```
mysql> select * from test;
+------------------------+
| STREET_ADDRESS         |
+------------------------+
| 1212½ W. Alameda Ave.  |
+------------------------+
1 row in set (0.00 sec)
```

Could you try using my script in your environment and see if the issue is still reproducible?

**Comment by morozov** [comment] 2018-10-03 07:07
No feedback for a year. Closing.

**Closed by morozov** 2018-10-03 07:07 UTC
Labels: Bug, Character Encoding, Missing Tests, MySQL, Prepared Statements
