### ISSUE TITLE
The mapping matrix in the "types" docs is broken

### ISSUE THREAD

**Issue by apfelbox** [doctrine/dbal#4143] opened 2020-07-03 13:19 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | n/a

#### Summary

The rendering of the mapping matrix table is broken in the official docs:

https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/types.html#mapping-matrix

#### Current behaviour

![2020-07-03 at 15 17](https://user-images.githubusercontent.com/1032411/86472953-4a47d680-bd40-11ea-97f8-9591b5821841.png)

#### How to reproduce

Just visit the link above

#### Expected behaviour

It should rather look like a real table, like the one in the Github rendering:
https://github.com/doctrine/dbal/blob/2.10.x/docs/en/reference/types.rst#mapping-matrix

![2020-07-03 at 15 18](https://user-images.githubusercontent.com/1032411/86473047-7c593880-bd40-11ea-82d2-fb53aaf53a11.png)

----

I thought there was an issue about that already, but I couldn't find it. If this is a duplicate, sorry for the noise and please close. 😊

**Comment by SenseException** [comment] 2020-07-05 13:03
Yes, this is a duplicate of #3338. I'll close this issue in favour of the original one.

**Closed by SenseException** 2020-07-05 13:03 UTC
