### ISSUE TITLE
Expression builder considering only first element in array binding parameter

### ISSUE THREAD

**Issue by ricardofiorani** [doctrine/dbal#3433] opened 2019-01-21 13:16 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | idk
| Version     | v2.9.2
| DB used | MariaDB (v10.3.11)
| PHP version | 7.3.0

#### Summary

When using the `expr()->in()` with a binding value, it only considers the first item in the parameter array on the query. It should consider all values from the array.

#### Current behaviour

Only the first value of an parameter array is considered on the `IN` statement.

#### How to reproduce
My setup is PHP 7.3 with MariaDB (10.3.11) using PDO.

The following example will consider only the first array element (bug):
```php
<?php
$q = $this->connection->createQueryBuilder();
$q->select('test_id');
$q->from('test_table');
$q->where(
    $q->expr()->in('test_table.test_id', ':id_list')
);

$q->setParameter('id_list', [123, 456], Type::SIMPLE_ARRAY);

//This will return missing records by considering only "123" and ignoring "456"
$results = $q->execute()->fetchAll(); 
```

The following example will work as expected:
```php
<?php
$q = $this->connection->createQueryBuilder();
$q->select('test_id');
$q->from('test_table');
$q->where(
    $q->expr()->in('test_table.test_id', [123, 456])
);

//This will return the right amount of records by considering both "123" and "456"
$results = $q->execute()->fetchAll(); 
```

#### Expected behaviour

It should consider all values from the binding parameter array.

**Comment by Ocramius** [comment] 2019-01-23 06:50
@ricardofiorani what's the executed SQL looking like, and what are the bound parameters at SQL level?

**Comment by morozov** [comment] 2019-01-23 07:53
@ricardofiorani it should probably be `Connection::PARAM_INT_ARRAY` instead of `Type::SIMPLE_ARRAY` in your code.

**Comment by Ocramius** [comment] 2019-01-23 07:53
Yeah, but `Type::SIMPLE_ARRAY` should serialize the value to a `string` bound to a single argument, as far as I know

**Comment by ricardofiorani** [comment] 2019-01-23 09:23
@morozov it worked as expected with `Connection::PARAM_INT_ARRAY`

**Comment by Ocramius** [comment] 2019-01-23 09:32
The question still stands though: what's going on with `Type::SIMPLE_ARRAY`? We should still look into it.

**Comment by ricardofiorani** [comment] 2019-01-23 09:38
@Ocramius sure, at this exactly moment I'm writing a proof of ~concept~ bug to which I'll post the gist here soon.

**Comment by ricardofiorani** [comment] 2019-01-23 10:01
After some tests with sqlite, the `\Doctrine\DBAL\Types\Type::SIMPLE_ARRAY` doesn't work at all, bringing no record, please see the test that I did below. 

```php
<?php declare(strict_types=1);

require 'vendor/autoload.php';

$config = new \Doctrine\DBAL\Configuration();
$connectionParams = [
    'url' => 'sqlite:/:memory:',
];

$connection = \Doctrine\DBAL\DriverManager::getConnection($connectionParams, $config);

$connection->exec(<<<SQL
CREATE TABLE test_table (
  test_id Int
);

INSERT INTO test_table VALUES (123), (456)
SQL
);

//Fetching using \Doctrine\DBAL\Connection::PARAM_INT_ARRAY
echo PHP_EOL;
//-----------
$q = $connection->createQueryBuilder();
$q->select('*');
$q->from('test_table');
$q->where(
    $q->expr()->in('test_table.test_id', ':id_list')
);

$q->setParameter('id_list', [123, 456], \Doctrine\DBAL\Connection::PARAM_INT_ARRAY);

var_dump([
    'using' => '\Doctrine\DBAL\Connection::PARAM_INT_ARRAY',
    'sql' => $q->getSQL(),
    'count' => count($q->execute()->fetchAll()),
]);

//Fetching using \Doctrine\DBAL\Types\Type::SIMPLE_ARRAY
echo PHP_EOL;
//-----------
$q = $connection->createQueryBuilder();
$q->select('*');
$q->from('test_table');
$q->where(
    $q->expr()->in('test_table.test_id', ':id_list')
);

$q->setParameter('id_list', [123, 456], \Doctrine\DBAL\Types\Type::SIMPLE_ARRAY);

var_dump([
    'using' => '\Doctrine\DBAL\Types\Type::SIMPLE_ARRAY',
    'sql' => $q->getSQL(),
    'count' => count($q->execute()->fetchAll()),
]);

//Fetching attaching the parameters directly in the expr()->in()
echo PHP_EOL;
//-----------
$q = $connection->createQueryBuilder();
$q->select('*');
$q->from('test_table');
$q->where(
    $q->expr()->in('test_table.test_id', [123, 456])
);

var_dump([
    'using' => ' the parameters directly in the expr()->in() without binding',
    'sql' => $q->getSQL(),
    'count' => count($q->execute()->fetchAll()),
]);
```

Output: 
```
array(3) {
  ["using"]=>
  string(42) "\Doctrine\DBAL\Connection::PARAM_INT_ARRAY"
  ["sql"]=>
  string(63) "SELECT * FROM test_table WHERE test_table.test_id IN (:id_list)"
  ["count"]=>
  int(2)
}

array(3) {
  ["using"]=>
  string(39) "\Doctrine\DBAL\Types\Type::SIMPLE_ARRAY"
  ["sql"]=>
  string(63) "SELECT * FROM test_table WHERE test_table.test_id IN (:id_list)"
  ["count"]=>
  int(0)
}

array(3) {
  ["using"]=>
  string(60) " the parameters directly in the expr()->in() without binding"
  ["sql"]=>
  string(63) "SELECT * FROM test_table WHERE test_table.test_id IN (123, 456)"
  ["count"]=>
  int(2)
}
```

Please let me know any other info needed or any way that I can help.

**Comment by ricardofiorani** [comment] 2019-01-23 10:04
Changing the DSN to connect to MariaDB, the same code above outputs this:

```
/code/asd.php:37:
array(3) {
  'using' =>
  string(42) "\Doctrine\DBAL\Connection::PARAM_INT_ARRAY"
  'sql' =>
  string(63) "SELECT * FROM test_table WHERE test_table.test_id IN (:id_list)"
  'count' =>
  int(2)
}

/code/asd.php:55:
array(3) {
  'using' =>
  string(39) "\Doctrine\DBAL\Types\Type::SIMPLE_ARRAY"
  'sql' =>
  string(63) "SELECT * FROM test_table WHERE test_table.test_id IN (:id_list)"
  'count' =>
  int(1)
}

/code/asd.php:71:
array(3) {
  'using' =>
  string(60) " the parameters directly in the expr()->in() without binding"
  'sql' =>
  string(63) "SELECT * FROM test_table WHERE test_table.test_id IN (123, 456)"
  'count' =>
  int(2)
}
```

**Comment by Ocramius** [comment] 2019-01-23 10:05
What does the prepared statement bound parameter look like? Specifically, what is being bound to `:id_list`?

**Comment by ricardofiorani** [comment] 2019-01-23 10:18
@Ocramius binding them with `\Doctrine\DBAL\Types\Type::SIMPLE_ARRAY` will result the following code:

```php
var_dump([
    'parameters' => $q->getParameters(),
    'parameterTypes' => $q->getParameterTypes(),
]);
```
To give the following output for both MariaDB and SQLite:
```
array(2) {
  'parameters' =>
  array(1) {
    'id_list' =>
    array(2) {
      [0] =>
      int(123)
      [1] =>
      int(456)
    }
  }
  'parameterTypes' =>
  array(1) {
    'id_list' =>
    string(12) "simple_array"
  }
}
```

**Comment by ricardofiorani** [comment] 2019-01-23 10:20
Please let me know if I understood correctly what you meant/want, or how can I see exactly how the parameters are bound to the final executed SQL.

**Comment by Ocramius** [comment] 2019-01-23 11:40
Hmm, I guess the SQL logger is not deep enough in this, as it retrieves the non-converted value. I'd need to see what happens around following line: 

https://github.com/doctrine/dbal/blob/9b88bf3711b8472e75cae98e947a20f0df202d77/lib/Doctrine/DBAL/Driver/PDOStatement.php#L91

**Comment by morozov** [comment] 2021-10-30 20:51
Closing as the primary issue in question is by design.

**Closed by morozov** 2021-10-30 20:51 UTC
Labels: Missing Tests, Bug, MariaDB, Prepared Statements, Type Conversion
