### ISSUE TITLE
Doctrine\DBAL\DBALException  : Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

### ISSUE THREAD

**Issue by ashuiccc** [doctrine/dbal#3651] opened 2019-08-11 03:23 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.9.2

#### Summary

when I use php artisan migrate command(mysql8.0), there is an error=>Doctrine\DBAL\DBALException  : Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

#### How to reproduce

I^m not sure if mysql5.7 has this problem,but after I use mysql8.0,when I change the fields attribute,the err error has appeared.

#### Expected behaviour

The database field can be modified normally.

**Comment by SenseException** [comment] 2019-08-16 22:22
MySQL 8 should use `MySQL80Platform`. Please check if there is a configuration issue in the project you are working on. A bug also has to be reproducible without artisan. Next to a configuration issue, this can also happen in case of a incorrect usage of DBAL.

A reproducible example of this with DBAL only is appreciated.

**Comment by Afnisse** [comment] 2020-09-02 19:37
in Laravel the right fix for this problem is to add a server version on config/database.php under the MySQL section.

`'server_version'      => "5.7"`

because if you don't, Doctrine will use Doctrine\DBAL\Platforms\MySqlPlatform which supports all versions of MYSQL since MYSQL 5.0 which does not support JSON fields, and by adding the server_version doctrine will load MySQL57Platform that have support for JSON instead of MySqlPlatform.

example of database MySQL config:
```
'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'server_version' => "5.7",
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
```

**Comment by morozov** [comment] 2022-08-05 06:19
Looks like a duplicate of https://github.com/doctrine/dbal/issues/5557 and a bunch of similar issues.

**Closed by morozov** 2022-08-05 06:19 UTC
