### ISSUE TITLE
Schema\Index does not handle functional indexes

### ISSUE THREAD

**Issue by jusurb** [doctrine/dbal#5403] opened 2022-05-17 20:39 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.6

#### Summary

Doctrine migrations when running diff tool constructs a schema from current DB and when it encounters a Mysql 8 functional index it breaks as it fails to extract a column name. It seams current implementation of Schema\Index does not support functional indexes.

#### How to reproduce

```sql
CREATE TABLE warehouse_parts
	ADD part_number_suffix VARCHAR(8) NULL;
	ADD INDEX idxf_part_number_suffix((REGEXP_SUBSTR(part_number_suffix, '[0-9]+')))
```

run `bin/console doctrine:migrations:diff`

#### Expected behaviour

should either ignore the index or handle it without breaking

#### Stacktrace 

```
In Index.php line 83:

  [TypeError]
  Argument 1 passed to Doctrine\DBAL\Schema\Index::_addColumn() must be of the type string, null given, called in /var/www/html/vendor/doctrine/dbal/src/Schema/Index.php on line 72


Exception trace:
  at /var/www/html/vendor/doctrine/dbal/src/Schema/Index.php:83
 Doctrine\DBAL\Schema\Index->_addColumn() at /var/www/html/vendor/doctrine/dbal/src/Schema/Index.php:72
 Doctrine\DBAL\Schema\Index->__construct() at /var/www/html/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:1072
 Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableIndexesList() at /var/www/html/vendor/doctrine/dbal/src/Schema/MySQLSchemaManager.php:104
 Doctrine\DBAL\Schema\MySQLSchemaManager->_getPortableTableIndexesList() at /var/www/html/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:228
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableIndexes() at /var/www/html/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:328
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails() at /var/www/html/vendor/doctrine/dbal/src/Schema/MySQLSchemaManager.php:336
 Doctrine\DBAL\Schema\MySQLSchemaManager->listTableDetails() at /var/www/html/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:306
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTables() at /var/www/html/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:1229
 Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema() at /var/www/html/vendor/doctrine/migrations/lib/Doctrine/Migrations/Generator/DiffGenerator.php:130
 Doctrine\Migrations\Generator\DiffGenerator->createFromSchema() at /var/www/html/vendor/doctrine/migrations/lib/Doctrine/Migrations/Generator/DiffGenerator.php:88
 Doctrine\Migrations\Generator\DiffGenerator->generate() at /var/www/html/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php:154
 Doctrine\Migrations\Tools\Console\Command\DiffCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1033
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/bin/console:42
```

**Comment by greg0ire** [comment] 2022-05-17 20:45
Duplicate of #5306

**Closed as not planned by greg0ire** 2022-05-17 20:45 UTC

**Comment by jusurb** [comment] 2022-05-17 20:53
oh sorry, missed it

**Comment by greg0ire** [comment] 2022-05-17 20:56
No worries, this has happened to me many times as well. We are too hasty!
