### ISSUE TITLE
executeQuery() blocks forever on AWS lambda while persisting several objects at once into RDS

### ISSUE THREAD

**Issue by jean553** [doctrine/dbal#5176] opened 2022-01-12 15:42 UTC
### Bug Report

INSERT SQL command blocks on AWS lambda while trying to persist several objects.
Only occurs when SQL logger is not null.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.2.0

#### All versions

doctrine-dbal 3.2.0
PHP 8.1.1 
PostgreSQL 13.3 (AWS RDS)

#### Summary and how to reproduce

I use Doctrine DBAL for a Symfony project running on AWS lambda deployed with bref (https://github.com/brefphp/bref). One of my action inserts multiple objects one by one in database through multiple `INSERT` SQL queries.

**Problem:** If I try to execute more than a certain amount of INSERT (around ~100), then only a few amount of those INSERT are executed (around ~40); then, one INSERT hangs forever, blocking the whole process.

```php
for ($i = 0; $i < 100; $i += 1) {

    $statement = $connection->prepare("INSERT INTO ... "); // blocks here forever after ~40 successful INSERTs
    $result = $statement->executeQuery();
}
```

The amount of successful INSERTs before it blocks is not exactly the same at each attempt. It can be 38 the first attempt, then 41 the next one.

When checking the table `pg_stat_activity` while it blocks, we can the see the follwing wait_event for the INSERT:

```
usename          | symfony_user
application_name | 
client_hostname  | 
client_port      | 3217
backend_start    | 2022-01-12 16:46:49.912008+00
xact_start       | 
query_start      | 2022-01-12 16:46:50.170347+00
state_change     | 2022-01-12 16:46:50.172585+00
wait_event_type  | Client
wait_event       | ClientRead
state            | idle
backend_xid      | 
backend_xmin     | 
query            | INSERT INTO ... ;
```

**Workaround**: The issue does not happen anymore if I add `$entityManager->getConnection()->getConfiguration()->setSQLLogger(null);` before inserting. In that case, all the objects are correctly inserted.

Another possible workaround is to directly use PDO without the DBAL anymore. In that case, it works as expected:

```php
$db = new \PDO('pgsql: ...');

foreach ($objects as $oneObject) {

    $statement = $db->prepare("INSERT INTO ... etc ...");
    $statement->execute();
}

// no problem, all objects inserted
```

#### Current behaviour

If I try to execute more than a certain amount of INSERT (around ~100), then only a few amount of those INSERT are executed (around ~40); then, one INSERT hangs forever, blocking the whole process.

#### Expected behaviour

Whatever the amount of consecutive INSERTs performed to the database, they should all be executed without having one blocking.

**Comment by morozov** [comment] 2022-01-12 20:34
@jean553, a few questions:

1. Are you sure your RDS doesn't run out of IOPS or something like this?
2. Why do you think it's a DBAL issue? ~~Does it work for you without the DBAL?~~ (I see, you mentioned a workaround)

Normally, we don't provide this kind of support here. If you want the issue considered for fixing, you'll have to at least provide us access to the environment where the issue can be reproduced.

**Comment by allan-simon** [comment] 2022-01-13 08:29
Hello @morozov (I'm a coworker of @jean553) 

1. yes, the instance is a m5.large and we ruled out the IOPS hypothesis by testing the same workload with other methods (direct PDO, pyhon script etc. )  and doing other INSERT directly while the PHP call with DBAL is "blocked". If anything having the SQLLogger activated slowing down things should help in that case (less query per second, less IOPS), while here it's the opposite.
2. We think it's DBAL because:
   1.  with direct PDO of running the very exact same queries the issue does not happen
   2.  the issue with DBAL does not happen when we deactivate the SQL logger
   3.  the pg_stat_activity show the server is waiting for an action (ClientRead) from the client (i.e php process)

Could it be that the SQLLogger generate an exception or cause the statement to take a bit too much of time ? causing the connection to become in an unstable state (the previous query was not correctly finished, so the server is stil waiting for it to be finished , while DBAL is already trying to do the next insert ? )

**Comment by morozov** [comment] 2022-01-13 15:53
As far as I can tell, the DBAL doesn't ship any specific `SQLLogger` implementations except for the deprecated `DebugStack`, so you must be using some own or 3rd-party logger. What logger is that? Would the issue reproduce if you use the null logger from #3041?

If you can connect to the database from the development environment (e.g. via a public endpoint or port forwarding), you could try using a debugger and see where exactly the client code gets stuck.

**Comment by allan-simon** [comment] 2022-01-13 18:19
We use monolog , through symfony, good idea for the NullLogger, we will try that, thanks a lot for the pointer.

**Comment by allan-simon** [comment] 2022-01-17 19:33
hello may i know why is it closed, even if the problem is caused by the logger,  the logger being not responsible of the connection, it should not cause DBAL to hang , at least it should re-throw the exception ?

**Comment by morozov** [comment] 2022-01-17 21:51
Sorry, I meant to close another issue.

> at least it should re-throw the exception

If you believe something needs to be changed in the DBAL, please provide the steps to reproduce the scenario in question.

**Comment by allan-simon** [comment] 2022-01-17 22:47
> If you believe something needs to be changed in the DBAL, please provide the steps to reproduce the scenario in question.

no problem, I will work on finding a reproducing scenario :)

**Comment by morozov** [comment] 2022-02-13 08:03
Closing as not reproducible. Please feel free to post more details if it turns out that the root cause is in the DBAL.

**Closed as completed by morozov** 2022-02-13 08:03 UTC
Labels: pdo_pgsql, Question
