### ISSUE TITLE
Laravel MySQL DB migrations failing since version 2.10.0

### ISSUE THREAD

**Issue by bartjuh4** [doctrine/dbal#3789] opened 2019-12-20 10:58 UTC
### Bug Report
Laravel Database Migrations failing since dbal upgrade from 2.9.2 to 2.10.0:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`' at line 1 (SQL: ALTER TABLE user_federations CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT CHARACTER S  
  ET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`)       

#### Current behaviour
When you have a string field and change it to a bigInteger field strange character set errors are occurring. 

#### How to reproduce
Create a Laravel db migration with an string column and make another migration with a change to that column where you change it to bigInteger.

**Comment by lcobucci** [comment] 2019-12-24 08:14
As discussed in https://github.com/laravel/framework/issues/30539 this is being handled in Laravel.

**Comment by lcobucci** [comment] 2019-12-24 08:14
Closing as duplicate of https://github.com/doctrine/dbal/issues/3714

**Closed by lcobucci** 2019-12-24 08:14 UTC
