### ISSUE TITLE
OCI8 - undefined index, CRITICAL !

### ISSUE THREAD

**Issue by michaljusiega** [doctrine/dbal#3766] opened 2019-12-02 08:42 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10

#### Summary

Some changes in 2.10 make a BC break. On line 281 in OCI8Statement, the column is not valid in array, so throws a Notice: Undefined index: test.

Before upgrade to 2.10 the line looks like:
`$column = $this->_paramMap[$column] ?? $column;`

After upgrade do 2.10 is:
`$column = $this->_paramMap[$column];`

#### Current behaviour

Undefined index in array. The null coalesce operator was removed (WHY, who accept this ?)

![obraz](https://user-images.githubusercontent.com/16488888/69944505-c696e480-14e7-11ea-9e3f-421f9efc3e2d.png)

#### How to reproduce

The EntityManager must be of OCI8 instance.

```
$query = $this->entityManager->getConnection()->prepare($prepareSQL);
$query->bindValue('test', 'testvalue');
$query->execute();
```

#### Expected behaviour

Should be work by using default column.

Gentlemen. A bit of partolite work with doctrine. You have very poor standards, these things should not appear. Remember: If something works, don't move it.

**Comment by Ocramius** [comment] 2019-12-02 08:59
> You have very poor standards

Uhm, no, the change was introduced because we do have good and also strict standards, and that was highlighted (although incorrectly) by analysis.

Meanwhile, closing as duplicate of #3738

**Comment by michaljusiega** [comment] 2019-12-02 09:04
DAFUQ. So now will be throws exception ? Nice ... your standards.

**Comment by michaljusiega** [comment] 2019-12-02 09:07
Nevermind.

**Comment by Ocramius** [comment] 2019-12-02 09:09
Right, locking here: please refrain from opening further issues, if this is the level of discussion.

**Closed by Ocramius** 2019-12-02 09:09 UTC
Labels: Duplicate, Oracle, Prepared Statements
