### ISSUE TITLE
`fetchAllAssociative` does return wrong stream with Oracle with CLOB column

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5002] opened 2021-11-19 23:27 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.4

#### Summary

`fetchAllAssociative` is implemented in https://github.com/doctrine/dbal/blob/94fe5c7057e2c47bac8833e81aeb8691b7f27d05/src/Driver/FetchUtils.php#L53 by saving row by row into the resulting array

#### Current behaviour

once iterator moves to the next row, the previous stream provided by Oracle CLOB column will return empty string (or null, if it CLOB value was null)

#### How to reproduce

SQL queries for Oracle 11r2g database:
```
CREATE TABLE "invoice" ("id" NUMBER(10) NOT NULL, "ref_no" VARCHAR2(255) NOT NULL, "addr" CLOB DEFAULT NULL NULL, PRIMARY KEY("id"));
START TRANSACTION;
insert into "invoice" ("id", "ref_no", "addr") values ('1', 'A1', '{"ownerReference":null}');
insert into "invoice" ("id", "ref_no", "addr") values ('2', 'A2', null);
COMMIT;
select * from "invoice";
```

result with current DBAL `FetchUtils::fetchAllAssociative` impl.:
```
array(2) {
  [0]=>
  array(3) {
    ["id"]=>
    string(1) "1"
    ["ref_no"]=>
    string(2) "A1"
    ["addr"]=>
    string(0) ""
  }
  [1]=>
  array(3) {
    ["id"]=>
    string(1) "2"
    ["ref_no"]=>
    string(2) "A2"
    ["addr"]=>
    NULL
  }
}
```

when the https://github.com/doctrine/dbal/blob/94fe5c7057e2c47bac8833e81aeb8691b7f27d05/src/Driver/FetchUtils.php#L54 impl is changed to "materialize" the stream data into a string before moving to the next row, the result is following/correct:

I belive it is related with https://bugs.php.net/bug.php?id=46728

#### Expected behaviour

```
array(2) {
  [0]=>
  array(3) {
    ["id"]=>
    string(1) "1"
    ["ref_no"]=>
    string(2) "A1"
    ["addr"]=>
    string(23) "{"ownerReference":null}"
  }
  [1]=>
  array(3) {
    ["id"]=>
    string(1) "2"
    ["ref_no"]=>
    string(2) "A2"
    ["addr"]=>
    NULL
  }
}
```

**Comment by morozov** [comment] 2021-11-21 16:17
Which driver are you using? The `oci8` one uses `OCI_RETURN_LOBS`, so it should make the driver return the string instead of the descriptor.

Please make sure you provide an example of the code that reproduces the problem. As far as I can tell, neither `oci8` nor `pdo_oci` use `FetchUtils` to implement `fetchAllAssociative()`.

**Comment by mvorisek** [comment] 2021-11-21 16:32
I use `pdo_oci`, this change in atk4/data framework fixed the issue: https://github.com/atk4/data/pull/922/commits/5e50ca6aae0f55b200434ad9c21b52ea3631bf37 , so the maybe `FetchUtils::fetchAllAssociative()` impl. is not called, but the impl. with `while` and "early stream to string materialization" helped.

**Comment by morozov** [comment] 2021-11-23 07:11
It does look related to the `pdo_oci` bug:
```php
$pdo = new PDO('oci:dbname=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=XE)))', 'system', 'oracle');
$stmt = $pdo->query('select * from "invoice"');
$data = $stmt->fetchAll(PDO::FETCH_ASSOC);
var_dump($data[0]['addr']);
// resource(41) of type (stream)
var_dump(stream_get_contents($data[0]['addr']));
// string(0) ""
```
In general, it's a bad idea to read multiple LOB streams into a string since it can use an unpredictable amount of memory. It's even worse that the DBAL does that implicitly and by default in the `oci8` driver.

At the same time, AFAIK, unlike PostgreSQL, the Oracle driver cannot maintain multiple LOB streams from the same result.

**Comment by morozov** [comment] 2022-01-21 18:27
Closing as this is caused by the underlying driver's implementation details.

**Closed as completed by morozov** 2022-01-21 18:27 UTC
Labels: Invalid, pdo_oci

**Comment by mvorisek** [comment] 2022-01-21 18:32
for doc purposes, waiting for https://github.com/php/php-src/pull/5233 PR
