### ISSUE TITLE
SQLServerPlatform and nullable fields

### ISSUE THREAD

**Issue by umpirsky** [doctrine/dbal#2320] opened 2016-02-18 08:56 UTC
There is a mapping:

``` php
/**
 * @ORM\ManyToOne(targetEntity="Foo")
 * @ORM\JoinColumn(name="foo_id", referencedColumnName="id")
 */
private $foo;
```

Schema create generates following SQL with different platforms:

MySQL: `CREATE TABLE xxx (id INT AUTO_INCREMENT NOT NULL, foo_id INT DEFAULT NULL,...`
MSSQL: `CREATE TABLE xxx (id INT IDENTITY NOT NULL, foo_id INT,...`

This leads to `foo_id` not allowing NULL values in MSSQL database, but does with MySQL.

I tried to change in [SQLServerPlatform.getColumnDeclarationSQL](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php#L1550):

``` diff
-            $notnull = (isset($field['notnull']) && $field['notnull']) ? ' NOT NULL' : '';
+            $notnull = (isset($field['notnull']) && $field['notnull']) ? ' NOT NULL' : ' NULL';
```

And that did the trick.

**Comment by vetruvet** [comment] 2016-04-13 03:48
Same issue - this also causes problems later on in my code when I try to create foreign keys with `ON DELETE SET NULL` - works fine in MySQL but breaks in MSSQL.

**Comment by umpirsky** [comment] 2016-04-13 07:06
@vetruvet As a temporary workaround you can override `SQLServerPlatform` as I suggested in bug description.

**Comment by morozov** [comment] 2021-10-31 18:02
I cannot reproduce this:
```sql
DROP TABLE IF EXISTS xxx;
CREATE TABLE xxx (id INT IDENTITY NOT NULL, foo_id INT, test VARCHAR(16));
INSERT INTO xxx(test) VALUES('foo');
SELECT * FROM xxx;

-- +----+--------+------+
-- | id | foo_id | test |
-- +----+--------+------+
-- |  1 | <NULL> | foo | 
-- +----+--------+------+
```
Closing for now. Please provide a failing test to reopen.

**Closed by morozov** 2021-10-31 18:02 UTC
Labels: Bug, SQL Server, Platforms, Schema, Schema Definition
