### ISSUE TITLE
Column option "autoincrement" => "auto" causes schema diffs

### ISSUE THREAD

**Issue by sandermarechal** [doctrine/dbal#3389] opened 2018-12-06 11:07 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.0

#### Summary

Schema diff generates a diff for columns that use the (undocumented) value of `"auto"` for the "autoincrement" option. This would normally be trivial, but the rather popular symfony/security-acl package defines all it's tables with an `"id"` column with the option `"autoincrement" => "auto"`.

#### Previous behaviour

A schema diff (update) when using Symfony ACL only generates expected updates.

#### Current behavior

A schema diff (update) when using Symfony ACL also generates updates for the `"id"` column of all ACL tables.

#### How to reproduce

Setup a standard Symfony, add the security ACL, initialize the ACL tables, run "bin/console doctrine:schema:update --dump-sql".

### Cause

I have identified commit dca1465bdc0836c71ed97e46820490127ccc89ab as the cause, specifically in `Doctrine\DBAL\Schema\Comparator` [line 415](https://github.com/doctrine/dbal/commit/dca1465bdc0836c71ed97e46820490127ccc89ab#diff-6a252b2e905db4e03fc6a121a41e6466L415) which changes the column property comparison from != to ===. In the old version "auto" and true would compare equal. In the new version they do not compare equal, causing the schemas to differ.

**Comment by sandermarechal** [comment] 2018-12-06 11:14
See also symfony/security-acl#43

**Comment by Ocramius** [comment] 2018-12-06 13:38
Would it be possible to isolate this into a test case? Patch seems easy to
do, once we prevent regressions via a test.

**Comment by sandermarechal** [comment] 2018-12-06 13:59
That should be easy. Just use a Schema with a column that has `"autoincrement" => "auto"` as an option as the "from" schema, and one with `"autoincrement" => true` as an option in the "to" schema. Diff 'em and the diff should be empty.

**Comment by sandermarechal** [comment] 2018-12-10 09:21
I have added a failing test case. I am not sure what the best solution would be though. Do a sloppy comparison? Or just add a special-case for the string 'auto'?

**Comment by morozov** [comment] 2018-12-10 17:04
@sandermarechal looks like most schema managers cast the value of `autoincrement` to a boolean but the one for MySQL doesn't. If so, the manager should be fixed, not the comparator.

**Comment by sandermarechal** [comment] 2018-12-11 08:15
Symfony ACL is fixing it on their end, but that doesn't account for already released versions. I would propose adding a special case for the string "auto" only, and documenting that it is for BC with symfony/security-acl.

**Comment by Ocramius** [comment] 2018-12-11 14:44
> Sorry, I re-read it again. @Ocramius given that it's an undocumented behavoir, should we still support it (maybe by adding a special case for the `"auto"` value in the comparator) or expect it to be fixed on the calling side. Relying on `"auto" == true` is really creepy.

No, this should not be handled on this end: the value is supposed to be a boolean.

As @sandermarechal mentioned right above, this is being fixed in `symfony/security-acl`, which is the root cause.

@sandermarechal let's not pursue this further: closing as `invalid` here.

**Closed by Ocramius** 2018-12-11 14:44 UTC
Labels: Bug, Regression, Schema Comparison, Schema Introspection

**Comment by sandermarechal** [comment] 2018-12-13 12:31
@Ocramius symfony/security-acl fixing it on their end does nothing for the large amount of versions already released which claim to be compatible with 2.9.0 but now are not due to this issue.

Since symfony-acl is quite a popular and widely used package, I had hoped you could add a special case for "auto". You could immediately deprecate it and then remove it in DBAL 3.0.0.

**Comment by Ocramius** [comment] 2018-12-13 12:34
No, I'd not consider that for two main reasons:

 1. this is a schema-change-only issue, not something that affects runtime behavior.
 2. `symfony/security-acl` can be upgraded downstream, and is the root cause: we shouldn't make workarounds in first place, and even less for something that is being patched.

Upgrading dependencies is a correct and sensible approach.
