### ISSUE TITLE
Connection passes just everything to the logger

### ISSUE THREAD

**Issue by jaapio** [doctrine/dbal#3413] opened 2018-12-18 07:58 UTC
### Bug Report

We have a situation where we use a query builder to create a query and pass that to a native query. This querybuilder object is passed to the logger which perfectly logs the query. So far so good. 
But things are going wrong when the logger is not just logging the query to a resource but is first serializing the data before writing it to the final destination. Like the symfony debug toolbar does. 

https://github.com/symfony/symfony/issues/29634 

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | v2.5.13

#### Summary

Because the documentation stats that the input of logger should be a `string` the implementor should rely on that. But it could be literally any object. there is no type check done. 

#### Current behaviour

Non strings are passed to the logger. 

#### Expected behaviour

I would suggest that we add a cast in each call of the `Connection` to the logger which casts the `$query` param to a string. In the end adding a type hint so the `$query` param can only be a string would be the best option. But I don't know if it is possible to add those without breaking the code. Which of course depends on the supported php versions of DBAL.

**Comment by Ocramius** [comment] 2018-12-18 10:02
> This querybuilder object is passed to the logger which perfectly logs the query

This is invalid: only the query string should be passed in.

> add a cast in each call

No, the correct type is to be given by the consumer. We didn't have scalar type hints when this API was designed, but that's not an excuse to pass invalid types at runtime.

**Comment by jaapio** [comment] 2018-12-18 12:57
In that case we have to adjust our own code. which isn't an issue.

More people are facing this issue. Since the QueryBuilder or any other object implementing a toString method will works a query. I do agree with you that we shouldn't pass invalid types at runtime. But currently DBAL accepts this. which causes errors later on in the process. While the code does run ok. 
What would you advice to prevent this kind of issues? Would you accept a PR adding scalar typehints for this part? 

I understand that it written this way. But I would like to help the project to improve at this point.

**Comment by Ocramius** [comment] 2018-12-18 13:00
> Would you accept a PR adding scalar typehints for this part?

Not possible in `2.x` due to backwards compatibility. This has already been fixed in `develop`.

Please note that if the type says `string`, it means `string`, not something that may implement `->__toString()`.

This kind of error is typically detected via type checker, such as [psalm](https://github.com/vimeo/psalm) or [phpstan](https://github.com/phpstan/phpstan).

**Closed by Ocramius** 2018-12-18 13:00 UTC
