### ISSUE TITLE
Mysql @ManyToMany useless index

### ISSUE THREAD

**Issue by tmbdrogba** [doctrine/dbal#2741] opened 2017-06-12 07:59 UTC
Let's say I have this basic @manytomany relationship:

```
// Entity A
class A {

    /**
    * @ManyToMany(targetEntity="B")
    */
    private $b;
```
Doctrine creates a relation table `a_b` with two fields, with a primary key on those two fields. That's the right way.

Things is : it also creates two more indexes, one on each field, for the foreign keys. **Why not just one ?**

Actually, if my primary key is composite of `A` (as the primary field of the primary key) and `B`, mysql requires only one more index for the foreign key on B, **no need for A.**

To resume, my table indexes should be :
- primary : A-B
- index : B

with two foreign keys on A and B

But it looks like :

- primary : A-B
- index : B
- index : A

with two foreign keys on A and B

**Comment by Ocramius** [comment] 2017-06-12 08:08
Duplicate of https://github.com/doctrine/doctrine2/issues/6495 ?

**Closed by Ocramius** 2017-06-12 08:08 UTC

**Comment by tmbdrogba** [comment] 2017-06-12 08:12
Yes it's a duplicate, but I thought it was better to opened it here than in the doctrine2 repo

**Comment by Ocramius** [comment] 2017-06-12 08:14
Also duplicates https://github.com/doctrine/dbal/pull/2470
