### ISSUE TITLE
Oracle ORA-01036 - Illegal variable name/number on Dbal 2.10

### ISSUE THREAD

**Issue by atay** [doctrine/dbal#3765] opened 2019-12-02 07:43 UTC
### Bug Report

For new Dbal 2.10.0 on my Oracle connector, it fails. It fails on bindParam function call.
It is still working fine with dbal 2.9.*, so I had to downgrade for now.
Not sure if it's related to https://github.com/doctrine/dbal/issues/3744

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.10.0

#### Summary

Executing code:
```
        $statement = $this->connection->prepare('CALL apw_user.GET_SPRZ_ID(:v_SPRZ_ID)');
        $statement->bindParam('v_SPRZ_ID', $sprzId, PDO::PARAM_INPUT_OUTPUT, 32);
```
returns an error:
```
Warning: oci_bind_by_name(): ORA-01036: illegal variable name/number
```
which was working fine for dbal 2.9.*. 

#### Current behaviour

```
Warning: oci_bind_by_name(): ORA-01036: illegal variable name/number
```

#### How to reproduce

The procedure in Oracle.
```
create PROCEDURE GET_SPRZ_ID (NUMER OUT INTEGER) 
AS BEGIN 
  SELECT ID_SPRZ.nextval into NUMER from dual; 
END;
/
```

#### Expected behaviour

There should be no error on execution.

**Comment by morozov** [comment] 2019-12-02 15:45
It must be a duplicate of #3722.

**Closed** 2019-12-07 00:41 UTC
