### ISSUE TITLE
Improve Type system

### ISSUE THREAD

**Issue by guilhermeblanco** [doctrine/dbal#3733] opened 2019-11-12 04:56 UTC
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

Our current mapping types implementation is a simple Registry. Also, Types have private final constructors, which make it impossible to implement more elaborated data types that are not necessary members of the static type map (such an example would be a LazyDataType that would require a constructor initializer and instance-level property values, which conflicts with current Type and TypeMap registry implementation.

We should implement a more powerful, TypeFactory (ideas welcome) implementation that could operate in a prototypical way (ever request builds a new Type) or a singleton-ish (every request returns same Type instance).

**Comment by morozov** [comment] 2022-08-06 18:24
Closing as a duplicate of https://github.com/doctrine/dbal/issues/2841.

**Closed by morozov** 2022-08-06 18:24 UTC
Labels: New Feature, Types, Type Mapping
