### ISSUE TITLE
CS change on Comparator causes generating ALTER SEQUENCE even when nothing changed

### ISSUE THREAD

**Issue by finwe** [doctrine/dbal#3195] opened 2018-06-20 11:08 UTC
### Bug Report

The change of `!=` to `!==` on line 187 in https://github.com/doctrine/dbal/commit/3d75905643ff384544b78c564cf9953d8572996f caused Doctrine Migrations to generate ALTER SEQUENCE for every sequence there is, because compared  values are string `"1"` vs int `1`.

This occurs (at least) on PostgreSQL 10.

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | 2.7.1

#### Current behavior

diffSequence returs true even when the sequence didn't change. Therefore every sequence is marked as changed and ALTER SEQUENCE SQL is generated for all present sequences.

#### How to reproduce

Generate a migration with doctrine/migrations on PostgreSQL 10 database with sequences after upgrading DBAL from 2.6.3 to 2.7.1.

#### Expected behavior

No migrations should be generated.

**Comment by Majkl578** [comment] 2018-06-20 11:37
Duplicate of #3086

**Comment by Majkl578** [comment] 2018-06-20 11:37
Will be released in 2.7.2 + 2.8.0 soon.

**Closed by Majkl578** 2018-06-20 11:37 UTC

**Comment by finwe** [comment] 2018-06-20 11:48
Oh, will also search in merged next time. Thanks! 

20. června 2018 13:37:59 SELČ, Michael Moravec <notifications@github.com> napsal:
>Will be released in 2.7.2 + 2.8.0 soon.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/doctrine/dbal/issues/3195#issuecomment-398719006

-- 
Odesláno aplikací K-9 Mail ze systému Android. Omluvte prosím moji stručnost.
