### ISSUE TITLE
When a RetryableException is thrown, entitymanager should not be closed

### ISSUE THREAD

**Issue by kcassam** [doctrine/dbal#2625] opened 2017-01-31 10:54 UTC
When a RetryableException is thrown, entitymanager should not be closed

RetryableException are DeadlocException and LockWaitTimeoutException

entitymanager should not be closed so we can retry the flush like that

```
/*
    * Since doctrine 2.6, you cannot retry a flush when an exception had appeared 
    * because the entity manager is closed and all entities detach, even with a RetryableException. 
    * This function won't work, bescause if there is an Exception, the em is closed. 

    private retryflush() {

        $retry = 0;
        while ($retry < 3) {
            try {
                $this->em->flush();
                return;
            } catch (RetryableException $e) {
                
                if ($retry >= 2) {
                    throw $e;
                }
                sleep(1);
                $this->reset();
                $retry++;
            } 
        }
    }
*/

```

**Comment by Ocramius** [comment] 2017-01-31 10:55
> Since doctrine 2.6,

Since ORM 2.0?

**Comment by deeky666** [comment] 2017-01-31 13:03
Shouldn't this be handled in ORM? Don't see what we can do here in DBAL about it.

**Comment by Ocramius** [comment] 2017-01-31 13:07
@deeky666 no, ORM just throws and closes the UnitOfWork on purpose, since no guarantee is present about synchronicity of the entities with the DB. This is expected, and behavior may also change depending on whether the underlying DB supports transactions or not. Also, listeners may cause additional mayhem too.

**Comment by deeky666** [comment] 2017-01-31 13:24
@Ocramius I see but what is the expected behaviour of DBAL here then?

**Comment by Ocramius** [comment] 2017-01-31 13:44
@deeky666 oh, darn, was totally convinced that this issue was on the ORM repo. Closing as `invalid`, since this issue mixes up things. Retries should be done at lower level: the ORM is not designed to do that internally anyway.

**Closed by Ocramius** 2017-01-31 13:44 UTC

**Comment by kcassam** [comment] 2017-02-01 15:28
Thanks, an sorry 
https://github.com/doctrine/doctrine2/issues/6272
