### ISSUE TITLE
Doctrine abstract methods must be declared in Driver

### ISSUE THREAD

**Issue by marky291** [doctrine/dbal#2628] opened 2017-02-04 02:05 UTC
I have out of nowhere received this error using laravel 5.4, windows 10.

I am using the latest version of dbal, but issue occured on version, "doctrine/dbal": "~2.3",

`Class Doctrine\DBAL\Driver\PDOStatement contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Doctrine\DBAL\Driver\Statement::errorCode, Doctrine\DBAL\Driver\ResultStatement::closeCursor, Doctrine\DBAL\Driver\ResultStatement::columnCount)`

The problem seems to be with the package?

**Comment by marky291** [comment] 2017-02-04 02:09
in C:\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php line 28

**Comment by marky291** [comment] 2017-02-04 02:28
Might be obvious, but removing the package solves the problem, I hope there is a fix for this, otherwise I will have to rewrite my laravel migrations without it.

**Comment by deeky666** [comment] 2017-02-04 10:49
The class does not contain any abstract methods nor does PHP's `\PDOStatement` which it extends. Is there maybe something wrong with your PHP PDO installation?

**Comment by deeky666** [comment] 2017-02-04 10:50
Sorry, the error is related to the interface (I was distracted by the "abstract" keyword). But still. `\PDOStatement` implements all of those by default.

**Comment by deeky666** [comment] 2017-02-04 10:52
Closing as invalid as it is not DBAL related.

**Closed by deeky666** 2017-02-04 10:52 UTC
Labels: Invalid

**Comment by marky291** [comment] 2017-02-04 14:37
Maybe this is a laravel issue ?

I removed the dbal package which was required for laravel migration table renaming. *change ()* method.

Now it's not an issue for me but could for others?

**Comment by deeky666** [comment] 2017-02-04 16:24
@marky291 you can try to reproduce this error without laravel context. We cannot look into every third party package that could cause issues. You need to have an isolated DBAL environment.

**Comment by vogelor** [comment] 2017-07-19 10:31
After adding this code to 
vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php
it works for me.
so i think they are missing to implement some needed abstract functions.

i know, the code is not "great" but maybe it helps finding the "real error"


	public function errorInfo() {
		parent::errorInfo();
	}

	public function closeCursor() {
		parent::closeCursor();
	}

	public function columnCount() {
		parent::columnCount();
	}

**Comment by Ocramius** [comment] 2017-07-21 00:13
These methods are already implemented in DBAL. Maybe a polyfill is defining
a pdo interface in a non-compatible way in Laravel.

Until this is tested in isolation (DBAL test suite), the issue stays closed.

On 19 Jul 2017 12:31 PM, "vogelor" <notifications@github.com> wrote:

After adding this code to
vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php
it works for me.
so i think they are missing to implement some needed abstract functions.

i know, the code is not "great" but maybe it helps finding the "real error"

public function errorInfo() {
	parent::errorInfo();
}

public function closeCursor() {
	parent::closeCursor();
}

public function columnCount() {
	parent::columnCount();
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/dbal/issues/2628#issuecomment-316343388>, or mute
the thread

**Comment by vogelor** [comment] 2017-07-25 18:44
after some research of the code i agree with you. i also think this is a problem of laravel.
