### ISSUE TITLE
Sql with LIKE ESCAPE '\' breaks replacing named parameters to '?' and leads to a sql error

### ISSUE THREAD

**Issue by vavra** [doctrine/dbal#3371] opened 2018-11-29 14:40 UTC
See attached test. If as a like escape character is used '~' everything is OK. If one replaces ~ to \\ than an sql error occurs: 

An exception occurred while executing
```sql
SELECT NAME FROM DOCUMENT
WHERE (ID_FLDR_DOCU = ?)			
	AND (NAME LIKE ? ESCAPE '\')
	AND (
		(A = :p2_A)		
		OR (
			B IS NULL
			OR B = ''
			)
		)
	AND (
		C IS NOT NULL
		AND C <> ''
		)		
ORDER BY NAME ASC OFFSET 0 ROWS
FETCH NEXT 5 ROWS ONLY
```
with params [3, "%1\\_\\\\\\_5bfff30585b261.25683875.pdf"]:

SQLSTATE [42000, 102]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near ':'.

Because :p2_A is not translated into ?, counted parameter.

[test_like_escape_char.zip](https://github.com/doctrine/doctrine2/files/2629523/test_like_escape_char.zip)

Tested on doctrine/dbal v 2.8.0 and 2.9.x-dev

**Comment by morozov** [comment] 2018-12-01 16:55
The problem seems to be in `SQLParserUtils::expandListParameters()` which considers `\` an escaping character regardless of the platform, however it's only true for MySQL.

**Comment by morozov** [comment] 2021-10-30 17:24
This must have been fixed by https://github.com/doctrine/dbal/pull/4397, no longer reproducible on `3.1.x`. In the ANSI mode, the query in question is parsed as:
```sql
SELECT NAME FROM DOCUMENT
WHERE (ID_FLDR_DOCU = {:folder_id})			
	AND (NAME LIKE {:p1_NAME} ESCAPE '\')
	AND (
		(A = {:p2_A})		
		OR (
			B IS NULL
			OR B = ''
			)
		)
	AND (
		C IS NOT NULL
		AND C <> ''
		)		
ORDER BY NAME ASC OFFSET 0 ROWS
FETCH NEXT 5 ROWS ONLY
```
The curly braces identify what has been recognized as a parameter (see `Doctrine\DBAL\Tests\SQL\ParserTest#testAnsiEscaping()`).

**Closed by morozov** 2021-10-30 17:24 UTC
Labels: Bug, SQL Server, Prepared Statements
