### ISSUE TITLE
Problem with connect to ProxySql

### ISSUE THREAD

**Issue by Smolevich** [doctrine/dbal#3557] opened 2019-05-24 06:14 UTC
|    Q        |   A
|------------ | -----
| Version     | 2.5.13

### Support Question

I try to connect to ProxySql (Percona XtraDB Cluster Operator 1.1.0) and got error `Doctrine\DBAL\DBALException: "Invalid platform version "Percona XtraDB Cluster Operator 1.1.0" specified. The platform version has to be specified in the format: "<major_version>.<minor_version>.<patch_version>".` Is it expected behavior?

**Comment by morozov** [comment] 2019-05-24 16:36
Yes, because the version doesn't match the expected format. You should be able to override the server version or specify a custom platform in [connection parameters](https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/configuration.html#automatic-platform-version-detection).

**Comment by Smolevich** [comment] 2019-05-24 17:42
I should set serverVersion equal to `Percona XtraDB Cluster Operator 1.1.0` that turn off database version detection?

**Comment by morozov** [comment] 2019-05-24 18:56
No, you should set it to the MySQL version which the operator runs internally.

**Comment by Smolevich** [comment] 2019-05-24 19:42
Version 5.7 was setted, but this method  in [Driver](https://github.com/doctrine/dbal/blob/2.5/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php#L123) get argument `version` equal to `Percona XtraDB Cluster Operator 1.1.0`

**Comment by morozov** [comment] 2019-05-24 20:51
It doesn't sound right. Please provide a test script to reproduce the issue.

**Comment by Smolevich** [comment] 2019-05-24 21:52
```
$host = 'proxysql.localhost';
$password = 'pass';
$username = 'usernamel';
$db = 'database';

$config = new \Doctrine\DBAL\Configuration();

$connectionParams - [
    'dbname' => $db,
    'user' => $username,
    'password' => $password,
    'host' => $host,
    'driver' => 'pdo_mysql'
];

$conn = \Doctrine\DBAL\DriverManager::getConnection($connectionParams, $config);

var_dump($conn->getDatabasePlatform());
```
throw exception `Uncaught Doctrine\DBAL\DBALException: Invalid platform version "Percona XtraDB Cluster Operator 1.1.0" specified. The platform version has to be specified in the format: "<major_version>.<minor_version>.<patch_version>".`

**Comment by morozov** [comment] 2019-05-25 01:54
You should set the server version in connection parameters.

**Comment by Smolevich** [comment] 2019-05-25 05:57
Using version `1.1.0` works for me, how can turn I off database detection? Maybe I should to use special value for `serverVersion`?

**Comment by ostrolucky** [comment] 2019-06-06 14:15
`server_version: 5.6` works for us in combination with Percona. This looks like a problem of your configuration. Please consult some support channels. As this is a bug tracker, we cannot provide appropriate support for these kind of questions. Hence closing. Thanks for understanding.

**Closed by ostrolucky** 2019-06-06 14:15 UTC
Labels: MySQL, Platform Detection, Question
