### ISSUE TITLE
Flush an object with NULL values in LOB fields leads to an error, OCI8

### ISSUE THREAD

**Issue by eisberg** [doctrine/dbal#5359] opened 2022-04-22 17:57 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| ORM Version     | 2.11.2 
| DBAL Version     | 3.3.3  
| Database Driver| Oracle, OCI8
| PHP | 8.1.3 

Link to issue in "ORM" repository:  [#9601](https://github.com/doctrine/orm/issues/9601)

#### Summary

When working with optional fields in entity that have a BLOB type (blob, clob, text, ..., etc.), we get a warning:

`Deprecated: OCILob::writeTemporary(): Passing null to parameter #1 ($data) of type string is deprecated in vendor/doctrine/dbal/src/Driver/OCI8/Statement.php on line 76`
 
The error occurs when working with Oracle (OCI8)

#### How to reproduce

```xml
<?xml version="1.0" encoding="utf-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping https://www.doctrine-project.org/schemas/orm/doctrine-mapping.xsd">
  <entity name="ExampleProcess" table="JOB_PROCESS">
    <id name="id" type="integer" column="id">
      <generator strategy="SEQUENCE"/>
      <sequence-generator sequence-name="PROCESS_ID_SEQ" allocation-size="1" initial-value="1"/>
    </id>
    <field name="response" type="blob" column="response" nullable="true"></field>
  </entity>
</doctrine-mapping>
```

```php
<?php

class ExampleProcess
{
    private int $id;
    /**
     * @var null|string|resource
     */
    private $response;  // << optional field

    public function getId(): int
    {
        return $this->id;
    }
 

    public function getResponse(): string|null
    {
        if (\is_resource($this->response)) {
            return (string) stream_get_contents($this->response);
        }

        return $this->response ?? null;
    }

    public function setResponse(string|null $response): self
    {
        $this->response = $response;

        return $this;
    }
 
}

```

Example:

```php
<?php

$test = new ExampleProcess();
$em->persist($test);
$em->flush(); // this will trigger a warning

$test2 = new ExampleProcess();
$test2->setResponse(null);
$em->persist($test2);
$em->flush(); // this will trigger a warning

// unwanted code that allows you to temporarily bypass the problem:
$test3 = new ExampleProcess();
$test3->setResponse("");
$em->persist($test3);
$em->flush(); // this will work fine

```
 
#### Expected behavior

Optional fields are expected to allow NULL values

**Comment by morozov** [comment] 2022-04-24 22:13
After attempting to fix it, I believe the current behavior is by design: if a null value is attempted to be bound to the statement, it should be bound as `ParameterType::NULL`, not `ParameterType::LARGE_OBJECT`. It looks like it needs to be fixed in the ORM which unconditionally derives the parameter type from the column type.

**Comment by morozov** [comment] 2022-04-24 22:17
@derrabus do you believe this issue should be moved to the ORM repository?

**Comment by derrabus** [comment] 2022-04-24 22:43
There is doctrine/orm#9601 already.

**Comment by morozov** [comment] 2022-04-25 05:22
Then I’ll close this. I don’t think anything needs to be changed in the DBAL in this regard.

**Comment by fabacino** [comment] 2022-06-23 10:03
Passing a value of `null` with `ParameterType::NULL` works fine on Oracle but breaks compatibility with SQLServer, at least on my end
```
Implicit conversion from data type varchar(max) to varbinary(max) is not allowed.
Use the CONVERT function to run this query.
```
Passing `null` as `ParameterType::LARGE_OBJECT` on the other hand works fine on SQLServer but causes the error mentioned in this issue on Oracle.

So if you need to support both of these platforms, I think there currently is no consistent way to set `null` into a blob column.

---

I have not found a way to pass `null` into `sqlsrv_prepare` as a literal value (instead of a four-element array containing parameter information) for blob columns. I assume this would imply that values *have* to be passed as `ParameterType::LARGE_OBJECT`, otherwise the [SqlSrv statement](https://github.com/doctrine/dbal/blob/3.3.x/src/Driver/SQLSrv/Statement.php#L183) cannot know whether the column is of blob type or not.

What I did find though is that skipping the creation of the LOB descriptor in case `null` is passed in [OCI8 statement](https://github.com/doctrine/dbal/blob/3.3.x/src/Driver/OCI8/Statement.php#L74) seems to fix the problem. I can PR if this is a feasible solution.

**Comment by morozov** [comment] 2022-06-23 15:38
> Passing a value of `null` with `ParameterType::NULL`[...] breaks compatibility with SQLServer, at least on my end
> 
> ```
> Implicit conversion from data type varchar(max) to varbinary(max) is not allowed.
> Use the CONVERT function to run this query.
> ```

Could you provide a reproducer for that? How does passing `null` cause the conversion from varchar(max) to varbinary(max)?

> What I did find though is that skipping the creation of the LOB descriptor in case null is passed in [OCI8 statement](https://github.com/doctrine/dbal/blob/3.3.x/src/Driver/OCI8/Statement.php#L74) seems to fix the problem. I can PR if this is a feasible solution.

For now, it still sounds like a workaround. Why would one need to bind null as a LOB if they know it's null?

**Comment by fabacino** [comment] 2022-06-24 12:41
> Could you provide a reproducer for that? How does passing null cause the conversion from varchar(max) to varbinary(max)?

Sure, executing the following code gives me the implicit conversion error
```php
$connection = \Doctrine\DBAL\DriverManager::getConnection([
    'driver' => 'sqlsrv',
    'user' => 'guest',
    'password' => 'hidden',
    'host' => 'localhost',
    'dbname' => 'tests',
    'charset' => 'UTF-8',
]);

$schemaManager = $connection->createSchemaManager();
$table = $schemaManager->createSchema()->createTable('files');
$table->addColumn('id', 'integer');
$table->addColumn('payload', 'blob', ['notnull' => false]);
$schemaManager->createTable($table);

$connection->createQueryBuilder()
    ->insert('files')
    ->values([
        'id' => ':id',
        'payload' => ':payload',
    ])
    ->setParameter('id', 1, ParameterType::INTEGER)
    ->setParameter('payload', null, ParameterType::NULL)
    ->executeStatement();
```

If the parameter type is changed to `LARGE_OBJECT` however, everything works fine
```php
    //->setParameter('payload', null, ParameterType::NULL)
    ->setParameter('payload', null, ParameterType::LARGE_OBJECT)
```

---

> For now, it still sounds like a workaround. Why would one need to bind null as a LOB if they know it's null?

Let me share my use case. In our application, we use record and table classes for (further) database abstraction which might look something like this for the table used above.
```php
class FileRecord
{
    public function __construct(
        private int $id,
        private ?string $payload
    ) {
    }

    public function id(): int
    {
        return $this->id;
    }

    public function payload(): ?string
    {
        return $this->payload;
    }
}
```
```php
class FilesTable
{
    public function insert(FileRecord $record): void
    {
        $connection->createQueryBuilder()
            ->insert('files')
            ->values([
                'id' => ':id',
                'payload' => ':payload',
            ])
            ->setParameter('id', $record->id(), ParameterType::INTEGER)
            ->setParameter('payload', $record->payload(), ParameterType::LARGE_OBJECT)
            ->executeStatement();
    }
}
```

Inside the `insert()` method, the actual value for the payload column i.e. whether it's `null` or not, is not of real importance because we know that `$record->payload()` returns a valid value for the column. We *could* check for `null` and pass a different parameter type of course, but the code is much simpler if we don't have to. 

This being said, even though I consider treating `null` as a special case by the caller unnecessary work, I wouldn't mind doing that.
My issue is that I currently have to do some kind of platform check because there is no uniform way that works on both Oracle and SQLServer *regardless* whether `ParameterType::NULL` or `ParameterType::LARGE_OBJECT` is considered the "right" way to set `null` into a blob column. Either way I am stuck with one of these workarounds
```php
if ($connection->getDatabasePlatform() instanceof SQLServerPlatform) {
    // ParameterType::NULL raises a conversion error.
    $connection->setParameter('payload', null, ParameterType::LARGE_OBJECT);
} else {
    $connection->setParameter('payload', null, ParameterType::NULL);
}
```
```php
if ($connection->getDatabasePlatform() instanceof OraclePlatform) {
    // ParameterType::LARGE_OBJECT raises a PHP warning.
    $connection->setParameter('payload', null, ParameterType::NULL);
} else {
    $connection->setParameter('payload', null, ParameterType::LARGE_OBJECT);
}
```
which I think the DBAL library could take care of for me.

**Comment by morozov** [comment] 2022-06-24 17:45
> Sure, executing the following code gives me the implicit conversion error

Thanks, I can reproduce the issue. I believe the error message that this scenario produces implies that we're binding the value for a BLOB (`VARBINARY(max)`) column as TEXT (`VARCHAR(max)`):

> Implicit conversion from data type varchar(max) to varbinary(max) is not allowed. Use the CONVERT function to run this query.

This may be a separate issue in the DBAL drivers for SQL Server. Specifically, the `sqlsrv` driver doesn't support any special handling for `ParameterType::NULL` and defaults to binding the value as a string: https://github.com/doctrine/dbal/blob/33ffa53e18ffd22ead94eb6a9aa8f0c4a320b22a/src/Driver/SQLSrv/Statement.php#L151-L180

Interestingly, the same problem is reproducible with `pdo_sqlsrv` which seems to implement the proper binding: https://github.com/doctrine/dbal/blob/bf72469d40439b3a97a8d973323e383d38afa406/src/Driver/PDO/Statement.php#L22

But it's still possible that either:

1. There is a bug that makes `pdo_sqlsrv`DBAL driver bind `ParameterType::NULL` as something different.
2. The `pdo_sqlsrv` extension itself doesn't handle it properly.

Note that the following expresion works just fine, so there should be a way to insert NULL into a nullable `VARBINARY(max)` column without any conversion:
```sql
INSERT INTO files(id, payload) VALUES(1, NULL);
```

I'll try debugging the drivers to get more details.

**Comment by morozov** [comment] 2022-06-24 22:32
From the `pdo_sqlsrv` [documentation](https://docs.microsoft.com/en-us/sql/connect/php/pdostatement-bindparam?view=sql-server-ver16#remarks) (I believe, the same applies to `sqlsrv`):

> When binding null data to server columns of type varbinary, binary, or varbinary(max) you should specify binary encoding (`PDO::SQLSRV_ENCODING_BINARY`) using the `$driver_options`.

So it sounds like the DBAL has to take care of binding NULL values for different column types.

**Comment by morozov** [comment] 2022-06-25 02:31
@fabacino please see if https://github.com/doctrine/dbal/pull/5466 fixes the issue for you.

**Closed as completed** 2022-06-26 15:26 UTC
Labels: oci8, Prepared Statements

**Comment by fabacino** [comment] 2022-06-27 08:51
> please see if #5466 fixes the issue for you.

It does, thank you very much for addressing this so quickly!
