### ISSUE TITLE
Caching not improving execution time at all

### ISSUE THREAD

**Issue by userfriendly** [doctrine/dbal#2563] opened 2016-11-29 14:24 UTC
Hi there,

I've got a bit of a weird issue with Doctrine/DBAL and caching, in that execution time is the same time for both a cache miss and cache hit.

See example script at http://pastie.org/10972484

I've checked both Doctrine\DBAL\Connection::executeCacheQuery() for cache hit and my Memcached store for the key during 2nd execution, but there is no improvement in execution time for the cache hit.

Caching the resultset manually works as expected, but I would much prefer letting Doctrine handle the caching (and more importantly, the cache invalidation).

Any ideas?

**Comment by Ocramius** [comment] 2016-12-04 06:52
Since I don't trust external links to stay the same, here's the issue:

```php
<?php

namespace Cisco\FsatBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Doctrine\Common\Cache\MemcachedCache;
use Doctrine\DBAL\Cache\QueryCacheProfile;
use Doctrine\DBAL\Connection;

/*
 * Issue is that there seems to be no benefit in letting
 * Doctrine/DBAL cache the result: execution time for the
 * example script below, this->executeLetDoctrineCache(),
 * is the exact same for cache miss and cache hit, about
 * 12 seconds.
 * 
 * Cache hit is confirmed by checking the relevant
 * conditional statement in
 * Doctrine\DBAL\Connection::executeCacheQuery()
 * and by checking that Memcached holds the resultset.
 * 
 * Caching manually however does work as expected as per
 * $this->executeUseCacheManually(), in that the first
 * execution takes 9 seconds (cache miss) and the 2nd
 * execution (cache hit) takes 4 seconds.
 */
class CacheTestCommand extends ContainerAwareCommand
{
    protected $memoryInUse;
    protected $timeAtStart;

    public function __construct()
    {
        parent::__construct();
        $this->memoryInUse = memory_get_usage();
        $this->timeAtStart = microtime( true );
    }

    public function configure()
    {
        $this->setName( 'cisco:cache:test' )->setDescription( 'Test Doctrine Memcached execution time.' );
    }

    public function execute( InputInterface $input, OutputInterface $output )
    {
        $this->executeRunPlainMysqli( $input, $output );
        //$this->executeLetDoctrineCache( $input, $output );
        //$this->executeUseCacheManually( $input, $output );
    }

    /*
     * Run native SQL through plain mysqli to see what the Doctrine/DBAL overhead is
     * 
     * Takes about 1.8 seconds, more or less the same as via MySQL shell client
     */
    public function executeRunPlainMysqli( InputInterface $input, OutputInterface $output )
    {
        $this->profile( $output );
        $sql = 'SELECT r.id, r.case_id, r.feedback, r.summarise, r.wish, r.survey_started_at, r.created_at, c.* FROM fsat__result r LEFT JOIN salesforce__case c ON c.id = r.case_id WHERE r.survey_started_at LIKE "201%" LIMIT 100000;';
        $db = new \mysqli( 'localhost', 'root', '', 'vecloud' );
        $result = $db->query( $sql );
        $this->profile( $output, "MySQLi returns " . $result->num_rows . " rows" );
    }

    /*
     * Let Doctrine/DBAL handle the caching itself
     * Preferred solution that sadly doesn't work as expected
     * 
     * For both cache miss and cache hit execution time is ~12 seconds
     */
    public function executeLetDoctrineCache( InputInterface $input, OutputInterface $output )
    {
        $this->profile( $output );
        $memcached = new \Memcached();
        $memcached->addServer('localhost', 11211);
        $cacheDriver = new MemcachedCache();
        $cacheDriver->setMemcached( $memcached );
        $em = $this->getContainer()->get( 'doctrine' )->getManager();
        $conn = $em->getConnection();
        $this->profile( $output, "Connection obtained" ); // 0.05 seconds

        $config = $conn->getConfiguration();
        $config->setResultCacheImpl( $cacheDriver );
        $qb = $conn->createQueryBuilder();
        $qb->select( "r.id, r.case_id, r.feedback, r.summarise, r.wish, r.survey_started_at, r.created_at, c.*" );
        $qb->from( "fsat__result", "r" );
        $qb->leftJoin( "r", "salesforce__case", "c", "c.id = r.case_id" );
        $andCond = $qb->expr()->andx();
        $andCond->add( $qb->expr()->like( "r.survey_started_at", ":date1" ));
        $qb->andWhere( $andCond );
        $qb->setMaxResults( 100000 );
        $sql = $qb->getSql();
        $this->profile( $output, "Query built" ); // 0.06 seconds

        $stmt = $conn->executeQuery(
                    $sql,
                    array( "date1" => "201%" ),
                    array( Connection::PARAM_INT_ARRAY ),
                    new QueryCacheProfile( 0, "FooBaa" )
                );
        $result = $stmt->fetchAll();
        $stmt->closeCursor();
        $this->profile( $output, "Result contains " . count( $result ) . " rows" );
    }

    /*
     * Run Doctrine/DBAL on its own, then cache manually - works
     * as expected, but would be a last resort solution only
     * 
     * Takes ~9 seconds to execute the 1st time, then ~4 seconds
     * the 2nd time when the result comes from the cache
     */
    public function executeUseCacheManually( InputInterface $input, OutputInterface $output )
    {
        $this->profile( $output );
        $memcached = new \Memcached();
        $memcached->addServer( "localhost", 11211 );
        $em = $this->getContainer()->get( 'doctrine' )->getManager();
        $conn = $em->getConnection();
        $this->profile( $output, "Connection obtained" ); // 0.05 seconds

        $qb = $conn->createQueryBuilder();
        $qb->select( "r.id, r.case_id, r.feedback, r.summarise, r.wish, r.survey_started_at, r.created_at, c.*" );
        $qb->from( "fsat__result", "r" );
        $qb->leftJoin( "r", "salesforce__case", "c", "c.id = r.case_id" );
        $andCond = $qb->expr()->andx();
        $andCond->add( $qb->expr()->like( "r.survey_started_at", ":date1" ));
        $qb->andWhere( $andCond );
        $qb->setMaxResults( 100000 );
        $sql = $qb->getSql();
        $this->profile( $output, "Query built" ); // 0.05 seconds

        $result = $memcached->get( "Foo" );
        if ( !$result )
        {
            echo $output->writeln( '<error>Data is NOT in cache</error>' );

            $stmt = $conn->executeQuery(
                        $sql,
                        array( "date1" => "201%" ),
                        array( Connection::PARAM_INT_ARRAY )
                    );
            $result = $stmt->fetchAll();
            $memcached->set( "Foo", $result );
        }
        else echo $output->writeln( '<info>Data is in cache</info>' );
        $this->profile( $output, "Result contains " . count( $result ) . " rows" );
    }

    protected function profile( OutputInterface $output, $label = "" )
    {
        $memUsed = ceil(( memory_get_usage() - $this->memoryInUse ) / ( 1024 * 1024 ));
        $time = round( microtime( true ) - $this->timeAtStart, 3 );
        $output->writeln( '<comment>##### ' . ( $label ? $label . ': ' : ' ' ) . 'Memory in use: ' . $memUsed . ' MB, time running: ' . $time . ' seconds #####</comment>' );
    }
}
```

**Comment by Ocramius** [comment] 2016-12-04 06:54
@userfriendly where's the time wasted here? Is caching being too slow? Is producing the cache key too slow? Can this be generalized into two reproducible benchmarks?

**Comment by userfriendly** [comment] 2016-12-05 12:53
Generating the key takes barely a millisecond, if that. In the above example, retrieving the data from the cache takes over 4 seconds. Here is the debug output with some additional var_dump() lines from Connection:executeCacheQuery() if that helps:

## 1st execution (cache miss)
```
#####  Memory in use: 2 MB, time running: 0.018 seconds #####
##### Connection obtained: Memory in use: 6 MB, time running: 0.048 seconds #####
##### Query built: Memory in use: 7 MB, time running: 0.055 seconds #####
string(52) "### Connection::executeCacheQuery() has been called."
string(87) "### Connection::executeCacheQuery() has obtained result cache instance after 0 seconds."
string(76) "### Connection::executeCacheQuery() has generated cache key after 0 seconds."
string(26) "Cache miss for key Foo"
string(80) "### Connection::executeCacheQuery() returns statement object after 1.72 seconds."
##### Result contains 100000 rows: Memory in use: 1614 MB, time running: 12.349 seconds #####
```

## 2nd execution (cache hit)
```
#####  Memory in use: 2 MB, time running: 0.018 seconds #####
##### Connection obtained: Memory in use: 6 MB, time running: 0.049 seconds #####
##### Query built: Memory in use: 7 MB, time running: 0.056 seconds #####
string(52) "### Connection::executeCacheQuery() has been called."
string(87) "### Connection::executeCacheQuery() has obtained result cache instance after 0 seconds."
string(76) "### Connection::executeCacheQuery() has generated cache key after 0 seconds."
string(86) "### Connection::executeCacheQuery() has retrieved data from cache after 4.272 seconds."
string(81) "### Connection::executeCacheQuery() returns statement object after 4.272 seconds."
##### Result contains 100000 rows: Memory in use: 1614 MB, time running: 12.316 seconds #####
```

**Comment by userfriendly** [comment] 2016-12-05 12:55
So basically the time saved by not executing the statement during the 2nd run is lost again by getting the result from the cache. :(

**Comment by Ocramius** [comment] 2016-12-05 13:44
@userfriendly can you try profiling with XDebug? Maybe it's looping over results in the cache? Maybe slow cache adapter? What if you use an array cache?

**Comment by userfriendly** [comment] 2016-12-05 14:28
By cache adapter you mean the sort of cache used? It's memcached, set as per the documentation in Symfony's config.yml file. Usually that's reasonably fast (as evidenced by the example script when caching manually).

Never used xdebug, what are you looking for here? I'm afraid I don't know the Doctrine internals well enough to say what it's doing with the cache. All I know is when I don't let Doctrine handle the caching it's a lot faster compared to both cache miss and cache hit with Doctrine.

**Comment by Ocramius** [comment] 2016-12-05 14:32
Running the script through xdebug's profiler (just needs a flag) can
produce a cachegrind file that you can send me (via mail, possibly
encrypted, since it may contain sensitive data) that I can look at for slow
or repeated method calls

**Comment by userfriendly** [comment] 2016-12-05 14:55
Sorry, like I said, never used it, and all the xdebug HOWTOs I've found are pages long explanation how to use xdebug with an IDE. How do I use it with just a shell command? The script above is a Symfony CLI command.

**Comment by userfriendly** [comment] 2016-12-05 15:22
Okay, I think I've sort of managed to find out how to run the example script through xdebug. However, it doesn't seem to generate a lot of info, the log file it generates is 790 bytes and seems to have nothing useful in it.

**Comment by userfriendly** [comment] 2016-12-05 15:32
> just needs a flag

What do you mean by that?

**Comment by userfriendly** [comment] 2016-12-05 15:43
Never mind, apparently xdebug's debugger and xdebug's profiler are two separate things, I had to enable the latter. Now I've got an 8.5MB cachegrind file.

**Comment by Ocramius** [comment] 2016-12-05 17:58
Well there's your problem: 
<img width="859" alt="f7d027" src="https://cloud.githubusercontent.com/assets/154256/20896115/7b96649c-bb1c-11e6-9657-d2e570476439.png">

Caused by [`ArrayStatement#fetchAll()`](https://github.com/doctrine/dbal/blob/b551fcb26a81e230085c0dca88174573b6c36609/lib/Doctrine/DBAL/Cache/ArrayStatement.php#L125), which indeed does not take advantage of [multi-get](https://github.com/doctrine/cache/blob/9fa5962201c8b69cb68d091bfa6a77e92e2a3559/lib/Doctrine/Common/Cache/MultiGetCache.php) and [multi-put](https://github.com/doctrine/cache/blob/9fa5962201c8b69cb68d091bfa6a77e92e2a3559/lib/Doctrine/Common/Cache/MultiPutCache.php) caches. 

This indeed leaves space for improvement... A lot of improvement.

**Comment by Ocramius** [comment] 2016-12-05 22:27
@userfriendly this has to be fixed in DBAL. I already got [word out, asking for helpers](https://twitter.com/Ocramius/status/805838099754483712)

**Comment by userfriendly** [comment] 2016-12-05 23:02
Ace, thank you for looking into this, much appreciated.

**Comment by Federkun** [comment] 2016-12-07 19:47
@Ocramius, when `ArrayStatement`'s `fetchAll()` is called, the data isn't already in-memory? From what I've seen, all the data is stored using single key (without using MultiGetCache and MultiPutCache).

**Comment by userfriendly** [comment] 2016-12-08 11:40
> However, such an amount of data must take some time anyway.

You're right. Although it would be pretty nice if the time it takes mirrored more closely the manual caching in the example script above, which - given the amount of data - is reasonably low.

This is obviously just a stripped down example, a lot of our queries and resultsets are a fair bit bigger, but if we can trim down a response time from 12 to 4 seconds that'd be grand.

**Comment by Ocramius** [comment] 2016-12-08 13:22
Check https://github.com/doctrine/dbal/pull/682 for ideas, please. Obviously, everything in one shot is not a good idea.

**Comment by Federkun** [comment] 2016-12-09 13:29
Yesterday I tried to break large object (~1GB of data) into smaller item (chunk of 1000, 5000, 10000 and 20000), and cache them using multiple keys. I didn't notice any significant improvements on writing and reading using memcached and redis.
The only benefit is that it's easier to store a large object graph without fine-tune memcache/redis & co., e.g: increment the max memory limit per item.
It should be possible to improve the reading performance by reading the cache a little at a time when `ArrayStatement` is iterated, but since the most common case is to `fetchAll` it would be futile to do that.

However, strangely,  the problem of @userfriendly doesn't seems have something to do with the time that the data take to be read from the cache, but that it take almost 50% of the time to just iterate an array with `ArrayStatement::fetchAll()`. I don't know why, here's my benchmarks:

```
php5
 
    --- cache miss
 
    ##### Memory in use: 1 MB, time running: 0 seconds #####
    ##### Connection obtained: Memory in use: 1 MB, time running: 0.001 seconds #####
    ##### Query built: Memory in use: 1 MB, time running: 0.001 seconds #####
    ##### Result contains 104146 rows: Memory in use: 880 MB, time running: 6.848 seconds #####
 
    --- cache hit
 
    ##### Memory in use: 1 MB, time running: 0.001 seconds #####
    ##### Connection obtained: Memory in use: 1 MB, time running: 0.001 seconds #####
    ##### Query built: Memory in use: 1 MB, time running: 0.001 seconds #####
    ##### Result contains 104146 rows: Memory in use: 880 MB, time running: 2.537 seconds #####
 
php7.1
 
    --- cache miss
 
    ##### Memory in use: 1 MB, time running: 0 seconds #####
    ##### Connection obtained: Memory in use: 1 MB, time running: 0 seconds #####
    ##### Query built: Memory in use: 1 MB, time running: 0.001 seconds #####
    ##### Result contains 104146 rows: Memory in use: 1266 MB, time running: 7.064 seconds #####
 
    --- cache hit
 
    ##### Memory in use: 1 MB, time running: 0 seconds #####
    ##### Connection obtained: Memory in use: 1 MB, time running: 0 seconds #####
    ##### Query built: Memory in use: 1 MB, time running: 0.001 seconds #####
    ##### Result contains 104146 rows: Memory in use: 1272 MB, time running: 1.134 seconds #####
```

and `ArrayStatement::fetchAll` is relatively fast. If you want I can provide you my docker container.

**Comment by patrick-mcdougle** [comment] 2016-12-12 05:42
Not sure if it's helpful or not, but some versions of Memcached has a biggest object size of 1MB. If the object is bigger than that, memcached is going to reject it. Is it possible that's what's happening? Can you call memcache directly to see if your data is there after it populates the cache?

**Comment by userfriendly** [comment] 2017-01-04 22:42
No, that's not it - at the beginning of my tests I configured Memcached with the appropriate settings for the data. It stores the data just fine, both when used manually (as seen in my example script) and when used by Doctrine. And yes, I also double-checked by doing precisely what you suggest, i.e. checking if the key is actually in Memcached.

**Comment by userfriendly** [comment] 2017-02-14 17:25
Guys, any news on this? Much appreciated. :) Cheers!

**Comment by Ocramius** [comment] 2017-02-16 19:19
@userfriendly unless you attempted a patch, I don't see any mention of PRs working on this :-)

**Comment by userfriendly** [comment] 2017-02-16 19:37
Ehh ... I wouldn't even know where to start.

**Comment by patrick-mcdougle** [comment] 2017-02-22 03:47
Is it possible that your environment is under memory pressure and is paging some of the memcached pages out to disk?

**Comment by userfriendly** [comment] 2017-02-22 12:38
Patrick, please check the previous comments in this conversation - the issue is with DBAL, not with my environment (which has 32GB of memory, btw).

**Closed** 2021-12-30 18:39 UTC
Labels: mysqli, Cache, Question, Performance
