### ISSUE TITLE
SQLServerPlatform::scrubInnerOrderBy() enters infinite loop

### ISSUE THREAD

**Issue by BenjaminNolan** [doctrine/dbal#2313] opened 2016-02-05 22:57 UTC
Not sure if this is an issue specific to 5.6, but that's all I've had time to test it in. (Sorry!) Wouldn't have noticed it were it not for the `String offset cast occurred` notice appearing hundreds of thousands of times in my PHP logs. :)

`Doctrine\DBAL\Platforms\SQLServerPlatform::scrubInnerOrderBy()` has a bug in it where it enters an infinite loop after `stripos()` returns `false` if the string `ORDER BY` is not present after the last `)` found at `$currentPosition`.

When it runs on the following query, it enters an infinite loop and never exits:

> `SELECT DISTINCT TOP 30 id_1, MIN(sclr_6) AS dctrn_minrownum FROM (SELECT q0_.available_at AS available_at_0, q0_.id AS id_1, q0_.is_active AS is_active_2, q0_.is_deleted AS is_deleted_3, q0_.created_at AS created_at_4, q0_.last_updated_at AS last_updated_at_5, ROW_NUMBER() OVER(ORDER BY q0_.created_at ASC) AS sclr_6 FROM ThisIsASquirrel q0_ WHERE (q0_.is_deleted = 0 AND q0_.is_active = 1) AND (q0_.is_deleted = 0)) dctrn_result GROUP BY id_1 ORDER BY dctrn_minrownum ASC`

Adding a check for $orderByPos === false and then breaking out allows the code to continue successfully.

**Comment by kokspflanze** [comment] 2016-03-26 20:29
hi,

i had the bug too, i fix it in https://github.com/doctrine/dbal/pull/2341

the problem is "OVER(ORDER BY q0_.created_at ASC)" in your query.

https://github.com/doctrine/dbal/blob/v2.5.4/lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php#L1222 count the number of "ORDER BY" and https://github.com/doctrine/dbal/blob/v2.5.4/lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php#L1227 search for " ORDER BY"

**Comment by morozov** [comment] 2021-10-30 21:26
Closing as irrelevant as of https://github.com/doctrine/dbal/pull/3756.

**Closed by morozov** 2021-10-30 21:26 UTC
