### ISSUE TITLE
High memory usage of preg_match_all() in SQLParserUtils::collectPlaceholders()

### ISSUE THREAD

**Issue by sgrossberndt** [doctrine/dbal#4261] opened 2020-09-08 15:18 UTC
### Bug Report

When executing a lot of queries (6.000+ in my case) with one named parameter each this leads to a very high memory usage (250MB in my case in one request) due to the `preg_match_all()` statement in the `SQLParserUtils::collectPlaceholders()` method. When using positional parameters for the query instead this high memory usage does not happen.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.2

#### How to reproduce

|    Product        |   Version
| ------------ | ------
PHP | `7.2.33-1+0~20200807.47+debian9~1.gbpcb3068`
PCRE Library | `8.43 2019-02-23`

```
CREATE TABLE tx_my_x_y_mm (
 uid_local int(10) unsigned NOT NULL DEFAULT '0',
 uid_foreign int(10) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY uid_local (uid_local,uid_foreign),
 KEY uid_foreign (uid_foreign)
);

CREATE TABLE tx_my_y (
 uid int(10) unsigned NOT NULL auto_increment,
 deleted tinyint(3) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (uid)
);
```

Execute many queries with one named parameter and profile the memory usage
```
SELECT "tx_my_x_y_mm".*, "tx_my_y".*
FROM "tx_my_x_y_mm" "tx_my_x_y_mm"
LEFT JOIN "tx_my_y" "tx_my_y" ON "tx_my_x_y_mm"."uid_foreign" = "tx_my_y"."uid"
WHERE ("tx_my_x_y_mm"."uid_local" = :dcValue1) AND (("tx_my_y"."deleted" = 0) OR ("tx_my_y"."uid" IS NULL)) AND ("tx_my_y"."deleted" = 0)
ORDER BY "tx_my_x_y_mm"."sorting" ASC
```

Exceute many queries with one positional parameter and profile the memory usage
```
SELECT "tx_my_x_y_mm".*, "tx_my_y".*
FROM "tx_my_x_y_mm" "tx_my_x_y_mm"
LEFT JOIN "tx_my_y" "tx_my_y" ON "tx_my_x_y_mm"."uid_foreign" = "tx_my_y"."uid"
WHERE ("tx_my_x_y_mm"."uid_local" = ?) AND (("tx_my_y"."deleted" = 0) OR ("tx_my_y"."uid" IS NULL)) AND ("tx_my_y"."deleted" = 0)
ORDER BY "tx_my_x_y_mm"."sorting" ASC
```

Compare the memory usages and you see a huge difference due to the `preg_match_all`

#### Expected behaviour

Memory usage it much lower although named parameters are used.

**Comment by greg0ire** [comment] 2020-09-08 17:42
Link for the lazy: https://github.com/doctrine/dbal/blob/ce85bd8719b18b61c3171f3324df281c7716aec4/lib/Doctrine/DBAL/SQLParserUtils.php#L106-L126

**Comment by morozov** [comment] 2020-09-08 19:08
Given that the query being processed is relatively small and the fact that the issue is reproducible at a certain scale, it looks like a memory leak.

@sgrossberndt could you provide a script that could be used to reproduce this high memory usage?

**Comment by sgrossberndt** [comment] 2020-09-09 07:20
```php
<?php

$parameterTypeForQueryBuilder = 'createNamedParameter';

if ($parameterTypeForQueryBuilder === 'createNamedParameter') {
	for ($uid = 1; $uid < 6000; $uid++) {
		$queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable('tx_my_y');
		$records = $queryBuilder
			->select('x.uid', 'mm.uid_foreign')
			->from('tx_my_x_y_mm', 'mm')
			->join('mm', 'tx_my_y', 'x', $queryBuilder->expr()->eq('x.uid', $queryBuilder->quoteIdentifier('mm.uid_local')))
			->where($queryBuilder->expr()->eq('x.uid', $queryBuilder->createNamedParameter($uid, Connection::PARAM_INT)))
			->orderBy('x.uid')
			->addOrderBy('mm.uid_foreign')
			->execute()
			->fetchAll();
		var_dump($records);
		// has a Excl. MemUse of 243 MB for preg_match_all() where 238MB are calls from Doctrine\DBAL\SQLParserUtils::getUnquotedStatementFragments
	}
} elseif ($parameterTypeForQueryBuilder === 'createPositionalParameter') {
	for ($uid = 1; $uid < 6000; $uid++) {
		$queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable('tx_my_y');
		$records = $queryBuilder
			->select('x.uid', 'mm.uid_foreign')
			->from('tx_my_x_y_mm', 'mm')
			->join('mm', 'tx_my_y', 'x', $queryBuilder->expr()->eq('x.uid', $queryBuilder->quoteIdentifier('mm.uid_local')))
			->where($queryBuilder->expr()->eq('x.uid', $queryBuilder->createPositionalParameter($uid, Connection::PARAM_INT)))
			->orderBy('x.uid')
			->addOrderBy('mm.uid_foreign')
			->execute()
			->fetchAll();
		var_dump($records);
	}
	// has a Excl. MemUse of 1,4 MB for preg_match_all() where 1,3 MB are calls from Doctrine\DBAL\SQLParserUtils::getUnquotedStatementFragments
}
```

Here are the xhprof profiles of both runs:
[createNamedParameters.doctrine_dbal.zip](https://github.com/doctrine/dbal/files/5193227/createNamedParameters.doctrine_dbal.zip) and [createPositionalParameters.doctrine_dbal.zip](https://github.com/doctrine/dbal/files/5193228/createPositionalParameters.doctrine_dbal.zip)

**Comment by norkunas** [comment] 2021-10-01 13:28
I'm also facing this memory leak when running a query in a long running process.. :disappointed:

**Comment by morozov** [comment] 2021-10-01 16:26
What DBAL version are you using? The SQL parser was completely reworked in 3.0.0 (https://github.com/doctrine/dbal/pull/4397).

**Comment by norkunas** [comment] 2021-10-03 11:43
I'm on 2.13 because orm blocks from upgrading to v3

**Comment by greg0ire** [comment] 2021-10-03 12:58
Currently trying to release 2.10.0, which will allow it :)
Follow my progress at https://github.com/doctrine/orm/pull/9061

**Comment by norkunas** [comment] 2021-10-03 13:11
But why it was not fixed in v2? :) The rework in my opinion was not a feature but a bugfix

**Comment by greg0ire** [comment] 2021-10-03 13:19
I don't know :man_shrugging: , and I'm not sure we should care if I can manage to release 2.10.0 (which is harder than it sounds)

**Comment by norkunas** [comment] 2021-10-04 07:19
doctrine/migrations is another blocker :)

**Comment by greg0ire** [comment] 2021-10-04 10:12
Feel free to work on either a fix or migration of `doctrine/migrations` (it's already underway)

**Comment by morozov** [comment] 2021-10-30 17:27
Closing as irrelevant as of https://github.com/doctrine/dbal/pull/4397.

**Closed by morozov** 2021-10-30 17:27 UTC
