### ISSUE TITLE
OFFSET and LIMIT values as query parameters 

### ISSUE THREAD

**Issue by alebedev80** [doctrine/dbal#6246] opened 2023-12-21 08:00 UTC
### Feature Request

SQL query LIMIT and OFFSET should use parameters instead of embedding values to the query. Because it's affect cache memory usage with cached queries

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no

#### Summary

More info and script which demonstrate the problem see [here](https://github.com/doctrine/orm/issues/11112).

**Comment by derrabus** [comment] 2023-12-21 08:51
Can you elaborate what kind of change you'd expect from DBAL? If the database does not forbid to use parameters in limit and offset, the DBAL doesn't either.

**Comment by greg0ire** [comment] 2023-12-21 09:22
I think we should look into reimplementing Platform:: 'modifyLimitQuery' with placeholders

**Comment by alebedev80** [comment] 2023-12-21 09:52
@derrabus i think SQL query should contain LIMIT/OFFSET values as parameters if DB supports them. If not supports then as now – embed values to SQL string.

**Comment by derrabus** [comment] 2023-12-21 10:12
> i think SQL query should contain LIMIT/OFFSET values as parameters

Okay, let me be more precise: What prevents you from doing this?

```php
$connection->executeQuery('SELECT my_col FROM my_table LIMIT ? OFFSET ?', [$myLimit, $myOffset]);
```

> if DB supports them. If not supports then as now – embed values to SQL string.

Can you elaborate how you expect this to look like? Also, please research which of the databases we support do allow parameters for limit and offset and which don't.

**Comment by alebedev80** [comment] 2023-12-21 10:34
> Okay, let me be more precise: What prevents you from doing this?

@derrabus I'm using Doctrine ORM and query builder with query cache. That change need to cache one query instead of millions (please see this [issue](https://github.com/doctrine/orm/issues/11112) for more explanation).

> Can you elaborate how you expect this to look like?

It should looks the same as with other parameters. Maybe need to use some 'system' keyword per that parameter names, e.g. `_doctrine_query_offset_` and `_doctrine_query_limit_` or whatever to prevent override user's parameters.


> Also, please research which of the databases we support do allow parameters for limit and offset and which don't.

All RDBMS from Doctrine's support list support parameterized LIMIT and OFFSET (strange that was not done initially). PDO also support it.

MySQL / MySQL57Platform / MySQL80Platform: MySQL supports parameterized LIMIT and OFFSET. You can use placeholders (like ?) in prepared statements.

MariaDB: Being a fork of MySQL, MariaDB also supports parameterized LIMIT and OFFSET in a similar fashion.

Oracle: Oracle uses ROWNUM or FETCH FIRST and OFFSET clauses, which can be parameterized in prepared statements.

Microsoft SQL Server / SQLServerPlatform: Supports parameterized OFFSET and FETCH NEXT (equivalent to LIMIT) in the ORDER BY clause, especially from SQL Server 2012 onwards.

PostgreSQL / PostgreSQLPlatform / PostgreSQL100Platform: PostgreSQL supports parameterized LIMIT and OFFSET. This functionality is consistent across the versions you mentioned.

IBM DB2 / Db2Platform: IBM DB2 supports parameterized LIMIT and OFFSET through the use of FETCH FIRST and OFFSET clauses in prepared statements.

SQLite: SQLite supports parameterized LIMIT and OFFSET.

**Comment by derrabus** [comment] 2023-12-21 10:58
> I'm using Doctrine ORM and query builder with query cache.

The ORM query builder is an ORM feature. The question is what needs to be changed in the DBAL.

> It should looks the same as with other parameters.

But that does work already, see me previous code exampe:

```php
$connection->executeQuery('SELECT my_col FROM my_table LIMIT ? OFFSET ?', [$myLimit, $myOffset]);
```

So what is it that you need additionally?

**Comment by greg0ire** [comment] 2023-12-21 11:27
The ORM uses modifyLimitQuery. If what you describe works across every platform, then a new API is not needed, and the ORM can use what you showed directly.

**Comment by alebedev80** [comment] 2023-12-21 11:37
> The ORM query builder is an ORM feature. The question is what needs to be changed in the DBAL.
Yes, but ORM caching a query by SQL query text hash. Right? Generated SQL is wrong because embed offset and limit values to the SQL text and per follow queries will be done THREE cache entries:

```
select * from foo where f = :field_val offset 0 limit 10;
select * from foo where f = :field_val offset 10 limit 10;
select * from foo where f = :field_val offset 20 limit 10;
```

instead of one:

```
select * from foo where f = :field_val offset : _doctrine_query_offset_ limit : _doctrine_query_limit_;
```

> But that does work already, see me previous code exampe:

or i should switch to pure PDO instead of Doctrine ORM?

@derrabus can you explain me current logic why limit|offset is embed strings instead of parameters?

**Comment by alebedev80** [comment] 2023-12-21 11:45
@derrabus and if SQL generatin in DBAL library then it should generate proper SQL. Why parameterized values better than embed value:


**Performance**:

Embedded Values: Each query with different embedded values is considered a new query by the database. This means the database needs to parse, compile, and optimize each query individually.
Parameterized Queries: They allow the database to reuse the execution plan for a query. Since the structure of the query remains constant, only the parameters change, which leads to better performance, particularly for queries executed multiple times with different values.

**Memory Usage and Efficiency:**

Embedded Values: This approach can lead to inefficient memory usage, especially if you have a lot of similar queries with only slight differences in values. It can also lead to bloat in the query cache of the database.
Parameterized Queries: They are more efficient in terms of memory usage because the database can cache a single prepared statement and execute it with different parameters. This reduces the memory footprint and can improve cache efficiency.


**Database Resource Utilization:**

Embedded Values: Can lead to higher CPU usage on the database server due to repeated parsing and compiling of similar queries.
Parameterized Queries: Reduce CPU load on the database server because the query is parsed and compiled once and then executed multiple times with different parameters.

**Comment by derrabus** [comment] 2023-12-21 11:52
> Why parameterized values better than embed value:

I don't need a lecture on prepared statements. I'm not arguing against your proposal, I'm trying to turn this into an actionable ticket and so far you haven't been helpful in that regard.

**Comment by derrabus** [comment] 2023-12-21 11:58
> The ORM uses modifyLimitQuery. If what you describe works across every platform, then a new API is not needed, and the ORM can use what you showed directly.

I see. And that method expects literal integers insetead of expressions. I mean, it should not matter much whether we insert an integer or a placeholder, the logic would be the same. Do you think we should widen the parameters of that method or rather add a new method for this purpose?

**Comment by greg0ire** [comment] 2023-12-21 12:03
We're probably going to deprecate one API in favour of the other, so let's imagine the best API, and use widening if and only doing that is compatible with the best API we can imagine. I'm AFK so it's hard for me to do that right now.

**Comment by alebedev80** [comment] 2023-12-21 12:16
> I don't need a lecture on prepared statements. 

I just thought that since someone was using embedded strings, it would not be unreasonable to tell them why they shouldn't. 💅

**Comment by greg0ire** [comment] 2023-12-21 13:46
If you know how to use the git pickaxe, you'll realize neither @derrabus nor I were there to review this piece of code, let alone write it. You may also find why it was written that way. I'd do that myself if I could, but again, AFK. So instead of preaching the choir, you could help design the new API, an upgrade path, or look at the history to confirm why modifyLimitQuery was designed this way in the first place. That would help.

**Comment by derrabus** [comment] 2023-12-21 13:53
I mean, the current API is not necessarily bad. Embedding limit and offset into the query can be just fine. It's just not a one-size-fits-all solution. Adding a second API that allows using parameters is probably the way to go.

**Comment by greg0ire** [comment] 2023-12-21 17:09
The current API, for future reference:

https://github.com/doctrine/dbal/blob/6a793fb72948c9dec844de57de8cdbc16ff75bec/src/Platforms/AbstractPlatform.php#L4324-L4376

**Comment by alebedev80** [comment] 2023-12-21 17:47
@greg0ire 👅

**Comment by greg0ire** [comment] 2023-12-21 21:38
@derrabus so `addPaginationClauses(string $sql, string|null $limitPlaceholder, string|null $offsetPlaceholder)`?
@alebedev80 sorry, I don't know what that emoji means.

**Comment by alebedev80** [comment] 2023-12-22 07:26
That's my propose. I could be wrong because my knowledge and understanding of this project is extremely poor.

https://github.com/doctrine/dbal/pull/6250

**Comment by alebedev80** [comment] 2023-12-22 07:47
Seems per \Doctrine\DBAL\Platforms\OraclePlatform::doModifyLimitQuery() need to implement some workaround.
Also i think query could be simplified to:

```
SELECT *
FROM your_table
ORDER BY some_column
OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY;
```

**Comment by derrabus** [comment] 2023-12-22 18:01
> @derrabus so `addPaginationClauses(string $sql, string|null $limitPlaceholder, string|null $offsetPlaceholder)`? 

* I don't think, "pagination" is a term, database vendors would use for that functionality.
* Do we need to make those nullable? Is there a use-case for parameterizing either limit or offset and omitting the other?

**Comment by greg0ire** [comment] 2023-12-22 19:28
Getting the top 10 best sellers seems like a use case for limit w/o offset. The ORM has 2 different setters BTW (`setMaxResults` and... another one maybe `setFirstResult`). Also, if we're going to tie limit and offset together, then calling those pagination clauses seems fair to me. The only thing I don't like with pagination is that it would refer to page number and items per page, do maybe there's a better term, will have to give that more thought.

**Comment by alebedev80** [comment] 2023-12-23 05:45
@greg0ire "pagination" presume it work with pages by call page number. IMHO pagination is a subset of all possible offset/limit use cases.

**Comment by alebedev80** [comment] 2023-12-23 05:58
Also limit|offset very close terms and one often using with another. IMHO need to combine them in class, .e.g.

```php
<?php

declare(strict_types=1);

namespace Doctrine\DBAL;

final class QueryLimitOffsetParams
{
    public const LIMIT_PLACEHOLDER = '__doctrine_limit_placeholder__';
    public const OFFSET_PLACEHOLDER = '__doctrine_offset_placeholder__';

    private ?int $limit;
    private int $offset;

    public function __construct(
        ?int $limit = null,
        int $offset = 0
    )
    {
        $this->limit = $limit;
        $this->offset = $offset;
    }

    public function getLimit(): ?int
    {
        return $this->limit;
    }

    public function setLimit(?int $limit): void
    {
        $this->limit = $limit;
    }

    public function getOffset(): int
    {
        return $this->offset;
    }

    public function setOffset(int $offset): void
    {
        $this->offset = $offset;
    }
    


}
```

**Comment by eugene-borovov** [comment] 2023-12-23 06:41
@alebedev80 you can use your solution right now. Just configure a driver with proper platform and connection.

```php
$conn = DriverManager::getConnection([
    'driver' => 'pdo_mysql',
    'platform' => new CustomMySQLPlatform(),
    'wrapperClass' => ConnectionWithCustomQueryBuilder::class,
]);
```

**Comment by alebedev80** [comment] 2023-12-23 06:59
@eugene-borovov i think, i can't use official doctrine/dbal package with custom platform class because offset|limit parameter doesn't pass to execute() method(

**Comment by alebedev80** [comment] 2023-12-23 07:00
@eugene-borovov thank you! i'll try

**Comment by eugene-borovov** [comment] 2023-12-23 08:31
Limit parameter names should be configured for every query builder instance. The query can contain subqueries and CTEs with different limits. I use several builders for subqueries, and then combine SQL and parameters in the final query.
> You must include a unique parameter marker for each value you wish to pass in to the statement when you call [PDOStatement::execute()](https://www.php.net/manual/en/pdostatement.execute.php). You cannot use a named parameter marker of the same name more than once in a prepared statement, unless emulation mode is on.

**Comment by greg0ire** [comment] 2023-12-23 11:08
`addLimitOffsetClauses` then? Since we cannot seem to find a better hypernym than "pagination". At least it's explicit.

**Comment by mpdude** [comment] 2024-01-18 23:24
(Automatically) finding unique parameter names may become a problem

**Comment by mpdude** [comment] 2024-01-19 11:32
`\Doctrine\DBAL\Platforms\AbstractPlatform::doModifyLimitQuery` is about adding platform-specific SQL for the limit/offset into the SQL string. My feeling is we'd need a similar method that would be able to do that with given parameter names.

Some of the methods do checks on offset/limit values, like non-negative offsets or maximum limits, which is not possible for parameters bound at a later time. `\Doctrine\DBAL\Platforms\DB2111Platform::doModifyLimitQuery` needs to use different SQL based on the concrete offset value, so ...? 🤷🏻‍♂️

**Comment by greg0ire** [comment] 2024-01-19 11:42
I'm unsure if the `111` in `DB2111Platform` is a typo or not. Can you please use a permalink, so that we're sure what you are talking about?

**Comment by mpdude** [comment] 2024-01-19 11:44
https://github.com/doctrine/dbal/blob/3a34a86701ea507e3c2e543ebc658e2f4f67a945/src/Platforms/DB2111Platform.php#L35

At least we'd need to know whether the offset will be zero or not at the time the method is called. 

Similar here:

https://github.com/doctrine/dbal/blob/3a34a86701ea507e3c2e543ebc658e2f4f67a945/src/Platforms/DB2Platform.php#L895-L901

**Comment by greg0ire** [comment] 2024-01-19 11:46
This means we might only be able to contribute this to DBAL 4: https://github.com/doctrine/dbal/blob/3a34a86701ea507e3c2e543ebc658e2f4f67a945/src/Platforms/DB2111Platform.php#L12-L13


For the other thing you found, maybe `db22.DC_ROWNUM >= 0` would be valid, and we could use `PHP_INT_MAX` for the other case?

**Comment by mpdude** [comment] 2024-01-19 11:50
Basically all of the platforms need to know about the limit and offset in one way or another... Checking if the limit is null or not null, the offset zero or greater than zero, exceeding technical limits etc. All this is not possible with parameter values bound at a later time.

Have a look at the various `doModifyLimitQuery` overrides in different platforms, it's discouraging.

**Comment by greg0ire** [comment] 2024-01-19 12:13
Ugh, indeed, no way this is going to work :(
Let's close this I suppose

**Closed as not planned by greg0ire** 2024-01-19 12:13 UTC
Labels: New Feature, Requires Feedback
