### ISSUE TITLE
FK violation exception is not converted to ForeignKeyConstraintViolationException with Sqlite

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5496] opened 2022-07-12 23:26 UTC
|    Q        |   A
|------------ | ------
| Version     | 3.3.7

#### Summary

Currently, a general DBAL driver exception is thrown even if the error code is 23000 representing a FK violation for Sqlite.

#### Current behaviour

DBAL driver exception is thrown.

#### How to reproduce

Insert a row violating at least one FK.

#### Expected behaviour

Instance of `ForeignKeyConstraintViolationException` exception is thrown (exception is converted).

**Comment by morozov** [comment] 2022-07-15 19:58
> Insert a row violating at least one FK.

Please be more specific. There are several scenarios like this covered by `Functional\ExceptionTest`.

Is the issue reproducible on `3.4.x`? It may have been fixed by https://github.com/doctrine/dbal/pull/5409.

**Comment by mvorisek** [comment] 2022-07-15 20:54
The https://github.com/doctrine/dbal/pull/5409 does not fix this issue.

Thank you for pointing to the tests - I will check.

**Comment by morozov** [comment] 2022-08-18 15:59
Closing due to the lack of feedback.

**Closed as not planned by morozov** 2022-08-18 15:59 UTC
Labels: SQLite, Foreign Keys, Cannot Reproduce

**Comment by mvorisek** [comment] 2022-08-18 16:12
weird, https://github.com/atk4/data/blob/9e7a43525bd887eb01145076ede775bb4e621553/src/Persistence/Sql/DbalDriverMiddleware.php#L119 is needed in atk4/data to pass the tests

did you try to reproduce?
