### ISSUE TITLE
Custom PDO fetch modes and 2.7.0

### ISSUE THREAD

**Issue by corphi** [doctrine/dbal#3082] opened 2018-04-04 09:29 UTC
[Announced](https://github.com/doctrine/dbal/releases/tag/v2.7.0) as a deprecation only, an [exception is thrown](https://github.com/doctrine/dbal/blob/f76bf5ef631cec551a86c2291fc749534febebf1/lib/Doctrine/DBAL/Driver/PDOStatement.php#L234) when passing unrecognized fetch modes, such as `PDO::FETCH_KEY_PAIR`. That is a BC break. In another instance, a [silenced deprecation warning](https://github.com/doctrine/dbal/blob/f76bf5ef631cec551a86c2291fc749534febebf1/lib/Doctrine/DBAL/Schema/Column.php#L129) is issued instead.

While I completely agree on deprecating implicit usage of PDO features, I'd like a migration path that does not involve breaking working code. I suppose that some code depends on recognized fetch modes; I will investigate this and want to provide a pull request.

**Comment by Ocramius** [comment] 2018-04-04 09:33
@corphi unlikely happened intentionally: if you have a piece of code that reproduces the regression, we can make a patch release with a fix.

**Comment by alongosz** [comment] 2018-04-04 10:04
@Ocramius for us it also breaks a [piece of code](https://github.com/ezsystems/ezpublish-kernel/blob/v7.1.0/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationListConverter.php#L335).
We have the usage:
`$stmt->fetchAll(PDO::FETCH_ASSOC | PDO::FETCH_GROUP)` (it was fine since [PDOStatement::fetchAll doc](http://php.net/manual/en/pdostatement.fetchall.php) allowed bitwise-ORs for the `fetch_style` argument).

While we can of course refactor the code to use `FETCH_ASSOC` only and some `array_*` magic, I'm rather still in favor of silenced deprecation warning instead :)

**Comment by Ocramius** [comment] 2018-04-04 10:41
Uhhh, I think we never considered bitmasking fetch modes on our side, so that is most likely lack of knowledge on our end.

**Comment by dbu** [comment] 2018-04-04 11:42
We see the problem coming up in PHPCR-ODM (because dbal is used in jackalope-doctrine-dbal) as well: https://travis-ci.org/doctrine/phpcr-odm/jobs/361545802#L474

Is there an easy fix for this? And should we change code that relied on this, or is it an intended feature?

**Comment by andrerom** [comment] 2018-04-04 12:49
Same here, seeing the bitmasking fetch modes hitting us, breaking stable releases out there.

**Comment by Ocramius** [comment] 2018-04-04 13:52
Test cases please: adding "me too" is **NOT** useful

**Comment by Majkl578** [comment] 2018-04-04 13:56
Likely side-effect of #2996.

**Closed** 2018-04-07 04:44 UTC
Labels: BC Break, Bug, Missing Tests, PDO, Regression
