### ISSUE TITLE
Lost parameters: wrong ESCAPED_BRACKET_QUOTED_TEXT

### ISSUE THREAD

**Issue by riccardonar** [doctrine/dbal#3140] opened 2018-05-11 09:28 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.5.7

#### Summary

This commit https://github.com/doctrine/dbal/commit/3a351369582dade60c750e2cef540eb7b568e6b3 change preg_match_all and not consider the shortest match so can lost some parameters

#### Current behavior

`Doctrine\DBAL\SQLParserUtils::getUnquotedStatementFragments` for this statement

``` php
$statement = "SELECT table.field1, ARRAY['3']::integer[]
FROM schema.table table
WHERE table.f1 = :some AND ARRAY['3']::integer[]";
```

return this array

``` php
Array
(
    [0] => Array
        (
            [0] => SELECT table.f1, ARRAY
            [1] => 0
        )

    [1] => Array
        (
            [0] => 3
            [1] => 24
        )

    [2] => Array
        (
            [0] => 3
            [1] => 97
        )

    [3] => Array
        (
            [0] => ]::integer
            [1] => 99
        )
)
```

without sql part with `table.f1 = :some` so parameter `some` is lost

#### How to reproduce

``` php
$statement = "SELECT table.field1, ARRAY['3']::integer[]
FROM schema.table table
WHERE table.f1 = :some AND ARRAY['3']::integer[]";

$fragments = \Doctrine\DBAL\SQLParserUtils::getUnquotedStatementFragments($statement);
print_r($fragments);
```

#### Expected behavior

from previous version, something like this:

``` php
Array
(
    [0] => Array
        (
            [0] => SELECT table.f1, ARRAY
            [1] => 0
        )

    [1] => Array
        (
            [0] => ::integer
            [1] => 27
        )

    [2] => Array
        (
            [0] => 
FROM schema.table table
WHERE table.f1 = :some AND ARRAY
            [1] => 38
        )

    [3] => Array
        (
            [0] => ::integer
            [1] => 100
        )
)
```

**Comment by ohvitorino** [comment] 2018-07-23 13:41
I'm facing the same problem.

I'm upgrading an application that used doctrine/dbal version 2.3.5 to 2.5.14.

I managed to figure out that the problem might lie on the method: `\Doctrine\DBAL\SQLParserUtils::getUnquotedStatementFragments`. The regular expression used to split the query in fragments has change since 2.3.5. This causes, as far as I can see, the query fragments to be incorrectly determined.

**Comment by Ocramius** [comment] 2018-07-23 13:46
@ohvitorino send a fix with a test then :+1:

**Comment by ohvitorino** [comment] 2018-07-23 14:56
After looking a little bit further it seems that in my case the problem is a bit different that the one reported by @riccardonar .

In my case the query uses `array[...]` instead of `ARRAY[...]` this is, from what could find in the Postgresql documentation, valid syntax. So the regex `const ESCAPED_BRACKET_QUOTED_TEXT = '(?<!\bARRAY)\[(?:[^\]])*\]';` should be changed to allow to match both 'array' and 'ARRAY'.

**Comment by morozov** [comment] 2018-10-21 12:18
Fixed by https://github.com/doctrine/dbal/pull/3277.

**Closed by morozov** 2018-10-21 12:18 UTC
