### ISSUE TITLE
driver syntax is not the same in doctrine.dbal.driver and doctrine.dbal.url

### ISSUE THREAD

**Issue by FanchTheSystem** [doctrine/dbal#3129] opened 2018-05-04 15:44 UTC
Hello,

Using last symfony, in the file : config/packages/doctrine.yaml 

For driver it work only with _
```
 doctrine:
     dbal: 
         driver:           'pdo_psql'
```

For url it work only with -
```
doctrine:
    dbal: 
        url:           'pdo-pgsql://...'
```

So you can't have in your .env file somerthing like:
`
DATABASE_URL=${DBDRIVER}://...
`

Maybe you should add an alias or two ;)

It is the same for mysql as example:
https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url

**Comment by Majkl578** [comment] 2018-05-04 16:02
Underscore is not valid character for URI scheme, thus `-` is used as a workaround.
It's translated back here: https://github.com/doctrine/dbal/blob/f76bf5ef631cec551a86c2291fc749534febebf1/lib/Doctrine/DBAL/DriverManager.php#L398-L424

**Comment by morozov** [comment] 2018-05-27 05:29
I’d leave it as is and have properly documented. Also, made sure error messages are helpful.

**Comment by FanchTheSystem** [comment] 2018-05-28 08:47
Yes I think the only "clean" solution is to have an explicit warning in the documentation.
And maybe recommend usage of shorter version like 'plsql'

**Comment by morozov** [comment] 2021-11-02 04:16
Closing as the originally reported issue is by design.

**Closed by morozov** 2021-11-02 04:16 UTC
Labels: Requires Feedback, Configuration
