### ISSUE TITLE
Unit tests on PHP7 and Oracle are failing badly ....

### ISSUE THREAD

**Issue by DeepDiver1975** [doctrine/dbal#2257] opened 2015-12-11 14:29 UTC
````
/home/deepdiver/.phpenv/versions/7.0.0/bin/php /tmp/ide-phpunit.php --configuration /home/deepdiver/Development/ownCloud/doctrine2/dbal/tests/travis/oracle.travis.xml
Testing started at 15:15 ...
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from /home/deepdiver/Development/ownCloud/doctrine2/dbal/tests/travis/oracle.travis.xml

````

SNIPP

````
 

An exception occurred while executing 'CREATE USER doctrine IDENTIFIED BY oracle':

ORA-01920: user name 'DOCTRINE' conflicts with another user or role name
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:76
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/lib/Doctrine/DBAL/DBALException.php:116
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/lib/Doctrine/DBAL/Connection.php:992
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/lib/Doctrine/DBAL/Schema/OracleSchemaManager.php:306
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:596
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/tests/Doctrine/Tests/TestUtil.php:93
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/tests/Doctrine/Tests/TestUtil.php:52
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/tests/Doctrine/Tests/TestUtil.php:43
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/tests/Doctrine/Tests/DbalFunctionalTestCase.php:35
 /home/deepdiver/Development/ownCloud/doctrine2/dbal/tests/Doctrine/Tests/DBAL/Functional/BlobTest.php:15
 

````

SNIPP

````


Time: 3.4 seconds, Memory: 90.00Mb


FAILURES!
Tests: 3699, Assertions: 6665, Errors: 606, Skipped: 52, Incomplete: 11.

Process finished with exit code 2

**Comment by pdgcvs** [comment] 2015-12-13 14:54
Looks like a new version of OCI8 ext was released for PHP 7.

https://pecl.php.net/package/oci8/2.1.0

Maybe it helps.

**Comment by arcostasi** [comment] 2015-12-13 19:26
Great! the php community is giving your best! thanks

**Comment by Ocramius** [comment] 2015-12-13 19:29
Also 2.0.10 released, as it seems.

**Comment by arcostasi** [comment] 2015-12-14 01:28
Functionality in 2.0.10 and 2.1.0 is equivalent.
https://blogs.oracle.com/opal/entry/php_7_oci8_2_1

**Comment by deeky666** [comment] 2016-01-06 12:13
@DeepDiver1975 I cannot reproduce this error. I am getting another error a lot which seems to be related to #2261. 

```
php -v
PHP 7.0.0 (cli) (built: Dec 14 2015 15:05:59) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

vendor/bin/phpunit -c oci8.phpunit.xml 
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

..............................................SSS...........S   61 / 3756 (  1%)
S..............S.......SS...S.....S.SSS..............SS......  122 / 3756 (  3%)
.....SSS.............SS...SSS.........SS...S............S.S..  183 / 3756 (  4%)
...S...............................E

Time: 2.18 seconds, Memory: 26.00Mb

There was 1 error:

1) Doctrine\Tests\DBAL\Functional\BlobTest::testInsert
Exception: [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'INSERT INTO blob_table (id, clobfield, blobfield, binaryfield) VALUES (?, ?, ?, ?)' with params [1, "test", "test", "test"]:

ORA-01722: invalid number

With queries:
5. SQL: 'INSERT INTO blob_table (id, clobfield, blobfield, binaryfield) VALUES (?, ?, ?, ?)' Params: '1', 'test', 'test', 'test'
4. SQL: 'TRUNCATE TABLE blob_table' Params: 
3. SQL: 'CREATE TABLE blob_table (id NUMBER(10) NOT NULL, clobfield CLOB NOT NULL, blobfield BLOB NOT NULL, binaryfield RAW(50) NOT NULL, PRIMARY KEY(id))' Params: 
2. SQL: 'ALTER SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS = '.,'' Params: 

Trace:
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:142
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:992
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:692
/home/deeky/dev/doctrine/dbal/tests/Doctrine/Tests/DBAL/Functional/BlobTest.php:42
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:908
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:768
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestResult.php:612
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:440
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/src/TextUI/Command.php:149
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/src/TextUI/Command.php:100
/home/deeky/dev/doctrine/dbal/vendor/phpunit/phpunit/phpunit:47


/home/deeky/dev/doctrine/dbal/tests/Doctrine/Tests/DbalFunctionalTestCase.php:73

Caused by
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO blob_table (id, clobfield, blobfield, binaryfield) VALUES (?, ?, ?, ?)' with params [1, "test", "test", "test"]:

ORA-01722: invalid number

/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:76
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:142
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:992
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:692
/home/deeky/dev/doctrine/dbal/tests/Doctrine/Tests/DBAL/Functional/BlobTest.php:42

Caused by
Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01722: invalid number

/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:983
/home/deeky/dev/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:692
/home/deeky/dev/doctrine/dbal/tests/Doctrine/Tests/DBAL/Functional/BlobTest.php:42

FAILURES!
Tests: 219, Assertions: 1699, Errors: 1, Skipped: 29.
```

Maybe there is something wrong with your phpunit configuration? What does your configuration file look like? Mine looks like the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/4.8/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="vendor/autoload.php"
>
  <php>
    <ini name="error_reporting" value="-1" />

    <var name="db_type" value="oci8"/>
    <var name="db_host" value="127.0.0.1" />
    <var name="db_username" value="C##doctrine" />
    <var name="db_password" value="sql" />
    <var name="db_name" value="orcl" />
    <var name="db_port" value="1521"/>
    <var name="db_event_subscribers" value="Doctrine\DBAL\Event\Listeners\OracleSessionInit"/>

    <var name="tmpdb_type" value="oci8"/>
    <var name="tmpdb_host" value="127.0.0.1" />
    <var name="tmpdb_username" value="SYSTEM" />
    <var name="tmpdb_password" value="sql" />
    <var name="tmpdb_name" value="orcl" />
    <var name="tmpdb_port" value="1521"/>
  </php>

    <testsuites>
        <testsuite name="Doctrine DBAL Test Suite">
            <directory>./tests/Doctrine/Tests/DBAL</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

**Comment by DeepDiver1975** [comment] 2016-01-06 14:49
I will update my PHP 7 tomorrow and post results

**Comment by DeepDiver1975** [comment] 2016-01-07 11:20
> An exception occurred while executing 'CREATE USER doctrine IDENTIFIED BY oracle': ORA-01920: user name 'DOCTRINE' conflicts with another user or role name

@deeky666 this is yet another uppercase vs lowercase issue somewhere .....

it works with uppercase username - but lowercase produces the error abore
```xml
        <var name="db_username" value="DOCTRINE" />
```


```xml
        <var name="db_username" value="doctrine" />
```

**Comment by deeky666** [comment] 2016-01-07 11:53
@DeepDiver1975 ah that's a good hint. Is this casing issue really a PHP related issue then? Does it work lowercased in PHP < 7? If so we might need to do a deeper investigation in Doctrine as to where this is originated.

**Comment by deeky666** [comment] 2016-01-07 11:55
Hmm looking at my configuration again, I wonder why it works for me with a lowercased database name. Can you maybe have a look what the casing of your database name really is (just to be sure)?

**Comment by DeepDiver1975** [comment] 2016-01-07 12:06
> @DeepDiver1975 ah that's a good hint. Is this casing issue really a PHP related issue then? Does it work lowercased in PHP < 7? If so we might need to do a deeper investigation in Doctrine as to where this is originated.

I'll quickly reelaborate on this ...

Regarding the database setup - it's a 11g XE out of the box .... äh docker :wink: 
https://github.com/DeepDiver1975/docker-oracle-xe-11g

**Comment by DeepDiver1975** [comment] 2016-01-07 13:24
> I'll quickly reelaborate on this ...

bääh - no longer reproducible :imp:

**Comment by deeky666** [comment] 2016-01-07 13:26
@DeepDiver1975 well as I am also not getting this error, I will close this issue for now. If you encounter it again some time, just poke me.

**Closed by deeky666** 2016-01-07 13:26 UTC
Labels: Requires Feedback

**Comment by DeepDiver1975** [comment] 2016-01-07 13:28
> just poke me.

sure

**Comment by lbonhomme** [comment] 2016-08-25 15:06
Hi,

Just to let you know...
I get a reproductible error when I try to insert a simple record (i.e. in Album table) using Doctrine's OCI8 driver.  
I get a 'ORA-01722: invalid number' error : 
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO Album (ID, title, artist) VALUES (?, ?, ?)' with params [6, "AAA", "DDD"]

When I change from OCI driver to PDOOracle driver, it works perfectly.

I'm using PHP 7.0.4 with latest versions of ZF2/Doctrine and Oracle 11 

'hope that can help ...
