### ISSUE TITLE
Misleading Not Unique Alias Error Message in 2.5.2 Release

### ISSUE THREAD

**Issue by redstrike** [doctrine/dbal#2399] opened 2016-05-19 16:23 UTC
Misleading Not Unique Alias Error Message in 2.5.2 Release https://github.com/doctrine/dbal/issues/1262 (Is there any fix for this issue?)

I cannot update to the latest dbal version due to this problem from 2.5.2. It seems that the bug happens after this fix https://github.com/doctrine/dbal/issues/1079. I am keeping dbal at 2.5.1 now.

**Comment by deeky666** [comment] 2016-06-30 17:46
@redstrike can you please provide the failing query builder code then I can have a look. Thanks.

**Comment by redstrike** [comment] 2016-07-03 22:08
@deeky666: This SQL query works normally on DBAL 2.5.1 and below. But it's no longer work since 2.5.2 release.
```sql
SELECT d.m_id, m_title, m_url, m_type, m_cat, s.singer_id, s.singer_name, s.singer_img, s.is_picked, m_viewed_week, (st.m_viewed + st.m_viewed_week + st.m_viewed_day) / POW(days_from_created + 1, 1.36) AS trending_rank
FROM (SELECT m_id, m_title, m_singer, m_url, m_type, m_cat, m_is_local, DATEDIFF(NOW(), m_date) AS days_from_created FROM media_data WHERE m_cat = 2 ORDER BY m_id DESC LIMIT 288) d
INNER JOIN media_stats st ON d.m_id = st.m_id
INNER JOIN media_singer s ON d.m_singer = s.singer_id
WHERE m_cat = 2 ORDER BY trending_rank DESC
LIMIT 18 OFFSET 36
```

Below is the dump screenshot of $queryBuilder (I couldn't use getSQL()):

![dump querybuilder](https://cloud.githubusercontent.com/assets/2168227/16547833/acf3398a-41a4-11e6-9dbc-13af277ae608.png)

And the error messages:
```
Fatal error: Uncaught Doctrine\DBAL\Query\QueryException: The given alias 'st' is not unique in FROM and JOIN clause table. The currently registered aliases are: d, st, s.
Doctrine\DBAL\Query\QueryException: The given alias 'st' is not unique in FROM and JOIN clause table. The currently registered aliases are: d, st, s.
```

**Comment by inkognitro** [comment] 2019-02-26 12:44
Same issue. For me it was because I added same join twice accidentally. What made my life difficult to debug was: The SQL string was correct but the QueryBuilder returned the error message above.

**Comment by Ocramius** [comment] 2019-02-26 15:44
@inkognitro we'd need a test case to verify what is misleading in the error message.

**Comment by Moongazer** [comment] 2020-11-25 17:21
I've the same error with Doctrine DBAL v2.12. The query works (is executed and returns the desired result), but the extension is thrown: `The given alias 'c' is not unique in FROM and JOIN clause table. The currently registered aliases are: ue, c.`

```
$result = $queryBuilder->select('c.name', 'ue.enrolled_at')
  ->from('user_enrollment', 'ue')
  ->join('ue', 'class', 'c', $queryBuilder->expr()->eq('c.id', $queryBuilder->quoteIdentifier('ue.class_id')))
  ->where($queryBuilder->expr()->eq('ue.user_id', 123))
  ->execute()->fetchAllAssociative();
```

**Comment by morozov** [comment] 2022-02-17 19:21
Closing as missing a reproducer.

**Closed by morozov** 2022-02-17 19:21 UTC
Labels: Missing Tests, Bug, QueryBuilder
