### ISSUE TITLE
Tests are 4x slower on Oracle since DBAL v3.4.0

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5698] opened 2022-09-27 12:41 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.4.0

#### Summary

Not sure what is exactly the problem, but since upgrade to DBAL v3.4.x, the CI takes ~7 minutes for Oracle vs. ~1.5 minutes before.

#### Current behaviour

before https://github.com/atk4/data/actions/runs/3133960125/jobs/5087921285#step:17:27, https://github.com/atk4/data/actions/runs/3133376169/jobs/5086678758#step:17:27
after https://github.com/atk4/data/actions/runs/3135574120/jobs/5091417197#step:17:27

# Steps to reproduce

run atk4/data tests like in the CI:

https://github.com/atk4/data/blob/c30e90879bbf21ec946d648ee112d32b90edc9fd/.github/workflows/test-unit.yml#L236-L245

**Comment by morozov** [comment] 2022-09-27 14:58
This is not necessarily caused by the DBAL. See https://github.com/doctrine/orm/pull/9839 for example. The DBAL's own test suite became 40% faster as of https://github.com/doctrine/dbal/pull/5268 (`3.4.0`).

You'll need to provide more details for this issue to be considered.

**Comment by mvorisek** [comment] 2022-09-28 10:30
Any idea what the issue can be? Please see the diff - https://github.com/atk4/data/compare/8d1b2b2d3092432f832356226c6d4b4716e4d717 - no other change than DBAL version was made. Tested multiple times, same results.

Also, it seems you blocked me in the past in your GH account, I am sorry if I upset you, but this action stopped a notifications from you nor I am unable to comment on some of your php-src issues.

**Comment by morozov** [comment] 2022-09-28 16:33
I blocked you because communication with you takes a lot of time and energy. You're saying you are sorry but at the same time when requested to provide more details you provide a link to the diff which changes the DBAL version, which is already known. As a result: time spent on interaction leads to zero progress.

**Comment by morozov** [comment] 2022-10-02 17:38
Closing as previously warned in https://github.com/doctrine/dbal/issues/5508#issuecomment-1186046795.

**Closed as not planned by morozov** 2022-10-02 17:38 UTC
Labels: Oracle, Performance, Cannot Reproduce

**Comment by mvorisek** [comment] 2022-10-16 12:19
before:

![image](https://user-images.githubusercontent.com/2228672/196035037-59f0aec1-830f-469e-af80-4e2630e84faf.png)

after:

![image](https://user-images.githubusercontent.com/2228672/196035044-2fe35183-1558-4544-8df6-0c4e4e7a3a65.png)

problem is described in https://github.com/doctrine/dbal/issues/5764, related with https://github.com/doctrine/dbal/pull/5268 change
