### ISSUE TITLE
Floating point precision changes are not detected as changes

### ISSUE THREAD

**Issue by andrei-dascalu** [doctrine/dbal#3672] opened 2019-09-05 13:39 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.1.1

#### Current behavior

Float column precision updates are ignored when generating a diff

#### How to reproduce

Given the a current column declaration 

    /**
     * @var float
     *
     * @ORM\Column(name="predicted_cost", type="float", precision=6, scale=2, nullable=true)
     */
    private $predictedCost;

updating it to 

    /**
     * @var float
     *
     * @ORM\Column(name="predicted_cost", type="float", precision=12, scale=2, nullable=true)
     */
    private $predictedCost;

and running diff after clearing metadata cache

php vendor/bin/doctrine-migrations migrations:diff

results in no changes detected

#### Expected behaviour

A diff is generated with an appropriate ALTER TABLE statement

**Comment by lcobucci** [comment] 2019-09-05 17:39
@andrei-dascalu that's the expected behaviour since the `float` type is meant for approximate values.

According to SQL standards, the type `FLOAT` permits an optional specification for the precision (but not a range). MySQL allows a non-standard definition but that's not used by us. 

DBAL always use `DOUBLE` as db type (to simplify things internally), so the precision is irrelevant during the comparison.

If you do want to use the range you might look at the `decimal` type.

**Comment by lcobucci** [comment] 2019-09-10 07:10
Closing as invalid as per my explanation.

**Closed by lcobucci** 2019-09-10 07:10 UTC
Labels: Bug, Invalid
