### ISSUE TITLE
BC Break in Date/Time related types: can no longer convert `DateTimeImmutable` to database value

### ISSUE THREAD

**Issue by langj** [doctrine/dbal#2794] opened 2017-07-27 15:11 UTC
I think there should be a BC Break Notice in the UPGRADE.md file.

The following example code will break when switching from 2.5 to 2.6.

~~~ php
public function findUsersNewerThan(\DateTimeImmutable $dateTime)
{
    $qb = $this->connection->createQueryBuilder();
    $qb->select('*')
        ->from('user')
        ->where('created_at > :date')
        ->setParameter(':date', $dateTime, Type::DATETIME);
    // [...]
}
~~~

When I read #2678 correctly, this is intentional behaviour so there wont be a fix for it.

**Comment by lcobucci** [comment] 2017-07-27 15:32
@langj I think you misread something, that PR was NOT merged to avoid BC breaks. You should use `Type:: DATE_IMMUTABLE` in order to use `DateTimeImmutable` objects.

`Type::DATETIME` only supports `\DateTime` (on 2.5 and 2.6).

**Comment by langj** [comment] 2017-07-27 16:18
@lcobucci Thanks for your response.
I referenced this PR because it showed me, that `Type::DATETIME` intentionally dropped support for `DateTimeImmutable`.
However, I am currently using `DateTimeImmutable` in my Project and I use `Type::DATETIME` to store it because `Type::DATETIME_IMMUTABLE` is not available and it works well with 2.5.12 and 2.5.13.
When I update to 2.6.0 I get a 

> ConversionException in ConversionException.php line 95:
Could not convert PHP value of type 'DateTimeImmutable' to type 'datetime'. Expected one of the following types: null, DateTime

(which, I now know, is intended)

But it  looks like a BC Break to me as previous supported usage now results in an Exception. So I think should be documented, shouldnt it?

**Comment by jvasseur** [comment] 2017-07-27 17:16
The fact that the datetime type worked with both DateTime and DateTimeImmutable instances was an implementation detail, it never was officially supported so this isn't a BC break.

**Comment by Ocramius** [comment] 2017-07-27 17:18
It is: userland code broke, so we need to revert it.

On 27 Jul 2017 20:16, "Jérôme" <notifications@github.com> wrote:

The fact that the datetime type worked with both DateTime and
DateTimeImmutable instances was an implementation detail, it never was
officially supported so this isn't a BC break.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/dbal/issues/2794#issuecomment-318427922>, or mute
the thread

**Comment by Ocramius** [comment] 2017-07-27 18:01
Please check https://github.com/doctrine/dbal/pull/2795 - I provided a fix and can gladly do a release with it later tonight

**Comment by Majkl578** [comment] 2017-07-27 20:44
@enumag Isn't this the issue you ran into?

**Comment by enumag** [comment] 2017-07-27 20:59
@Majkl578 One of them, yes.

**Comment by lcobucci** [comment] 2017-07-27 21:16
You're quite right about this, it was actually caused by https://github.com/doctrine/dbal/pull/869.

**Comment by Ocramius** [comment] 2017-07-28 10:35
Handled in #2795

**Closed** 2017-07-28 10:34 UTC
Labels: Bug, Type Conversion

**Comment by Ocramius** [comment] 2017-07-28 10:36
`master`: doctrine/dbal@3a6110f2499938244334b5fd88ebd6d40cd49417
`2.6` doctrine/dbal@dd7d1fc2b8b43a609f52912d4f2b4f752c7e9498
