### ISSUE TITLE
PDO\Exception doesn't handle driver-specific error code being NULL

### ISSUE THREAD

**Issue by TimurFlush** [doctrine/dbal#5130] opened 2021-12-19 05:02 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.0

When a PDO error occurs, the ::errorInfo() method returns the internal error code of the internal PDO driver.
This error then goes into the Doctrine\Dbal\Driver\Pdo\Exception class, which converts the information from PDO::errorInfo() into a Doctrine exception.
What Doctrine means is that PDO::errorInfo() always returns an integer error code, but sometimes it may return null.
Because of this, I get the following exception: [![image.png](https://i.postimg.cc/0yJPxDvp/image.png)](https://postimg.cc/TKGZJypw)

This is because PDO does not return an error code for error HY093 in Postgresql:
[![image.png](https://i.postimg.cc/RFZYCxtj/image.png)](https://postimg.cc/zL47pM0j)

I won't say any more about it. I'm just bringing this point to your attention.)

**Comment by morozov** [comment] 2021-12-19 06:06
@TimurFlush please provide the steps to reproduce the issue.

**Comment by TimurFlush** [comment] 2021-12-19 21:33
> @TimurFlush please provide the steps to reproduce the issue.

I'm lazy
This happens when doctrine encounters an unexpected parameter during executeQuery()

p.s. php 8 & postgresql 13

**Comment by morozov** [comment] 2021-12-19 21:34
Closing as cannot reproduce.

**Comment by bertrandjamin** [comment] 2022-01-13 10:25
@morozov I encounter the same issue if some parameters are wrongly named. 

You can reproduce it via a call of this type 
```
        /**
         * Table structure
         * CREATE TABLE "public"."test" (
         *  "label" text
         * );
         *
         */
        $connection = $this->entityManager->getConnection();

        $sqlInsert = $connection
            ->createQueryBuilder()
            ->insert('test')
            ->values(['label' => ':libellé'])
            ->getSQL();

        $stmt = $connection->prepare($sqlInsert);
        $stmt->executeStatement(['libellé' => 'my label']);
```

This call generate this Exception 
```
TypeError {#574
  #message: "Exception::__construct(): Argument #2 ($code) must be of type int, null given"
  #code: 0
  #file: "./vendor/doctrine/dbal/src/Driver/AbstractException.php"
  #line: 34
  trace: {
    ./vendor/doctrine/dbal/src/Driver/AbstractException.php:34 { …}
    ./vendor/doctrine/dbal/src/Driver/PDO/Exception.php:26 { …}
    ./vendor/doctrine/dbal/src/Driver/PDO/Statement.php:94 { …}
    ./vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php:77 { …}
    ./vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/TracingStatementForV3.php:43 { …}
    ./vendor/doctrine/dbal/src/Statement.php:189 { …}
    ./vendor/doctrine/dbal/src/Statement.php:230 { …}
    ./src/Integration/Commands/RefreshCommand.php:130 {
      App\Integration\Commands\RefreshCommand->execute(InputInterface $input, OutputInterface $output): int^
      › $stmt = $connection->prepare($sqlInsert);
      › $stmt->executeStatement(['libellé' => 'my label']);
      › die;
      arguments: {
        $params: array:1 [ …1]
      }
    }
    ./vendor/symfony/console/Command/Command.php:299 { …}
    ./vendor/symfony/console/Application.php:996 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:96 { …}
    ./vendor/symfony/console/Application.php:295 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:82 { …}
    ./vendor/symfony/console/Application.php:167 { …}
    ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:56 { …}
    ./vendor/autoload_runtime.php:35 { …}
    ./bin/console:11 { …}
  }
}
```

As told by @TimurFlush  earlier the real PgSql error would be `SQLSTATE[HY093]: Invalid parameter number: :libellé`

But this one has no code associated
```
#message: "SQLSTATE[HY093]: Invalid parameter number: :libellé"
        #code: "HY093"
        #file: "./vendor/doctrine/dbal/src/Driver/PDO/Statement.php"
        #line: 101
        +errorInfo: array:3 [
          0 => "HY093"
          1 => null
          2 => ":libellé"
        ]
```

The issue occurs in the file  vendor/doctrine/dbal/src/Driver/PDO/Exception.php

```
<?php

declare(strict_types=1);

namespace Doctrine\DBAL\Driver\PDO;

use Doctrine\DBAL\Driver\AbstractException;
use PDOException;

/**
 * @internal
 *
 * @psalm-immutable
 */
final class Exception extends AbstractException
{
    public static function new(PDOException $exception): self
    {
        if ($exception->errorInfo !== null) {
            // errorInfo is not null but errorInfo['code'] is null
            [$sqlState, $code] = $exception->errorInfo;
        } else {
            $code     = $exception->getCode();
            $sqlState = null;
        }
        // AbstractException does not allow null value for $code
        return new self($exception->getMessage(), $sqlState, $code, $exception);
    }
}
```

I hope that it is clear enough

**Comment by morozov** [comment] 2022-01-13 16:55
Thanks for the details, @bertrandjamin. The issue is indeed reproducible with the following snippet:
```php
$connection = /* connect to PostgreSQL */;

$stmt = $connection->prepare('SELECT :foo');
$stmt->executeStatement(['bar' => 'baz']);
```

**Comment by bertrandjamin** [comment] 2022-01-13 17:05
Yes it's a bit more simple  ^^

**Closed as completed** 2022-01-23 15:14 UTC
Labels: Bug, Error Handling
